/**
 * Workspace Knowledge — the Scenarios tab's guard reads + explicit generation
 * (enterprise, org-scoped). Scenarios are generated by an EXPLICIT action (not by
 * Process): estimate → confirm → a `knowledge.guard` job that runs the shared
 * in-process guard generate over the workspace corpus and persists the scenario set
 * under workspace scope. The object shapes mirror the repo `/guard/*` reads so the
 * reused guard components render the workspace scenarios unchanged.
 *
 *   - `POST /guard/estimate` — the pre-flight token/cost estimate over a scratch
 *     tree of the corpus's kept docs (deterministic; no LLM, no persistence).
 *   - `POST /guard/generate` — 409 while any spec conflict is open (the SAME shared
 *     `openConflicts` derivation the repo gate uses) or a generate is already
 *     running; else enqueues the org-scoped single-flight job (202 { jobId }).
 *   - `GET /guard/coverage` · `GET /guard/scenario?id=` — the scenario-corpus reads.
 *
 * Generation reads ONLY the corpus's kept docs (relevance-filtered, bounded) from
 * their STORED bodies via the ledger — no connector I/O — so it never sweeps the raw
 * source (thousands of tickets) and works even after a source is disconnected.
 */

import { Router, type Request, type Response, type NextFunction } from 'express';
import type { AuthUser } from '@truecourse/shared';
import { openConflicts } from '@truecourse/shared';
import { loadWorkspaceSpec } from '@truecourse/core/lib/spec-store';
import {
  getWorkspaceDecisions,
  type CuratedCorpus,
} from '@truecourse/core/commands/spec-in-process';
import {
  estimateWorkspaceGuard,
  readWorkspaceGuardCoverage,
  readWorkspaceGuardScenario,
  formatOpenConflictsMessage,
} from '@truecourse/core/commands/guard-in-process';
import { PgKnowledgeStore, ActiveJobExistsError } from '@truecourse/ee-data-store';
import { isLlmConfigured, NO_LLM_PROVIDER_MESSAGE } from '../llm/index.js';
import type { JobsApi } from '../jobs/index.js';
import { KNOWLEDGE_GUARD_TASK, workspaceGuardJobKey } from '../jobs/constants.js';
import { fetchWorkspaceGuardDocs } from './guard.js';

function orgIdOf(req: Request): string | null {
  return (req as Request & { eeUser?: AuthUser }).eeUser?.organizationId ?? null;
}

interface GuardRouteDeps {
  knowledge: PgKnowledgeStore;
  jobs: JobsApi;
}

export function registerKnowledgeGuardRoutes(router: Router, deps: GuardRouteDeps): void {
  const { knowledge, jobs } = deps;

  // --- Reads -----------------------------------------------------------------

  // The Scenarios-tab coverage payload: the last-generate report + recipe card +
  // committed inventory (same pieces the repo guard reads carry). Always 200 (each
  // piece is null/empty until a generate has run), so the tab renders its own states.
  router.get('/guard/coverage', async (req: Request, res: Response, next: NextFunction) => {
    try {
      const org = orgIdOf(req);
      if (!org) return res.status(401).json({ error: 'no workspace' });
      res.json(await readWorkspaceGuardCoverage(org));
    } catch (e) {
      next(e);
    }
  });

  // One committed scenario's YAML source by id (the row preview).
  router.get('/guard/scenario', async (req: Request, res: Response, next: NextFunction) => {
    try {
      const org = orgIdOf(req);
      if (!org) return res.status(401).json({ error: 'no workspace' });
      const id = String(req.query.id ?? '');
      if (!id) return res.status(400).json({ error: 'Missing ?id=<scenario id>.' });
      const source = await readWorkspaceGuardScenario(org, id);
      if (!source) return res.status(404).json({ error: `Scenario not found: ${id}` });
      res.json(source);
    } catch (e) {
      next(e);
    }
  });

  // --- Estimate (pre-flight, synchronous) ------------------------------------
  // Deterministic token math over the corpus's kept docs — no LLM call, so it runs
  // even with no provider configured (the provider gate lives on /guard/generate).
  // 404 before the first process (nothing to generate scenarios from yet).
  router.post('/guard/estimate', async (req: Request, res: Response, next: NextFunction) => {
    try {
      const org = orgIdOf(req);
      if (!org) return res.status(401).json({ error: 'no workspace' });
      const corpus = await loadWorkspaceSpec<CuratedCorpus>({ workspaceOrgId: org }, 'corpus');
      if (!corpus) {
        return res.status(404).json({ error: 'No workspace corpus yet. Process a connected source first.' });
      }
      const [docs, decisions] = await Promise.all([
        fetchWorkspaceGuardDocs({ knowledge }, org),
        getWorkspaceDecisions(org),
      ]);
      const estimate = await estimateWorkspaceGuard({ workspaceOrgId: org, docs, decisions });
      res.json({ estimate });
    } catch (e) {
      next(e);
    }
  });

  // --- Generate (explicit; org-scoped single-flight job) ---------------------
  router.post('/guard/generate', async (req: Request, res: Response, next: NextFunction) => {
    try {
      const org = orgIdOf(req);
      if (!org) return res.status(401).json({ error: 'no workspace' });

      const corpus = await loadWorkspaceSpec<CuratedCorpus>({ workspaceOrgId: org }, 'corpus');
      if (!corpus) {
        return res.status(409).json({ error: 'No workspace corpus yet. Process a connected source first.' });
      }

      // Fail loudly before enqueue when no provider is configured — generation is
      // entirely LLM-driven (mirrors /sync).
      if (!isLlmConfigured()) {
        return res.status(409).json({ error: NO_LLM_PROVIDER_MESSAGE });
      }

      // Block while any spec conflict is open — the SAME shared derivation the repo
      // gate uses. Extracting both sides of an unresolved overlap births noise.
      const decisions = await getWorkspaceDecisions(org);
      const open = openConflicts(corpus, decisions);
      if (open.length > 0) {
        return res.status(409).json({
          error: formatOpenConflictsMessage(open),
          openConflicts: open.length,
        });
      }

      const key = workspaceGuardJobKey(org);
      let job;
      try {
        job = await jobs.jobStore.create({ org, type: KNOWLEDGE_GUARD_TASK, key });
      } catch (e) {
        if (e instanceof ActiveJobExistsError) {
          return res
            .status(409)
            .json({ error: 'Scenario generation is already in progress for this workspace.', jobId: e.existing.id });
        }
        throw e;
      }
      await jobs.enqueueGuard({ jobId: job.id, org }, key);
      return res.status(202).json({ jobId: job.id });
    } catch (e) {
      next(e);
    }
  });
}
