/**
 * THE GENERATED DATASTORE (item 68) — the pure half.
 *
 * `deriveGuardCompose` turns the connection URLs an app writes down into the
 * compose file that provides them, plus the `api.services` that runs it and the
 * `api.env` that points the app at it. It touches no disk and probes nothing, so
 * every case here is a pure input/output assertion — including the refusals, which
 * are how a repo falls back to item 67's guided message instead of getting a
 * container guard guessed at.
 *
 * The second half asserts the PROPOSER's gate: a repo with its own compose
 * datastore, or a recipe already running the generated one, is never touched.
 */

import { describe, it, expect, afterEach } from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import yaml from 'js-yaml'
import { deriveGuardCompose, GUARD_COMPOSE_FILE, proposeRecipe } from '@truecourse/guard-generator'
import type { DatastoreUrlRef } from '@truecourse/shared'

const dirs: string[] = []
afterEach(() => {
  while (dirs.length) fs.rmSync(dirs.pop()!, { recursive: true, force: true })
})

/** One harvested connection URL. */
function ref(url: string, envVar?: string, file = '/repo/src/config.ts'): DatastoreUrlRef {
  return {
    url,
    scheme: url.slice(0, url.indexOf(':')),
    ...(envVar ? { envVar } : {}),
    location: { filePath: file, startLine: 1, endLine: 1, startColumn: 0, endColumn: url.length },
  }
}

/** The compose file's parsed `services` map. */
function services(content: string): Record<string, any> {
  return (yaml.load(content) as { services: Record<string, any> }).services
}

describe('deriveGuardCompose', () => {
  it('a user-less URL pins the neutral user AND carries the explicit URL in api.env', () => {
    // The speced-api case: `postgres://localhost:5432/weather` would resolve to
    // whoever runs the app, which is a different user on every machine.
    const derived = deriveGuardCompose([ref('postgres://localhost:5432/weather', 'DATABASE_URL')])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    expect(derived.plan.env).toEqual({ DATABASE_URL: 'postgres://guard@localhost:5432/weather' })
    expect(derived.plan.services).toEqual({
      up: 'docker compose -f docker-compose.guard.yml up -d --wait',
      down: 'docker compose -f docker-compose.guard.yml down',
    })
    const db = services(derived.plan.content).postgres
    expect(db.image).toBe('postgres:16-alpine')
    expect(db.ports).toEqual(['5432:5432'])
    expect(db.environment).toEqual({
      POSTGRES_USER: 'guard',
      POSTGRES_DB: 'weather',
      // No password is invented — trust auth is the honest alternative.
      POSTGRES_HOST_AUTH_METHOD: 'trust',
    })
    expect(db.healthcheck.test).toEqual(['CMD-SHELL', 'pg_isready -U guard -d weather'])
    // The header says what it is and where it came from.
    expect(derived.plan.content).toContain('generated by `truecourse guard`')
    expect(derived.plan.content).toContain('postgres://localhost:5432/weather')
    expect(derived.plan.notes).toHaveLength(1)
    expect(derived.plan.notes[0]).toContain('DATABASE_URL=postgres://guard@localhost:5432/weather')
  })

  it('a CREDENTIALED URL is carried verbatim and needs no api.env at all', () => {
    const derived = deriveGuardCompose([ref('postgres://app:s3cret@localhost:5432/orders', 'DATABASE_URL')])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    // The app's own default already reaches what was built — nothing to override.
    expect(derived.plan.env).toEqual({})
    expect(derived.plan.notes).toEqual([])
    expect(services(derived.plan.content).postgres.environment).toEqual({
      POSTGRES_USER: 'app',
      POSTGRES_DB: 'orders',
      POSTGRES_PASSWORD: 's3cret',
    })
  })

  it('a non-default port is published as the app wrote it', () => {
    const derived = deriveGuardCompose([ref('postgres://localhost:55432/weather', 'DATABASE_URL')])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    expect(services(derived.plan.content).postgres.ports).toEqual(['55432:5432'])
    expect(derived.plan.env.DATABASE_URL).toBe('postgres://guard@localhost:55432/weather')
  })

  it('a URL with no port falls back to the engine default', () => {
    const derived = deriveGuardCompose([ref('postgres://localhost/weather', 'DATABASE_URL')])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    expect(services(derived.plan.content).postgres.ports).toEqual(['5432:5432'])
  })

  it('derives EVERY detected engine into the one file', () => {
    const derived = deriveGuardCompose([
      ref('postgres://localhost:5432/weather', 'DATABASE_URL'),
      ref('redis://localhost:6379', 'CACHE_URL'),
      ref('mongodb://localhost:27017/events', 'MONGO_URL'),
    ])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    const declared = services(derived.plan.content)
    expect(Object.keys(declared).sort()).toEqual(['mongodb', 'postgres', 'redis'])
    expect(declared.redis.image).toBe('redis:7-alpine')
    expect(declared.mongodb.environment).toEqual({ MONGO_INITDB_DATABASE: 'events' })
    // Only postgres needed an override: redis and mongo run open by default, so the
    // app's own URLs already reach them.
    expect(Object.keys(derived.plan.env)).toEqual(['DATABASE_URL'])
  })

  it('mysql with no credentials is served by root with an empty password', () => {
    const derived = deriveGuardCompose([ref('mysql://localhost:3306/shop', 'DB_URL')])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    expect(services(derived.plan.content).mysql.environment).toEqual({
      MYSQL_DATABASE: 'shop',
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes',
    })
    expect(derived.plan.env.DB_URL).toBe('mysql://root@localhost:3306/shop')
  })

  it('REFUSES a mysql user with no password rather than inventing one', () => {
    const derived = deriveGuardCompose([ref('mysql://app@localhost:3306/shop', 'DB_URL')])

    expect(derived.ok).toBe(false)
    if (derived.ok) return
    expect(derived.reason).toContain('never invents a password')
  })

  it('REFUSES an engine with no image mapping', () => {
    const derived = deriveGuardCompose([ref('rediss://localhost:6379', 'CACHE_URL')])

    expect(derived.ok).toBe(false)
    if (derived.ok) return
    expect(derived.reason).toContain('no container image is mapped for the `rediss` scheme')
  })

  it('SKIPS a remote URL — a database on another machine is not guard’s to build', () => {
    const remoteOnly = deriveGuardCompose([ref('postgres://db.prod.internal:5432/app', 'DATABASE_URL')])
    expect(remoteOnly.ok).toBe(false)
    if (remoteOnly.ok) return
    expect(remoteOnly.reason).toContain('no local datastore connection URL')

    // …and it never poisons the local one that IS derivable (a test fixture's URL,
    // the shape the speced-api bench actually has).
    const mixed = deriveGuardCompose([
      ref('postgres://localhost:5432/weather', 'DATABASE_URL'),
      ref('postgres://unused.test/weather', undefined, '/repo/tests/helpers.ts'),
    ])
    expect(mixed.ok).toBe(true)
    if (!mixed.ok) return
    expect(mixed.plan.content).not.toContain('unused.test')
  })

  it('REFUSES two local URLs of one engine when neither is the configured one', () => {
    const derived = deriveGuardCompose([
      ref('postgres://localhost:5432/a'),
      ref('postgres://localhost:5433/b'),
    ])

    expect(derived.ok).toBe(false)
    if (derived.ok) return
    expect(derived.reason).toContain('2 different local postgres connection URLs')
  })

  it('picks the CONFIGURED URL when a second local one is an unbound literal', () => {
    const derived = deriveGuardCompose([
      ref('postgres://localhost:5433/fixture', undefined, '/repo/tests/helpers.ts'),
      ref('postgres://localhost:5432/weather', 'DATABASE_URL'),
    ])

    expect(derived.ok).toBe(true)
    if (!derived.ok) return
    expect(services(derived.plan.content).postgres.environment.POSTGRES_DB).toBe('weather')
  })

  it('REFUSES when the derivation must deviate and no variable can carry it', () => {
    // A user-less URL needs the explicit form, and nothing binds a variable to it.
    const derived = deriveGuardCompose([ref('postgres://localhost:5432/weather')])

    expect(derived.ok).toBe(false)
    if (derived.ok) return
    expect(derived.reason).toContain('binds no environment variable')
  })

  it('is empty-safe', () => {
    expect(deriveGuardCompose([])).toEqual({ ok: false, reason: 'no local datastore connection URL is written in the source' })
  })
})

// ---------------------------------------------------------------------------
// The proposer's gate.
// ---------------------------------------------------------------------------

describe('proposeRecipe — when a datastore is generated', () => {
  /** A minimal JS server repo the deterministic proposer accepts. */
  function serverRepo(): string {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-guard-gen-ds-'))
    dirs.push(root)
    fs.writeFileSync(
      path.join(root, 'package.json'),
      JSON.stringify({ name: 'app', version: '1.0.0', scripts: { start: 'node server.mjs' } }),
    )
    fs.writeFileSync(path.join(root, 'server.mjs'), '')
    return root
  }

  const DB = [ref('postgres://localhost:5432/weather', 'DATABASE_URL')]

  it('proposes the compose file, its services, and the env — as a PROPOSAL, not a write', () => {
    const root = serverRepo()

    const out = proposeRecipe(root, { datastores: DB })

    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.compose?.file).toBe(GUARD_COMPOSE_FILE)
    expect(out.recipe.api?.services?.up).toContain(GUARD_COMPOSE_FILE)
    expect(out.recipe.api?.env).toEqual({ DATABASE_URL: 'postgres://guard@localhost:5432/weather' })
    expect(out.todos.some((t) => t.includes(GUARD_COMPOSE_FILE))).toBe(true)
    // Nothing reached disk: the caller writes it, verifies it, and removes it on failure.
    expect(fs.existsSync(path.join(root, GUARD_COMPOSE_FILE))).toBe(false)
  })

  it("never generates when the repo has its OWN compose datastore", () => {
    const root = serverRepo()
    fs.writeFileSync(
      path.join(root, 'docker-compose.yml'),
      'services:\n  db:\n    image: postgres:16\n',
    )

    const out = proposeRecipe(root, { datastores: DB })

    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.compose).toBeUndefined()
    // The repo's own file, run the repo's own way — no `-f` override.
    expect(out.recipe.api?.services).toEqual({ up: 'docker compose up -d --wait', down: 'docker compose down' })
    expect(out.recipe.api?.env).toBeUndefined()
  })

  it('generates nothing when no datastore URL was harvested', () => {
    const out = proposeRecipe(serverRepo(), {})

    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.compose).toBeUndefined()
    expect(out.recipe.api?.services).toBeUndefined()
  })

  it('re-proposes the same services but does NOT rewrite a compose file a recipe already runs', () => {
    const root = serverRepo()
    fs.mkdirSync(path.join(root, '.truecourse', 'scenarios'), { recursive: true })
    fs.writeFileSync(
      path.join(root, '.truecourse', 'scenarios', 'recipe.json'),
      JSON.stringify({
        build: 'true',
        api: { serve: ['node', 'server.mjs'], services: { up: `docker compose -f ${GUARD_COMPOSE_FILE} up -d --wait` } },
      }),
    )

    const out = proposeRecipe(root, { datastores: DB })

    expect(out.ok).toBe(true)
    if (!out.ok) return
    // A reviewed, committed artifact by now — a `--refresh` must not revert edits.
    expect(out.compose).toBeUndefined()
    expect(out.recipe.api?.services?.up).toContain(GUARD_COMPOSE_FILE)
    expect(out.recipe.api?.env).toEqual({ DATABASE_URL: 'postgres://guard@localhost:5432/weather' })
  })

  it('overwrites an ORPHANED guard compose file (no recipe references it)', () => {
    const root = serverRepo()
    fs.writeFileSync(path.join(root, GUARD_COMPOSE_FILE), '# stale, from a run that was refused\n')

    const out = proposeRecipe(root, { datastores: DB })

    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.compose?.content).toContain('postgres:16-alpine')
  })
})
