import * as p from "@clack/prompts";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

function buildEnvContents(config: {
  provider?: string;
  anthropicKey?: string;
  openaiKey?: string;
  langfusePublicKey?: string;
  langfuseSecretKey?: string;
}): string {
  const lines: string[] = [
    "# TrueCourse Environment Configuration",
    `# Generated by truecourse setup on ${new Date().toISOString()}`,
    "",
  ];

  if (config.provider) {
    lines.push(`LLM_PROVIDER=${config.provider}`);
  }

  if (config.anthropicKey) {
    lines.push(`ANTHROPIC_API_KEY=${config.anthropicKey}`);
  }

  if (config.openaiKey) {
    lines.push(`OPENAI_API_KEY=${config.openaiKey}`);
  }

  if (config.langfusePublicKey && config.langfuseSecretKey) {
    lines.push("");
    lines.push("# Langfuse Tracing");
    lines.push(`LANGFUSE_PUBLIC_KEY=${config.langfusePublicKey}`);
    lines.push(`LANGFUSE_SECRET_KEY=${config.langfuseSecretKey}`);
  }

  lines.push("");
  return lines.join("\n");
}

export async function runSetup(): Promise<void> {
  p.intro("Welcome to TrueCourse");

  // Select LLM provider
  const provider = await p.select({
    message: "Which LLM provider would you like to use?",
    options: [
      { value: "anthropic", label: "Anthropic (Claude)" },
      { value: "openai", label: "OpenAI (GPT)" },
      { value: "skip", label: "Skip for now" },
    ],
  });

  if (p.isCancel(provider)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  const config: {
    provider?: string;
    anthropicKey?: string;
    openaiKey?: string;
    langfusePublicKey?: string;
    langfuseSecretKey?: string;
  } = {};

  // Set LLM provider
  if (provider === "anthropic" || provider === "openai") {
    config.provider = provider;
  }

  // Collect API keys based on provider selection
  if (provider === "anthropic") {
    const anthropicKey = await p.text({
      message: "Enter your Anthropic API key:",
      placeholder: "sk-ant-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "API key is required";
        }
      },
    });

    if (p.isCancel(anthropicKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.anthropicKey = anthropicKey;
  }

  if (provider === "openai") {
    const openaiKey = await p.text({
      message: "Enter your OpenAI API key:",
      placeholder: "sk-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "API key is required";
        }
      },
    });

    if (p.isCancel(openaiKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.openaiKey = openaiKey;
  }

  // Langfuse tracing
  const useLangfuse = await p.confirm({
    message: "Would you like to enable Langfuse tracing?",
    initialValue: false,
  });

  if (p.isCancel(useLangfuse)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  if (useLangfuse) {
    const langfusePublicKey = await p.text({
      message: "Enter your Langfuse public key:",
      placeholder: "pk-lf-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "Public key is required";
        }
      },
    });

    if (p.isCancel(langfusePublicKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    const langfuseSecretKey = await p.text({
      message: "Enter your Langfuse secret key:",
      placeholder: "sk-lf-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "Secret key is required";
        }
      },
    });

    if (p.isCancel(langfuseSecretKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.langfusePublicKey = langfusePublicKey;
    config.langfuseSecretKey = langfuseSecretKey;
  }

  // Write to ~/.truecourse/.env
  const configDir = path.join(os.homedir(), ".truecourse");
  fs.mkdirSync(configDir, { recursive: true });
  const envPath = path.join(configDir, ".env");
  fs.writeFileSync(envPath, buildEnvContents(config), "utf-8");
  p.log.success(`Configuration saved to ${envPath}`);

  p.log.info("Embedded PostgreSQL will start automatically when the server runs.");
  p.log.info("Database migrations are applied on server startup.");

  p.outro("Setup complete! Run `npx truecourse` to start.");
}
