import * as p from "@clack/prompts";
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const DEFAULT_MODELS: Record<string, string> = {
  anthropic: "claude-sonnet-4-20250514",
  openai: "gpt-5.3-codex",
};

function buildEnvContents(config: {
  provider?: string;
  model?: string;
  anthropicKey?: string;
  openaiKey?: string;
  langfusePublicKey?: string;
  langfuseSecretKey?: string;
}): string {
  const lines: string[] = [
    "# TrueCourse Environment Configuration",
    `# Generated by truecourse setup on ${new Date().toISOString()}`,
    "",
  ];

  if (config.provider) {
    lines.push(`LLM_PROVIDER=${config.provider}`);
  }

  if (config.model) {
    lines.push(`LLM_MODEL=${config.model}`);
  }

  if (config.anthropicKey) {
    lines.push(`ANTHROPIC_API_KEY=${config.anthropicKey}`);
  }

  if (config.openaiKey) {
    lines.push(`OPENAI_API_KEY=${config.openaiKey}`);
  }

  if (config.langfusePublicKey && config.langfuseSecretKey) {
    lines.push("");
    lines.push("# Langfuse Tracing");
    lines.push(`LANGFUSE_PUBLIC_KEY=${config.langfusePublicKey}`);
    lines.push(`LANGFUSE_SECRET_KEY=${config.langfuseSecretKey}`);
  }

  lines.push("");
  return lines.join("\n");
}

export async function runSetup(): Promise<void> {
  p.intro("Welcome to TrueCourse");

  // Select LLM provider
  const provider = await p.select({
    message: "Which LLM provider would you like to use?",
    options: [
      { value: "claude-code", label: "Claude Code CLI — no API key needed (Recommended)" },
      { value: "anthropic", label: "Anthropic (Claude API)" },
      { value: "openai", label: "OpenAI (GPT API)" },
      { value: "skip", label: "Skip for now" },
    ],
  });

  if (p.isCancel(provider)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  const config: {
    provider?: string;
    model?: string;
    anthropicKey?: string;
    openaiKey?: string;
    langfusePublicKey?: string;
    langfuseSecretKey?: string;
  } = {};

  // Set LLM provider
  if (provider === "anthropic" || provider === "openai" || provider === "claude-code") {
    config.provider = provider;
  }

  // Claude Code CLI — validate binary exists, no API key needed
  if (provider === "claude-code") {
    try {
      execSync("which claude", { stdio: "ignore" });
    } catch {
      p.log.error("Claude Code CLI not found on PATH. Install it first: https://docs.anthropic.com/en/docs/claude-code");
      process.exit(1);
    }
    p.log.success("Claude Code CLI detected.");
  }

  // Collect API keys based on provider selection
  if (provider === "anthropic") {
    const anthropicKey = await p.text({
      message: "Enter your Anthropic API key:",
      placeholder: "sk-ant-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "API key is required";
        }
      },
    });

    if (p.isCancel(anthropicKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.anthropicKey = anthropicKey;
  }

  if (provider === "openai") {
    const openaiKey = await p.text({
      message: "Enter your OpenAI API key:",
      placeholder: "sk-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "API key is required";
        }
      },
    });

    if (p.isCancel(openaiKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.openaiKey = openaiKey;
  }

  // Select LLM model (not needed for claude-code — uses its own model selection)
  if (provider === "anthropic" || provider === "openai") {
    const defaultModel = DEFAULT_MODELS[provider];
    const model = await p.text({
      message: `Enter the model to use (default: ${defaultModel}):`,
      placeholder: defaultModel,
    });

    if (p.isCancel(model)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.model = model?.trim() || defaultModel;
  }

  // Langfuse tracing (not applicable for claude-code)
  const useLangfuse = provider !== "claude-code" && await p.confirm({
    message: "Would you like to enable Langfuse tracing?",
    initialValue: false,
  });

  if (p.isCancel(useLangfuse)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  if (useLangfuse) {
    const langfusePublicKey = await p.text({
      message: "Enter your Langfuse public key:",
      placeholder: "pk-lf-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "Public key is required";
        }
      },
    });

    if (p.isCancel(langfusePublicKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    const langfuseSecretKey = await p.text({
      message: "Enter your Langfuse secret key:",
      placeholder: "sk-lf-...",
      validate(value) {
        if (!value || value.trim().length === 0) {
          return "Secret key is required";
        }
      },
    });

    if (p.isCancel(langfuseSecretKey)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }

    config.langfusePublicKey = langfusePublicKey;
    config.langfuseSecretKey = langfuseSecretKey;
  }

  // Write to ~/.truecourse/.env
  const configDir = path.join(os.homedir(), ".truecourse");
  fs.mkdirSync(configDir, { recursive: true });
  const envPath = path.join(configDir, ".env");
  fs.writeFileSync(envPath, buildEnvContents(config), "utf-8");
  p.log.success(`Configuration saved to ${envPath}`);

  // Run mode selection
  const runMode = await p.select({
    message: "How would you like to run TrueCourse?",
    options: [
      { value: "service" as const, label: "Background service (Recommended)" },
      { value: "console" as const, label: "Console (keep terminal open)" },
    ],
  });

  if (p.isCancel(runMode)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  // Rule category selection — use saved config if available
  const { readConfig: readExistingConfig } = await import("./helpers.js");
  const existingConfig = readExistingConfig();
  const defaultCategories = ["security", "bugs", "architecture", "performance", "reliability", "code-quality", "database"];
  const savedCategories = existingConfig.enabledCategories?.length ? existingConfig.enabledCategories : defaultCategories;

  const categories = await p.multiselect({
    message: "Which rule categories would you like to enable?",
    options: [
      { value: "security" as const, label: "Security (secrets, injection, crypto, auth)", hint: "recommended" },
      { value: "bugs" as const, label: "Bugs (runtime errors, null derefs, type issues)", hint: "recommended" },
      { value: "architecture" as const, label: "Architecture (service boundaries, layers, coupling)", hint: "recommended" },
      { value: "performance" as const, label: "Performance (N+1 queries, memory leaks, inefficient patterns)", hint: "recommended" },
      { value: "reliability" as const, label: "Reliability (error handling, timeouts, retries)", hint: "recommended" },
      { value: "code-quality" as const, label: "Code Quality (complexity, dead code, smells)", hint: "recommended" },
      { value: "database" as const, label: "Database (schema, indexes, constraints)", hint: "recommended" },
      { value: "style" as const, label: "Style (formatting, naming conventions, docstrings)" },
    ],
    initialValues: savedCategories,
    required: true,
  });

  if (p.isCancel(categories)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  // LLM rules toggle — use saved config if available
  const enableLlm = await p.confirm({
    message: "Enable LLM-powered rules? (costs tokens, slower but deeper analysis)",
    initialValue: existingConfig.enableLlmRules ?? true,
  });

  if (p.isCancel(enableLlm)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  const { writeConfig } = await import("./helpers.js");
  writeConfig({ runMode, enabledCategories: categories as string[], enableLlmRules: enableLlm });

  if (runMode === "service") {
    p.log.info("Background service selected. Run `truecourse start` to install and start the service.");
  }

  p.log.info("Embedded PostgreSQL will start automatically when the server runs.");
  p.log.info("Database migrations are applied on server startup.");

  p.outro("Setup complete!");
}
