#!/usr/bin/env python3
"""Assemble targets/FILING-TABLE.md from FINDINGS-INDEX.json, reverify/<repo>/<ID>.json,
live/<repo>/summary.json and the front matter of issues/<target>/<ID>-*.md.

Usage: python3 tools/build-table.py  (run from docs/findings/targets/)
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "targets")
INDEX = json.load(open(os.path.join(ROOT, "FINDINGS-INDEX.json")))

REPO_LABEL = {"strapi": "Strapi", "documenso": "Documenso", "caldiy": "Cal.diy"}
UPSTREAM = {"strapi": "strapi/strapi", "documenso": "documenso/documenso", "caldiy": "calcom/cal.diy"}


def load(path):
    try:
        return json.load(open(path))
    except FileNotFoundError:
        return None


def front_matter(path):
    text = open(path).read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    return fm


def drafts_for(fid):
    out = []
    for p in glob.glob(os.path.join(ROOT, "*", "issues", "*", f"{fid}-*.md")):
        fm = front_matter(p)
        out.append((os.path.relpath(p, ROOT), fm))
    return out


def cell(s):
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


rows = []
for repo in ("strapi", "documenso", "caldiy"):
    live = load(os.path.join(ROOT, repo, "live", "summary.json")) or {}
    live_findings = live.get("findings", {})
    build = live.get("build", {})
    for f in INDEX[repo]["findings"]:
        fid = f["id"]
        rv = load(os.path.join(ROOT, repo, "reverify", f"{fid}.json")) or {}
        src = rv.get("source", {}) or {}
        status = src.get("status", "?")
        fix = src.get("fix") or {}
        still = {
            "unchanged": "yes (source unchanged)",
            "changed-bug-remains": "yes (source changed, bug remains)",
            "fixed": f"no: fixed by {fix.get('pr') or fix.get('sha','?')} ({fix.get('date','?')}, release: {fix.get('inRelease') or 'none'})",
            "unclear": "unclear",
        }.get(status, status)
        docs = rv.get("docs") or {}
        if f.get("kind") == "doc" and docs:
            still += "; doc text " + ("still present" if docs.get("stillPresent") else "changed")
        lv = live_findings.get(fid)
        blocked = os.path.exists(os.path.join(ROOT, repo, "live", "STATUS.md")) and not live
        live_cell = "attempted, blocked (disk)" if blocked else "not re-run"
        if lv:
            live_cell = f"{lv.get('verdict','?')}"
            if build.get("sha"):
                live_cell += f" on {build.get('tag') or build['sha'][:10]}"
        new_items = (rv.get("tracker", {}) or {}).get("newItems", []) or []
        new_cell = "none" if not new_items else "; ".join(
            f"#{i.get('number')} ({i.get('state')}, {i.get('relation')})" for i in new_items
        )
        changed_cited = [c for c in (rv.get("tracker", {}) or {}).get("citedItems", []) or [] if c.get("changedSinceReview")]
        if changed_cited:
            if new_cell == "none":
                new_cell = ""
            new_cell += (" | " if new_cell else "") + "cited changed: " + "; ".join(f"{c.get('ref')} -> {c.get('stateToday')}" for c in changed_cited)
        drafts = drafts_for(fid)
        route = f.get("route") or rv.get("routeSuggestion") or "?"
        if drafts:
            route = drafts[0][1].get("route", route)
        draft_cell = ", ".join(p for p, _ in drafts) if drafts else "none"
        conf = rv.get("confidence") or f.get("confidence") or "high"
        notes = rv.get("notes") or ""
        live_note = lv.get("note") if lv else ""
        reeval = rv.get("reevaluation") or ""
        rows.append({
            "fid": fid, "repo": REPO_LABEL[repo], "title": f["title"], "still": still,
            "live_cell": live_cell, "new_cell": new_cell, "route": route, "conf": conf,
            "draft_cell": draft_cell, "notes": notes, "live_note": live_note, "reeval": reeval,
        })

lines = [
    "# Filing table (re-verified 2026-08-19)",
    "",
    "Generated by `tools/build-table.py` from FINDINGS-INDEX.json, reverify/, live/ and the issue drafts' front matter. Edit the sources, not this file.",
    "",
    "Columns: still present on the default branch today (from the source re-check, with the fix commit when fixed); live re-run verdict on today's build; new upstream reports since 2026-08-15 (and cited items whose state changed); route; confidence; draft file. Per-finding filer notes and the live-run one-liners are in the section below the table.",
    "",
    "| id | repo | title | still present today | live re-run | new upstream since 2026-08-15 | route | conf | draft |",
    "|---|---|---|---|---|---|---|---|---|",
]
for r in rows:
    lines.append("| " + " | ".join(cell(str(r[k])) for k in ("fid", "repo", "title", "still", "live_cell", "new_cell", "route", "conf", "draft_cell")) + " |")

lines += ["", "## Per-finding notes", ""]
for r in rows:
    parts = []
    if r["live_note"]:
        parts.append("**Live re-run:** " + r["live_note"].strip())
    if r["notes"]:
        parts.append("**Filer notes:** " + r["notes"].strip())
    if r["reeval"]:
        parts.append("**Re-evaluation:** " + r["reeval"].strip())
    body = " ".join(parts) if parts else "(no additional notes)"
    lines.append(f"### {r['fid']} ({r['repo']}) - {r['title']}")
    lines.append("")
    lines.append(body)
    lines.append("")

out = os.path.join(ROOT, "FILING-TABLE.md")
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out} with {len(rows)} rows")
