import type { AnalysisRule } from '@truecourse/shared'

export const CODE_QUALITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'code-quality/deterministic/console-log',
    category: 'code',
    domain: 'code-quality',
    name: 'Debug logging in production',
    description: 'Debug logging calls (console.log, print) in production code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-explicit-any',
    category: 'code',
    domain: 'code-quality',
    name: 'Untyped escape hatch',
    description: 'Using any/Any types bypasses type checking safety.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/todo-fixme',
    category: 'code',
    domain: 'code-quality',
    name: 'TODO/FIXME comment',
    description: 'TODO, FIXME, or HACK comments left in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/star-import',
    category: 'code',
    domain: 'code-quality',
    name: 'Wildcard import',
    description: 'Wildcard imports (import *, from x import *) pollute namespace and hide dependencies.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/global-statement',
    category: 'code',
    domain: 'code-quality',
    name: 'Global state mutation',
    description: 'Modifying global/module-level state from inside functions (Python: global, JS: var).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
]
