import type { AnalysisRule } from '@truecourse/shared'

export const CODE_QUALITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'code-quality/deterministic/console-log',
    category: 'code',
    domain: 'code-quality',
    name: 'Debug logging in production',
    description: 'Debug logging calls (console.log, print) in production code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-explicit-any',
    category: 'code',
    domain: 'code-quality',
    name: 'Untyped escape hatch',
    description: 'Using any/Any types bypasses type checking safety.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/todo-fixme',
    category: 'code',
    domain: 'code-quality',
    name: 'TODO/FIXME comment',
    description: 'TODO, FIXME, or HACK comments left in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/star-import',
    category: 'code',
    domain: 'code-quality',
    name: 'Wildcard import',
    description: 'Wildcard imports (import *, from x import *) pollute namespace and hide dependencies.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/global-statement',
    category: 'code',
    domain: 'code-quality',
    name: 'Global state mutation',
    description: 'Modifying global/module-level state from inside functions (Python: global, JS: var).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/nested-ternary',
    category: 'code',
    domain: 'code-quality',
    name: 'Nested ternary',
    description: 'Ternary expression nested inside another ternary — hard to read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/nested-template-literal',
    category: 'code',
    domain: 'code-quality',
    name: 'Nested template literal',
    description: 'Template literal nested inside another template literal — hard to read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-return-statements',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many return statements',
    description: 'Function with more than 5 return statements — consider refactoring.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/collapsible-if',
    category: 'code',
    domain: 'code-quality',
    name: 'Collapsible if',
    description: 'Nested if statements that can be collapsed into a single condition with &&.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/redundant-boolean',
    category: 'code',
    domain: 'code-quality',
    name: 'Redundant boolean return',
    description: 'if (x) return true; else return false; — can be simplified to return x.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unnecessary-else-after-return',
    category: 'code',
    domain: 'code-quality',
    name: 'Unnecessary else after return',
    description: 'else block after a return statement is unnecessary — the code can be flattened.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-empty-function',
    category: 'code',
    domain: 'code-quality',
    name: 'Empty function',
    description: 'Function body is empty — may indicate incomplete implementation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-useless-catch',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless catch',
    description: 'catch block that only re-throws the caught error without adding context.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-template-literal',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer template literal',
    description: 'String concatenation with + where a template literal would be cleaner.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-var-declaration',
    category: 'code',
    domain: 'code-quality',
    name: 'No var declaration',
    description: 'Using var instead of let/const — var is function-scoped and error-prone.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/cognitive-complexity',
    category: 'code',
    domain: 'code-quality',
    name: 'High cognitive complexity',
    description: 'Function with cognitive complexity > 15 — hard to understand.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/cyclomatic-complexity',
    category: 'code',
    domain: 'code-quality',
    name: 'High cyclomatic complexity',
    description: 'Function with cyclomatic complexity > 10 — too many decision points.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-lines',
    category: 'code',
    domain: 'code-quality',
    name: 'Function too long',
    description: 'Function with more than 50 lines — consider splitting into smaller functions.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-branches',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many branches',
    description: 'Function with more than 10 branches (if/else/switch cases) — hard to follow.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/nested-switch',
    category: 'code',
    domain: 'code-quality',
    name: 'Nested switch',
    description: 'Switch statement inside another switch — use helper functions or lookup tables.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/deeply-nested-functions',
    category: 'code',
    domain: 'code-quality',
    name: 'Deeply nested function',
    description: 'Function defined 3+ levels deep inside other functions — extract to module scope.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/duplicate-string',
    category: 'code',
    domain: 'code-quality',
    name: 'Duplicate string literal',
    description: 'Same string literal used 3+ times in a file — extract to a constant.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unused-expression',
    category: 'code',
    domain: 'code-quality',
    name: 'Unused expression',
    description: 'Expression statement with no side effect (e.g., x + 1;).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/redundant-jump',
    category: 'code',
    domain: 'code-quality',
    name: 'Redundant jump',
    description: 'return at end of void function or continue at end of loop body is unnecessary.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-script-url',
    category: 'code',
    domain: 'code-quality',
    name: 'Script URL',
    description: 'Using javascript: URLs is a form of eval and a security/quality concern.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-throw-literal',
    category: 'code',
    domain: 'code-quality',
    name: 'Throw literal',
    description: 'Throwing a string literal instead of an Error object — loses stack trace.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-label-var',
    category: 'code',
    domain: 'code-quality',
    name: 'Label shadows variable',
    description: 'Label with same name as a variable in scope — confusing.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-new-wrappers',
    category: 'code',
    domain: 'code-quality',
    name: 'Primitive wrapper object',
    description: 'new String(), new Number(), new Boolean() create wrapper objects — use literals.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-proto',
    category: 'code',
    domain: 'code-quality',
    name: '__proto__ usage',
    description: 'Using __proto__ is deprecated — use Object.getPrototypeOf() or Object.setPrototypeOf().',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-void',
    category: 'code',
    domain: 'code-quality',
    name: 'Void expression',
    description: 'Using void expression — confusing and unnecessary in modern JS.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-const',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer const',
    description: 'let variable that is never reassigned — should be const.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-debugger',
    category: 'code',
    domain: 'code-quality',
    name: 'Debugger statement',
    description: 'debugger statement or breakpoint() left in code.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-alert',
    category: 'code',
    domain: 'code-quality',
    name: 'Alert/confirm/prompt',
    description: 'alert(), confirm(), prompt() should not be used in production code.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/require-await',
    category: 'code',
    domain: 'code-quality',
    name: 'Async without await',
    description: 'async function that never uses await — remove async or add await.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-return-await',
    category: 'code',
    domain: 'code-quality',
    name: 'Redundant return await',
    description: 'return await is redundant in async functions — the promise is already unwrapped.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/expression-complexity',
    category: 'code',
    domain: 'code-quality',
    name: 'Complex expression',
    description: 'Expression with more than 5 binary/logical operators — hard to read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-switch-cases',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many switch cases',
    description: 'Switch statement with more than 10 cases — consider using a lookup table or polymorphism.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-union-members',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many union members',
    description: 'TypeScript union type with more than 5 members — consider an enum or type alias.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-breaks',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many break statements',
    description: 'Function with more than 5 break statements — may indicate overly complex control flow.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/identical-functions',
    category: 'code',
    domain: 'code-quality',
    name: 'Identical function bodies',
    description: 'Two functions in the same file have identical bodies — extract to a shared function.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unused-variable',
    category: 'code',
    domain: 'code-quality',
    name: 'Unused variable',
    description: 'Variable declared but never read — remove or use it.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unused-private-member',
    category: 'code',
    domain: 'code-quality',
    name: 'Unused private member',
    description: 'Private class member is never accessed outside its declaration.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/dead-store',
    category: 'code',
    domain: 'code-quality',
    name: 'Dead store',
    description: 'Variable is assigned a value that is overwritten before it is read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unused-collection',
    category: 'code',
    domain: 'code-quality',
    name: 'Unused collection',
    description: 'Array/Set/Map is created but never read — remove or use it.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/redundant-assignment',
    category: 'code',
    domain: 'code-quality',
    name: 'Redundant assignment',
    description: 'Variable assigned to itself or the same value is assigned twice in a row.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-lonely-if',
    category: 'code',
    domain: 'code-quality',
    name: 'Lonely if in else',
    description: 'if statement is the only statement in an else block — use else if instead.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/useless-constructor',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless constructor',
    description: 'Constructor only calls super() with the same arguments — it can be removed.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/useless-escape',
    category: 'code',
    domain: 'code-quality',
    name: 'Unnecessary escape',
    description: 'Unnecessary escape character in a string literal.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/useless-rename',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless destructuring rename',
    description: 'Destructuring renames a variable to the same name: `{ x: x }` should be `{ x }`.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/useless-computed-key',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless computed property key',
    description: 'Computed property key uses a string literal: `{ ["key"]: val }` should be `{ key: val }`.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/useless-concat',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless string concatenation',
    description: 'Concatenating two string literals: `"a" + "b"` should be `"ab"`.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/strict-equality',
    category: 'code',
    domain: 'code-quality',
    name: 'Loose equality',
    description: 'Using == instead of === performs type coercion which can lead to subtle bugs.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/commented-out-code',
    category: 'code',
    domain: 'code-quality',
    name: 'Commented-out code',
    description: 'Block of commented-out code found — remove it or track it in version control.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/inverted-boolean',
    category: 'code',
    domain: 'code-quality',
    name: 'Inverted boolean negation',
    description: '`!!x` or `!(!x)` — double negation is unnecessary.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-single-boolean-return',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer single boolean return',
    description: 'Function returns true/false in multiple branches — use a single boolean expression.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-immediate-return',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer immediate return',
    description: 'Variable assigned and immediately returned — return the expression directly.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-while',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer while loop',
    description: '`for(;condition;)` loop with no init or update should be `while(condition)`.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-object-spread',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer object spread',
    description: '`Object.assign({}, obj)` should be `{ ...obj }` for clarity.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-optional-chain',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer optional chaining',
    description: '`a && a.b` can be simplified to `a?.b` with optional chaining.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-nullish-coalescing',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer nullish coalescing',
    description: '`a !== null && a !== undefined ? a : b` can be simplified to `a ?? b`.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
