import type { AnalysisRule } from '@truecourse/shared'

export const CODE_QUALITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'code-quality/deterministic/console-log',
    category: 'code',
    domain: 'code-quality',
    name: 'Debug logging in production',
    description: 'Debug logging calls (console.log, print) in production code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-explicit-any',
    category: 'code',
    domain: 'code-quality',
    name: 'Untyped escape hatch',
    description: 'Using any/Any types bypasses type checking safety.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/todo-fixme',
    category: 'code',
    domain: 'code-quality',
    name: 'TODO/FIXME comment',
    description: 'TODO, FIXME, or HACK comments left in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/star-import',
    category: 'code',
    domain: 'code-quality',
    name: 'Wildcard import',
    description: 'Wildcard imports (import *, from x import *) pollute namespace and hide dependencies.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/global-statement',
    category: 'code',
    domain: 'code-quality',
    name: 'Global state mutation',
    description: 'Modifying global/module-level state from inside functions (Python: global, JS: var).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/nested-ternary',
    category: 'code',
    domain: 'code-quality',
    name: 'Nested ternary',
    description: 'Ternary expression nested inside another ternary — hard to read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/nested-template-literal',
    category: 'code',
    domain: 'code-quality',
    name: 'Nested template literal',
    description: 'Template literal nested inside another template literal — hard to read.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/too-many-return-statements',
    category: 'code',
    domain: 'code-quality',
    name: 'Too many return statements',
    description: 'Function with more than 5 return statements — consider refactoring.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/collapsible-if',
    category: 'code',
    domain: 'code-quality',
    name: 'Collapsible if',
    description: 'Nested if statements that can be collapsed into a single condition with &&.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/redundant-boolean',
    category: 'code',
    domain: 'code-quality',
    name: 'Redundant boolean return',
    description: 'if (x) return true; else return false; — can be simplified to return x.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/unnecessary-else-after-return',
    category: 'code',
    domain: 'code-quality',
    name: 'Unnecessary else after return',
    description: 'else block after a return statement is unnecessary — the code can be flattened.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-empty-function',
    category: 'code',
    domain: 'code-quality',
    name: 'Empty function',
    description: 'Function body is empty — may indicate incomplete implementation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-useless-catch',
    category: 'code',
    domain: 'code-quality',
    name: 'Useless catch',
    description: 'catch block that only re-throws the caught error without adding context.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/prefer-template-literal',
    category: 'code',
    domain: 'code-quality',
    name: 'Prefer template literal',
    description: 'String concatenation with + where a template literal would be cleaner.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code-quality/deterministic/no-var-declaration',
    category: 'code',
    domain: 'code-quality',
    name: 'No var declaration',
    description: 'Using var instead of let/const — var is function-scoped and error-prone.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
]
