import type { AnalysisRule } from '@truecourse/shared'

export const RELIABILITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'reliability/deterministic/catch-without-error-type',
    category: 'code',
    domain: 'reliability',
    name: 'Catch without error type discrimination',
    description: 'Catch block does not check or narrow the error type before handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/promise-all-no-error-handling',
    category: 'code',
    domain: 'reliability',
    name: 'Promise.all without error handling',
    description: 'Promise.all() without .catch() or surrounding try/catch.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-finally-cleanup',
    category: 'code',
    domain: 'reliability',
    name: 'Missing finally cleanup for resource',
    description: 'Resource opened in try block without finally or using for cleanup.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unsafe-json-parse',
    category: 'code',
    domain: 'reliability',
    name: 'Unsafe JSON.parse',
    description: 'JSON.parse() or json.loads() without try/catch for error handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/http-call-no-timeout',
    category: 'code',
    domain: 'reliability',
    name: 'HTTP call without timeout',
    description: 'fetch() or HTTP client call without a timeout option configured.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-error-event-handler',
    category: 'code',
    domain: 'reliability',
    name: 'Missing error event handler',
    description: 'EventEmitter or Stream created without an error event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/process-exit-in-library',
    category: 'code',
    domain: 'reliability',
    name: 'process.exit() in non-entry-point code',
    description: 'process.exit() or sys.exit() in code that is not the main entry point.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unchecked-array-access',
    category: 'code',
    domain: 'reliability',
    name: 'Unchecked array index access',
    description: 'Array accessed by dynamic index without a bounds check.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-null-check-after-find',
    category: 'code',
    domain: 'reliability',
    name: 'Missing null check after .find()',
    description: '.find() result used directly without checking for undefined.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/floating-promise',
    category: 'code',
    domain: 'reliability',
    name: 'Floating promise',
    description: 'Promise returned but not awaited or .catch()-ed.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/express-async-no-wrapper',
    category: 'code',
    domain: 'reliability',
    name: 'Express async handler without error wrapper',
    description: 'Async function passed to Express route without error-catching wrapper.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-next-on-error',
    category: 'code',
    domain: 'reliability',
    name: 'Missing next(error) in middleware catch',
    description: 'Express middleware catch block does not call next(error).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/uncaught-exception-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No uncaughtException handler',
    description: 'Node process without an uncaughtException event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/empty-reject',
    category: 'code',
    domain: 'reliability',
    name: 'Empty Promise.reject()',
    description: 'Promise.reject() called without an error argument.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unhandled-rejection-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No unhandledRejection handler',
    description: 'Node process without an unhandledRejection event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },

  // --- New rules ---
  {
    key: 'reliability/deterministic/unchecked-optional-chain-depth',
    category: 'code',
    domain: 'reliability',
    name: 'Deep optional chaining',
    description: 'Optional chaining deeper than 3 levels (a?.b?.c?.d?.e) suggests missing data validation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/catch-rethrow-no-context',
    category: 'code',
    domain: 'reliability',
    name: 'Catch rethrows without context',
    description: 'Catch block rethrows the error without adding context or wrapping.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/console-error-no-context',
    category: 'code',
    domain: 'reliability',
    name: 'console.error without context',
    description: 'console.error(err) called with only the error object, no additional context string.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/shallow-copy-environ',
    category: 'code',
    domain: 'reliability',
    name: 'os.environ used directly',
    description: 'os.environ used directly instead of os.environ.copy(), risking mutation of the process environment.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/invalid-envvar-default',
    category: 'code',
    domain: 'reliability',
    name: 'os.getenv with wrong default type',
    description: 'os.getenv() with a non-string default value (e.g., 0, False).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/flask-error-handler-missing-status',
    category: 'code',
    domain: 'reliability',
    name: 'Flask error handler missing status code',
    description: 'Flask error handler does not return an explicit status code.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/async-with-for-resources',
    category: 'code',
    domain: 'reliability',
    name: 'Missing async context manager',
    description: 'Async resource not using async with for proper cleanup.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/django-decorator-order',
    category: 'code',
    domain: 'reliability',
    name: 'Wrong Django decorator order',
    description: 'Django decorators applied in wrong order (e.g., @login_required must be below @require_http_methods).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/shebang-error',
    category: 'code',
    domain: 'reliability',
    name: 'Missing or malformed shebang',
    description: 'Executable Python script without a proper shebang line.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
