import type { AnalysisRule } from '@truecourse/shared'

export const RELIABILITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'reliability/deterministic/catch-without-error-type',
    category: 'code',
    domain: 'reliability',
    name: 'Catch without error type discrimination',
    description: 'Catch block does not check or narrow the error type before handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/promise-all-no-error-handling',
    category: 'code',
    domain: 'reliability',
    name: 'Promise.all without error handling',
    description: 'Promise.all() without .catch() or surrounding try/catch.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-finally-cleanup',
    category: 'code',
    domain: 'reliability',
    name: 'Missing finally cleanup for resource',
    description: 'Resource opened in try block without finally or using for cleanup.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unsafe-json-parse',
    category: 'code',
    domain: 'reliability',
    name: 'Unsafe JSON.parse',
    description: 'JSON.parse() or json.loads() without try/catch for error handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/http-call-no-timeout',
    category: 'code',
    domain: 'reliability',
    name: 'HTTP call without timeout',
    description: 'fetch() or HTTP client call without a timeout option configured.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-error-event-handler',
    category: 'code',
    domain: 'reliability',
    name: 'Missing error event handler',
    description: 'EventEmitter or Stream created without an error event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/process-exit-in-library',
    category: 'code',
    domain: 'reliability',
    name: 'process.exit() in non-entry-point code',
    description: 'process.exit() or sys.exit() in code that is not the main entry point.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unchecked-array-access',
    category: 'code',
    domain: 'reliability',
    name: 'Unchecked array index access',
    description: 'Array accessed by dynamic index without a bounds check.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-null-check-after-find',
    category: 'code',
    domain: 'reliability',
    name: 'Missing null check after .find()',
    description: '.find() result used directly without checking for undefined.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/floating-promise',
    category: 'code',
    domain: 'reliability',
    name: 'Floating promise',
    description: 'Promise returned but not awaited or .catch()-ed.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/express-async-no-wrapper',
    category: 'code',
    domain: 'reliability',
    name: 'Express async handler without error wrapper',
    description: 'Async function passed to Express route without error-catching wrapper.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-next-on-error',
    category: 'code',
    domain: 'reliability',
    name: 'Missing next(error) in middleware catch',
    description: 'Express middleware catch block does not call next(error).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/uncaught-exception-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No uncaughtException handler',
    description: 'Node process without an uncaughtException event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/empty-reject',
    category: 'code',
    domain: 'reliability',
    name: 'Empty Promise.reject()',
    description: 'Promise.reject() called without an error argument.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unhandled-rejection-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No unhandledRejection handler',
    description: 'Node process without an unhandledRejection event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
