import type { AnalysisRule } from '@truecourse/shared'

export const RELIABILITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'reliability/deterministic/catch-without-error-type',
    category: 'code',
    domain: 'reliability',
    name: 'Catch without error type discrimination',
    description: 'Catch block does not check or narrow the error type before handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/promise-all-no-error-handling',
    category: 'code',
    domain: 'reliability',
    name: 'Promise.all without error handling',
    description: 'Promise.all() without .catch() or surrounding try/catch.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-finally-cleanup',
    category: 'code',
    domain: 'reliability',
    name: 'Missing finally cleanup for resource',
    description: 'Resource opened in try block without finally or using for cleanup.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unsafe-json-parse',
    category: 'code',
    domain: 'reliability',
    name: 'Unsafe JSON.parse',
    description: 'JSON.parse() or json.loads() without try/catch for error handling.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/http-call-no-timeout',
    category: 'code',
    domain: 'reliability',
    name: 'HTTP call without timeout',
    description: 'fetch() or HTTP client call without a timeout option configured.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-error-event-handler',
    category: 'code',
    domain: 'reliability',
    name: 'Missing error event handler',
    description: 'EventEmitter or Stream created without an error event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/process-exit-in-library',
    category: 'code',
    domain: 'reliability',
    name: 'process.exit() in non-entry-point code',
    description: 'process.exit() or sys.exit() in code that is not the main entry point.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unchecked-array-access',
    category: 'code',
    domain: 'reliability',
    name: 'Unchecked array index access',
    description: 'Array accessed by dynamic index without a bounds check.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-null-check-after-find',
    category: 'code',
    domain: 'reliability',
    name: 'Missing null check after .find()',
    description: '.find() result used directly without checking for undefined.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/floating-promise',
    category: 'code',
    domain: 'reliability',
    name: 'Floating promise',
    description: 'Promise returned but not awaited or .catch()-ed.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/express-async-no-wrapper',
    category: 'code',
    domain: 'reliability',
    name: 'Express async handler without error wrapper',
    description: 'Async function passed to Express route without error-catching wrapper.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/missing-next-on-error',
    category: 'code',
    domain: 'reliability',
    name: 'Missing next(error) in middleware catch',
    description: 'Express middleware catch block does not call next(error).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/uncaught-exception-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No uncaughtException handler',
    description: 'Node process without an uncaughtException event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/empty-reject',
    category: 'code',
    domain: 'reliability',
    name: 'Empty Promise.reject()',
    description: 'Promise.reject() called without an error argument.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/unhandled-rejection-no-handler',
    category: 'code',
    domain: 'reliability',
    name: 'No unhandledRejection handler',
    description: 'Node process without an unhandledRejection event handler.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },

  // --- New rules ---
  {
    key: 'reliability/deterministic/unchecked-optional-chain-depth',
    category: 'code',
    domain: 'reliability',
    name: 'Deep optional chaining',
    description: 'Optional chaining deeper than 3 levels (a?.b?.c?.d?.e) suggests missing data validation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/catch-rethrow-no-context',
    category: 'code',
    domain: 'reliability',
    name: 'Catch rethrows without context',
    description: 'Catch block rethrows the error without adding context or wrapping.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/console-error-no-context',
    category: 'code',
    domain: 'reliability',
    name: 'console.error without context',
    description: 'console.error(err) called with only the error object, no additional context string.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/shallow-copy-environ',
    category: 'code',
    domain: 'reliability',
    name: 'os.environ used directly',
    description: 'os.environ used directly instead of os.environ.copy(), risking mutation of the process environment.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/invalid-envvar-default',
    category: 'code',
    domain: 'reliability',
    name: 'os.getenv with wrong default type',
    description: 'os.getenv() with a non-string default value (e.g., 0, False).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/flask-error-handler-missing-status',
    category: 'code',
    domain: 'reliability',
    name: 'Flask error handler missing status code',
    description: 'Flask error handler does not return an explicit status code.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/async-with-for-resources',
    category: 'code',
    domain: 'reliability',
    name: 'Missing async context manager',
    description: 'Async resource not using async with for proper cleanup.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/django-decorator-order',
    category: 'code',
    domain: 'reliability',
    name: 'Wrong Django decorator order',
    description: 'Django decorators applied in wrong order (e.g., @login_required must be below @require_http_methods).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/shebang-error',
    category: 'code',
    domain: 'reliability',
    name: 'Missing or malformed shebang',
    description: 'Executable Python script without a proper shebang line.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/cancellationtoken-not-forwarded',
    category: 'code',
    domain: 'reliability',
    name: 'CancellationToken not forwarded',
    description:
      'A method with a CancellationToken in scope calls a method that exposes a token-accepting overload but forwards no token, silently dropping cancellation.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'reliability/deterministic/class-with-idisposable-members-not-disposable',
    category: 'code',
    domain: 'reliability',
    name: 'Class with IDisposable members is not disposable',
    description:
      'A class constructs and owns an IDisposable field but does not itself implement IDisposable, so the held resource is never released.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
    engine: 'roslyn-host',
  },

  // --- C# reliability rules ---
  {
    key: 'reliability/deterministic/azure-function-no-error-handling',
    category: 'code',
    domain: 'reliability',
    name: 'Azure Functions should use structured error handling',
    description: 'An Azure Function body with no try/catch, so failures go uncaught and unlogged.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/azure-function-failure-not-logged',
    category: 'code',
    domain: 'reliability',
    name: 'Unlogged Azure Function failure',
    description: 'An Azure Function catch block that swallows the exception without logging it, hiding failures.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/disposable-field-without-idisposable',
    category: 'code',
    domain: 'reliability',
    name: 'Owns disposable field but is not disposable',
    description: 'A class holds a field whose type implements IDisposable but the class itself does not implement IDisposable, so the held resource never gets a deterministic release path.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/dispose-own-members',
    category: 'code',
    domain: 'reliability',
    name: 'Classes should dispose their own members in Dispose',
    description: 'A Dispose method that does not dispose the IDisposable fields the class owns.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/disposable-without-finalizer',
    category: 'code',
    domain: 'reliability',
    name: 'Disposable types with unmanaged resources should declare finalizers',
    description: 'An IDisposable type holding unmanaged resources (IntPtr fields) without a finalizer, so a forgotten Dispose leaks the resource permanently.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/idisposable-pattern-incorrect',
    category: 'code',
    domain: 'reliability',
    name: 'IDisposable should be implemented correctly',
    description: 'A type implementing IDisposable that does not follow the standard dispose pattern (protected virtual Dispose(bool)), risking leaks or double-dispose.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/return-disposable-from-using',
    category: 'code',
    domain: 'reliability',
    name: 'IDisposables created in a using should not be returned',
    description: 'Returning an object that was created in a using block, so it is disposed before the caller can use it.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/dangerous-get-handle',
    category: 'code',
    domain: 'reliability',
    name: 'SafeHandle.DangerousGetHandle should not be called',
    description: 'DangerousGetHandle extracts the raw handle without reference counting and can leave it dangling if the SafeHandle is collected.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/task-without-taskscheduler',
    category: 'code',
    domain: 'reliability',
    name: 'Task continuation without scheduler',
    description: 'A Task.Factory.StartNew or ContinueWith call omits an explicit TaskScheduler, relying on TaskScheduler.Current which can surprise.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/thread-resume-suspend',
    category: 'code',
    domain: 'reliability',
    name: 'Thread.Resume and Thread.Suspend should not be used',
    description: 'Thread.Suspend/Resume are deprecated APIs that can suspend a thread mid-lock and deadlock the process.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/exception-logged-and-rethrown',
    category: 'code',
    domain: 'reliability',
    name: 'Exceptions should be either logged or rethrown, not both',
    description: 'A catch block that both logs an exception and rethrows it, producing duplicate noise as it bubbles up.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'reliability/deterministic/double-dispose',
    category: 'code',
    domain: 'reliability',
    name: 'Resource disposed twice',
    description:
      'A resource held by a using (statement or declaration) is also disposed explicitly inside the same scope. The using already disposes it at scope exit, so the explicit Dispose/DisposeAsync is a second disposal — undefined for many types and an ObjectDisposedException for some (CA2202). The variable is matched semantically.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'reliability/deterministic/idisposable-not-disposed',
    category: 'code',
    domain: 'reliability',
    name: 'IDisposable never disposed',
    description:
      'A local owns a freshly-new\'d IDisposable that is never released — no using, no Dispose(), and the reference never escapes (not returned, assigned away, or passed as an argument), so the handle leaks. Conservative: the moment the value escapes or is disposed it is cleared, so only an unambiguous local leak is flagged.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'reliability/deterministic/missing-configureawait',
    category: 'code',
    domain: 'reliability',
    name: 'ConfigureAwait(false) should be used in library code',
    description:
      'An await in library code that does not call ConfigureAwait(false) (S3216 / CA2007). A library that captures the caller\'s synchronization context can deadlock an application that blocks on the returned task under a single-threaded context. Needs the project OutputKind to identify library code and the semantic model to confirm the awaited type exposes ConfigureAwait, so it runs in MSBuildWorkspace mode.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    engine: 'roslyn-workspace',
  },
]
