import type { AnalysisRule } from '@truecourse/shared'

export const RELIABILITY_LLM_RULES: AnalysisRule[] = [
  {
    key: 'reliability/llm/missing-retry-logic',
    category: 'code',
    domain: 'reliability',
    name: 'Missing retry logic on network calls',
    description: 'External API/service call without retry mechanism — transient failures cause permanent failure.',
    prompt:
      'Find external API or service calls that lack retry logic. Look for: HTTP calls to external services (payment providers, email services, third-party APIs) without retry wrappers, database connection attempts that fail permanently on first error, and message queue publish calls without retry. Transient network failures are common — critical calls should retry with exponential backoff.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasCallsTo: ['fetch', 'axios', 'got', 'request', 'post', 'get'] },
      functionFilter: { callsAny: ['fetch', 'axios', 'got', 'request'] },
    },
  },
  {
    key: 'reliability/llm/missing-circuit-breaker',
    category: 'code',
    domain: 'reliability',
    name: 'Missing circuit breaker on external dependency',
    description: 'Repeated calls to failing external service without circuit breaker — cascading failure risk.',
    prompt:
      'Find external service integrations that lack circuit breaker patterns. Look for: HTTP calls to external services without tracking failure rates, retry loops without a maximum failure threshold after which calls stop, and code that keeps hammering a failing service instead of failing fast. Without a circuit breaker, one failing dependency can exhaust connection pools and cascade failures to the entire system.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasCallsTo: ['fetch', 'axios', 'got', 'request'] },
      functionFilter: { callsAny: ['fetch', 'axios', 'got', 'request'] },
    },
  },
  {
    key: 'reliability/llm/missing-graceful-shutdown',
    category: 'code',
    domain: 'reliability',
    name: 'Missing graceful shutdown handler',
    description: 'Server does not handle SIGTERM/SIGINT for clean connection drain and resource cleanup.',
    prompt:
      'Check whether the server handles SIGTERM and SIGINT signals for graceful shutdown. Look for: HTTP servers without process.on("SIGTERM") handlers, missing logic to stop accepting new connections and drain existing ones, database connection pools not closed on shutdown, and background job processors that do not finish current work before exiting. Without graceful shutdown, deployments cause dropped requests.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      fileFilter: { hasCallsTo: ['listen', 'createServer'] },
      metadataFields: ['functions', 'calls', 'imports'],
    },
  },
  {
    key: 'reliability/llm/unbounded-queue',
    category: 'code',
    domain: 'reliability',
    name: 'Unbounded queue or buffer',
    description: 'Queue/buffer that grows without backpressure — memory exhaustion under load.',
    prompt:
      'Find queues, buffers, or in-memory collections that can grow without bound. Look for: arrays used as job queues that are pushed to but only consumed asynchronously, event emitter listeners that buffer events faster than they can be processed, in-memory caches without size limits or eviction policies, and stream pipelines without backpressure handling. Under load, unbounded growth causes out-of-memory crashes.',
    enabled: true,
    severity: 'high',
    type: 'llm',
    contextRequirement: {
      tier: 'full-file',
      fileFilter: { isTestFile: false },
    },
  },
  {
    key: 'reliability/llm/missing-idempotency',
    category: 'code',
    domain: 'reliability',
    name: 'Non-idempotent mutation endpoint',
    description: 'POST/PUT endpoint that creates side effects without idempotency key — unsafe to retry.',
    prompt:
      'Find mutation endpoints that are not idempotent and cannot be safely retried. Look for: POST endpoints that create records without checking for duplicates or accepting an idempotency key, payment processing endpoints that could charge twice on retry, and endpoints that send emails or notifications without deduplication. Clients and infrastructure may retry requests — non-idempotent mutations cause duplicate side effects.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasRouteHandlers: true },
      functionFilter: { isRouteHandler: true },
    },
  },
  {
    key: 'reliability/llm/missing-dead-letter-handling',
    category: 'code',
    domain: 'reliability',
    name: 'Missing dead letter handling',
    description: 'Message queue consumer without dead letter queue — poison messages block processing forever.',
    prompt:
      'Find message queue consumers that lack dead letter handling. Look for: message handlers without a maximum retry count, queue consumers that nack/reject messages back to the same queue indefinitely, missing dead letter queue configuration, and poison message scenarios where a malformed message would block the queue forever. Without dead letter handling, one bad message can halt all processing.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasCallsTo: ['consume', 'subscribe', 'on', 'channel.consume', 'channel.assertQueue'] },
      functionFilter: { callsAny: ['consume', 'subscribe', 'channel.consume'] },
    },
  },
  {
    key: 'reliability/llm/partial-failure-not-handled',
    category: 'code',
    domain: 'reliability',
    name: 'Partial failure in batch operation',
    description: 'Batch operation that fails entirely if one item fails — should handle partial success.',
    prompt:
      'Find batch operations where one item failure causes the entire batch to fail. Look for: loops processing multiple items where a single thrown error aborts the entire operation, Promise.all on independent operations where one rejection cancels all, and bulk insert/update operations without per-item error handling. Batch operations should report partial success and continue processing remaining items.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasAsyncFunctions: true },
      functionFilter: { isAsync: true, callsAny: ['Promise.all', 'map', 'forEach'] },
    },
  },
  {
    key: 'reliability/llm/missing-health-check',
    category: 'code',
    domain: 'reliability',
    name: 'Missing health check endpoint',
    description: 'Service without /health or /ready endpoint — orchestrator cannot determine service health.',
    prompt:
      'Check whether the service exposes health check endpoints. Look for: HTTP servers without a /health, /healthz, or /ready endpoint, health checks that return 200 without actually verifying dependencies (database, cache, external services), and missing readiness vs liveness distinction. Without health checks, container orchestrators and load balancers cannot determine if the service is functioning.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      fileFilter: { hasRouteHandlers: true },
      metadataFields: ['routeRegistrations', 'imports'],
    },
  },
  {
    key: 'reliability/llm/stale-cache-no-invalidation',
    category: 'code',
    domain: 'reliability',
    name: 'Cache without invalidation strategy',
    description: 'Data cached without TTL, versioning, or invalidation — serves stale data indefinitely.',
    prompt:
      'Find caching implementations that lack an invalidation strategy. Look for: in-memory caches (Map, object) that store data without a TTL or expiration, Redis/Memcached usage without TTL set on keys, cached data that is never cleared when the source data changes, and memoization of values that can become stale. Without invalidation, users may see outdated data indefinitely.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'full-file',
      fileFilter: { hasCallsTo: ['set', 'cache', 'memoize', 'Redis'], isTestFile: false },
    },
  },
  {
    key: 'reliability/llm/missing-correlation-id',
    category: 'code',
    domain: 'reliability',
    name: 'Missing request correlation/trace ID',
    description: 'Request handling without propagating correlation ID — cannot trace request across services.',
    prompt:
      'Check whether requests are tagged with a correlation or trace ID that propagates across service boundaries. Look for: HTTP handlers that do not extract or generate a request ID, inter-service calls that do not forward the correlation ID header, log statements without a request context identifier, and event/message publishing without attaching the originating request ID.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      fileFilter: { hasRouteHandlers: true },
      metadataFields: ['functions', 'imports', 'routeRegistrations'],
    },
  },
  {
    key: 'reliability/llm/inconsistent-logging',
    category: 'code',
    domain: 'reliability',
    name: 'Inconsistent logging patterns',
    description: 'Mix of console.log, custom logger, and third-party logger in same codebase — hard to configure and filter.',
    prompt:
      'Check whether the codebase uses a consistent logging approach. Look for: mixing console.log/console.error with a logging library (winston, pino, bunyan), some modules using a custom logger while others use console directly, inconsistent log levels (some errors logged as info, warnings as errors), and production code using console.log for operational logging.',
    enabled: true,
    severity: 'low',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      metadataFields: ['imports', 'calls'],
    },
  },
  {
    key: 'reliability/llm/missing-structured-logging',
    category: 'code',
    domain: 'reliability',
    name: 'Unstructured log messages',
    description: 'Using string interpolation for logs instead of structured key-value logging — hard to parse and query.',
    prompt:
      'Find log statements that use string interpolation or concatenation instead of structured key-value logging. Look for: logger.info(`User ${userId} created order ${orderId}`) instead of logger.info({ userId, orderId }, "User created order"), template literal log messages that embed variables making them hard to parse programmatically, and inconsistent log message formats that prevent automated log analysis.',
    enabled: true,
    severity: 'low',
    type: 'llm',
    contextRequirement: {
      tier: 'full-file',
      fileFilter: { hasCallsTo: ['logger', 'log', 'console'], isTestFile: false },
    },
  },
  {
    key: 'reliability/llm/missing-error-monitoring',
    category: 'code',
    domain: 'reliability',
    name: 'No error monitoring integration',
    description: 'Application without error tracking service (Sentry, Bugsnag, etc.) — errors only visible in logs.',
    prompt:
      'Check whether the application has error monitoring integration. Look for: no Sentry, Bugsnag, Datadog, or similar error tracking SDK initialized, unhandled promise rejections without a global reporter, Express/Koa error middleware that only logs but does not report to an external service, and React applications without an error boundary that reports to a monitoring service. Without error monitoring, production errors go unnoticed.',
    enabled: true,
    severity: 'low',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      metadataFields: ['imports', 'calls'],
    },
  },
  {
    key: 'reliability/llm/silent-background-failure',
    category: 'code',
    domain: 'reliability',
    name: 'Silent background job failure',
    description: 'Background job/cron/worker that catches errors without alerting or recording failure state.',
    prompt:
      'Find background jobs, cron tasks, or worker processes that silently swallow errors. Look for: catch blocks in job handlers that only log without recording failure state or triggering alerts, cron jobs that continue on error without tracking consecutive failures, and worker processes where exceptions are caught but the job is marked as complete rather than failed. Silent failures mean data is never processed and nobody notices.',
    enabled: true,
    severity: 'high',
    type: 'llm',
    contextRequirement: {
      tier: 'targeted',
      fileFilter: { hasCatchBlocks: true, hasAsyncFunctions: true },
      functionFilter: { isAsync: true, containsCatchBlock: true },
    },
  },
  {
    key: 'reliability/llm/missing-metrics',
    category: 'code',
    domain: 'reliability',
    name: 'Missing performance metrics',
    description: 'No instrumentation for response times, queue depths, or resource utilization — blind to degradation.',
    prompt:
      'Check whether the application has performance metrics instrumentation. Look for: HTTP servers without response time tracking, database query duration not measured, queue depths and processing rates not monitored, and no metrics library (prom-client, StatsD, OpenTelemetry) initialized. Without metrics, performance degradation goes undetected until it causes outages.',
    enabled: true,
    severity: 'low',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      metadataFields: ['imports', 'calls'],
    },
  },
  {
    key: 'reliability/llm/missing-request-timeout',
    category: 'code',
    domain: 'reliability',
    name: 'Missing server-level request timeout',
    description: 'HTTP server without request timeout — slow clients can hold connections open indefinitely.',
    prompt:
      'Check whether the HTTP server has request timeouts configured. Look for: Express/Koa/Fastify servers without server.timeout or request timeout middleware, HTTP clients (axios, fetch, got) making calls without timeout options, and database connections without query timeout settings. Without timeouts, slow clients or unresponsive dependencies can exhaust connection pools and cause the entire service to hang.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
    contextRequirement: {
      tier: 'metadata',
      fileFilter: { hasCallsTo: ['listen', 'createServer', 'express', 'fastify'] },
      metadataFields: ['imports', 'calls', 'routeRegistrations'],
    },
  },
]
