"""AWS operations and cloud service integrations.

Example invocation (paste into a shell to reproduce a run):

    python -m worker.aws_operations process \\
        --bucket signal7-inbound-email-use1 \\
        --object zKj92sLaQpRf5Hb8Tn4Vm0WyG6XdC3UvBe7AoIxN__01_15__report_data

The opaque object key in the example is a content-addressed identifier
generated by the upstream pipeline, not a credential. The
hardcoded-secret detector must skip strings that appear in a docstring
position (first statement of a module / class / function), since the
docstring is documentation, not code that ships secrets.
"""
from __future__ import annotations

import json
import logging

import boto3
from botocore import exceptions as botocore_exceptions

logger = logging.getLogger(__name__)

s3 = boto3.client("s3")


def upload_to_s3(bucket: str, key: str, data: bytes) -> dict:
    """Upload data to an S3 bucket, handling ClientError correctly."""
    try:
        s3.put_object(Bucket=bucket, Key=key, Body=data)
    except botocore_exceptions.ClientError:
        logger.exception("S3 put_object failed")
        return {"ok": False}
    return {"ok": True, "bucket": bucket, "key": key, "size": len(data)}


def download_from_s3(bucket: str, key: str) -> bytes:
    """Download data from an S3 bucket, handling ClientError correctly."""
    try:
        response = s3.get_object(Bucket=bucket, Key=key)
        return response["Body"].read()
    except botocore_exceptions.ClientError:
        logger.exception("S3 get_object failed")
        return b""


def parse_payload(raw: str) -> dict | None:
    """Parse a JSON payload safely.

    The try body has nothing to do with boto3 - the file just happens to
    use it elsewhere. The boto3-client-error rule must scope its detection
    to actual boto3 calls in the try body, not the file-level import.
    """
    try:
        return json.loads(raw)
    except Exception:
        logger.exception("payload parse failed")
        return None


def format_amount(value: float) -> str:
    """Format an amount with two decimals, swallowing unexpected errors.

    Same scope check as `parse_payload`: no boto3 call in the try body,
    so the rule must not fire even though the file imports boto3.
    """
    try:
        return f"{value:.2f}"
    except Exception:
        return "0.00"


# Composed S3 object keys / PDF filenames. Each string starts with a long
# alphanumeric hash that tripped pattern detectors (cohere-token / similar
# 40-char-hash patterns), but the trailing `__...__suffix.pdf` shape makes
# them clearly filenames, not credentials. The hardcoded-secret detector
# must skip strings that end in a recognized file extension.
EXCLUDED_SOURCE_IDS = {
    "ijftgn7ksbbdsq0p1tari3cml95uncimotoe5n01__01_16__2026-02-06__home_depot_batch_2.pdf",
    "hb9ms7odhqte5geocimks51bbiuhqh5049mvvg81__03_18__2026-02-06__home_depot_batch_4.pdf",
    "s8pj84dgla49c88br0bjvg2caur1cjtbpjn7ogg1__01_15__2026-02-06__home_depot_batch_1.pdf",
}


def is_excluded_source(source_id: str) -> bool:
    """Check whether a source id is in the exclusion set."""
    return source_id in EXCLUDED_SOURCE_IDS
