import crypto from 'crypto';
const SALT = 'app-specific-salt';
const HASH_ALGORITHM = 'sha256';
const TOKEN_BYTES = 32;
const IV_BYTES = 16;
const HEX_ENCODING = 'hex';
const UTF8_ENCODING = 'utf8';
export function hashWithSalt(input: string): string {
  const hmac = crypto.createHmac(HASH_ALGORITHM, SALT);
  return hmac.update(input).digest(HEX_ENCODING);
}
export function generateSecureRandom(): string {
  return crypto.randomBytes(TOKEN_BYTES).toString(HEX_ENCODING);
}
export function encryptGcm(input: string, key: Buffer): string {
  const iv = crypto.randomBytes(IV_BYTES);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  return cipher.update(input, UTF8_ENCODING, HEX_ENCODING);
}
export function compareBuffers(a: string, b: string): boolean {
  return crypto.timingSafeEqual(Buffer.from(a, UTF8_ENCODING), Buffer.from(b, UTF8_ENCODING));
}



// ---------------------------------------------------------------------------
// Mode shape-7bab52885f80: deterministic fingerprint hashing of
// cryptographically-random API tokens and document content. No salt is needed
// because inputs already carry sufficient entropy (random tokens) or because
// deterministic lookup semantics are required (content fingerprint). This is
// NOT a credential-hashing context, so the rule must not flag it.
// ---------------------------------------------------------------------------

declare const cryptoApi: {
  createHash(algorithm: string): {
    update(data: string): { digest(encoding: string): string };
  };
  randomBytes(size: number): { toString(encoding: string): string };
};
declare const alphaid: (length: number) => string;

interface ApiTokenRecord {
  id: string;
  userId: string;
  tokenHash: string;
  fingerprint: string;
}

declare const tokenStore: {
  insert(record: ApiTokenRecord): Promise<ApiTokenRecord>;
  findByHash(tokenHash: string): Promise<ApiTokenRecord | null>;
};

// Hash a high-entropy API token for storage. The token is generated by
// alphaid(16) (~96 bits of entropy) so rainbow-table attacks are infeasible
// and a per-record salt would break deterministic lookup on the verify path.
export function hashApiToken(token: string): string {
  return cryptoApi.createHash('sha256').update(token).digest('hex');
}

// Produce a content fingerprint for a signed document. The fingerprint must
// be deterministic across re-renders so the signing flow can detect tampering;
// adding a salt would defeat the purpose. This is document content, not auth.
export function fingerprintDocument(contents: string): string {
  return cryptoApi.createHash('sha256').update(contents).digest('hex');
}

export async function issueApiToken(userId: string): Promise<{ token: string; record: ApiTokenRecord }> {
  const token = alphaid(16);
  const tokenHash = hashApiToken(token);
  const fingerprint = cryptoApi.createHash('sha256').update(userId + ':' + token).digest('hex');
  const record = await tokenStore.insert({
    id: alphaid(12),
    userId,
    tokenHash,
    fingerprint,
  });
  return { token, record };
}

export async function verifyApiToken(token: string): Promise<ApiTokenRecord | null> {
  const tokenHash = hashApiToken(token);
  return tokenStore.findByHash(tokenHash);
}

export function fingerprintWebhookPayload(payload: string): string {
  // Webhook delivery signature input - receivers re-derive deterministically.
  return cryptoApi.createHash('sha512').update(payload).digest('hex');
}

export function etagFor(body: string): string {
  // HTTP ETag: a content-derived cache key; salting it would break caches.
  return cryptoApi.createHash('md5').update(body).digest('hex');
}
