import type { AnalysisRule } from '@truecourse/shared'

export const BUGS_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'bugs/deterministic/empty-catch',
    category: 'code',
    domain: 'bugs',
    name: 'Empty error handler',
    description: 'Empty catch/except blocks that swallow errors silently.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bare-except',
    category: 'code',
    domain: 'bugs',
    name: 'Bare except clause',
    description: 'Bare except catches all exceptions including KeyboardInterrupt and SystemExit.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-default-arg',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable default argument',
    description: 'Using mutable default arguments (list, dict, set) shares the object across calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Self comparison',
    description: 'Comparing a value to itself is always true or false — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Self assignment',
    description: 'Assigning a variable to itself has no effect and is likely a bug.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assignment-in-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Assignment in condition',
    description: 'Using assignment (=) instead of comparison (===) in a condition.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-case',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate case value',
    description: 'Switch statement with duplicate case values — only the first case will execute.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-keys',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate object keys',
    description: 'Object literal or dictionary with duplicate keys — later values silently overwrite earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-args',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate function arguments',
    description: 'Function with duplicate parameter names — later parameters shadow earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/all-branches-identical',
    category: 'code',
    domain: 'bugs',
    name: 'All branches identical',
    description: 'If/else where all branches have identical code — the condition has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/constant-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Constant condition',
    description: 'Condition that is always true or always false.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreachable-code',
    category: 'code',
    domain: 'bugs',
    name: 'Unreachable code',
    description: 'Code after return, throw, break, or continue that can never execute.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-self-compare',
    category: 'code',
    domain: 'bugs',
    name: 'NaN self-comparison',
    description: 'Using x !== x or NaN === NaN to check NaN — use Number.isNaN() instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-class-members',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate class members',
    description: 'Class with duplicate method or property names — the later declaration silently overwrites the earlier one.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-else-if',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate else-if condition',
    description: 'if/else if chain with duplicate conditions — the second branch is dead code.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-branches',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate branch body',
    description: 'if/else if with identical branch bodies — likely copy-paste error.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-typeof',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid typeof comparison',
    description: 'typeof compared to an invalid string like "strig" — likely a typo.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/use-isnan',
    category: 'code',
    domain: 'bugs',
    name: 'Direct NaN comparison',
    description: 'Comparing directly to NaN with === or == always yields false — use Number.isNaN() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/compare-neg-zero',
    category: 'code',
    domain: 'bugs',
    name: 'Comparison with -0',
    description: 'Comparing with -0 is unreliable — use Object.is(x, -0) instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loss-of-precision',
    category: 'code',
    domain: 'bugs',
    name: 'Loss of precision',
    description: 'Number literal that exceeds safe integer range and loses precision at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-negation',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe negation',
    description: '`!a instanceof B` negates `a` instead of the result — use `!(a instanceof B)` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-optional-chaining',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe optional chaining',
    description: 'Optional chaining in a context where short-circuiting to undefined causes a runtime error.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-finally',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe finally',
    description: 'return/throw in finally block silently discards try/catch result.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fallthrough-case',
    category: 'code',
    domain: 'bugs',
    name: 'Switch case fallthrough',
    description: 'Switch case without break/return that falls through to the next case.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/for-direction',
    category: 'code',
    domain: 'bugs',
    name: 'Wrong loop direction',
    description: 'Loop counter going in the wrong direction, causing an infinite loop or never executing.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-constructor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Constructor with return',
    description: 'Constructor returning a value replaces the constructed instance — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-setter-return',
    category: 'code',
    domain: 'bugs',
    name: 'Setter with return value',
    description: 'Setter method returning a value — the return value is always ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-promise-executor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Promise executor return',
    description: 'Returning a value from Promise executor — use resolve() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreachable-loop',
    category: 'code',
    domain: 'bugs',
    name: 'Unreachable loop',
    description: 'Loop body always exits on the first iteration via return, break, or throw.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/constant-binary-expression',
    category: 'code',
    domain: 'bugs',
    name: 'Constant binary expression',
    description: 'Binary expression with literal operands that always produces the same result.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loop-counter-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Loop counter assignment',
    description: 'Assigning (not incrementing) the loop counter inside the loop body.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unmodified-loop-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Unmodified loop condition',
    description: 'While loop condition variable is never modified inside the loop body.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/const-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Const reassignment',
    description: 'Reassigning a const variable causes a runtime TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/class-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Class reassignment',
    description: 'Reassigning a class declaration is almost always a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/function-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Function reassignment',
    description: 'Reassigning a function declaration is almost always a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/import-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Import reassignment',
    description: 'Reassigning an import binding causes a TypeError in strict mode.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/getter-missing-return',
    category: 'code',
    domain: 'bugs',
    name: 'Getter missing return',
    description: 'Property getter without a return statement always returns undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/missing-super-call',
    category: 'code',
    domain: 'bugs',
    name: 'Missing super call',
    description: 'Constructor in derived class without super() call causes a ReferenceError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/this-before-super',
    category: 'code',
    domain: 'bugs',
    name: 'This before super',
    description: 'Using this before super() in derived constructor causes a ReferenceError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/async-promise-executor',
    category: 'code',
    domain: 'bugs',
    name: 'Async Promise executor',
    description: 'Async function as Promise executor — rejected promises from async errors are swallowed.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/empty-character-class',
    category: 'code',
    domain: 'bugs',
    name: 'Empty character class in regex',
    description: 'Regex with empty character class [] never matches anything.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-regexp',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid regular expression',
    description: 'Regular expression with syntax errors that will throw at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/control-chars-in-regex',
    category: 'code',
    domain: 'bugs',
    name: 'Control characters in regex',
    description: 'Regex containing control characters (ASCII 0x01–0x1f) that are likely unintentional.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/sparse-array',
    category: 'code',
    domain: 'bugs',
    name: 'Sparse array',
    description: 'Array literal with empty slots like [1,,3] — likely a typo.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/prototype-pollution',
    category: 'code',
    domain: 'bugs',
    name: 'Prototype pollution',
    description: 'Dynamic property assignment obj[key] = value where key could be __proto__.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/void-zero-argument',
    category: 'code',
    domain: 'bugs',
    name: 'Unnecessary void expression',
    description: 'void 0 or void(0) used unnecessarily — use undefined directly instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/exception-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Exception parameter reassignment',
    description: 'Reassigning the catch/except parameter loses the original error information.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/null-dereference',
    category: 'code',
    domain: 'bugs',
    name: 'Null dereference',
    description: 'Accessing a property on a value that could be null or undefined without a nullish check.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/symbol-description',
    category: 'code',
    domain: 'bugs',
    name: 'Symbol without description',
    description: 'Symbol() called without a description string — debugging is much harder without one.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/array-callback-return',
    category: 'code',
    domain: 'bugs',
    name: 'Array callback missing return',
    description: 'Callback passed to map/filter/reduce/find/findIndex/some/every/flatMap has no return statement.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-inner-declarations',
    category: 'code',
    domain: 'bugs',
    name: 'Function/var in block',
    description: 'Function declaration or var inside a block (if/else/while) — hoisting behaviour is confusing and varies by engine.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/template-curly-in-string',
    category: 'code',
    domain: 'bugs',
    name: 'Template expression in regular string',
    description: 'Regular string containing `${...}` — likely meant to be a template literal.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/await-in-loop',
    category: 'code',
    domain: 'bugs',
    name: 'Await inside loop',
    description: '`await` inside a loop body forces sequential execution — consider Promise.all() instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/element-overwrite',
    category: 'code',
    domain: 'bugs',
    name: 'Element overwritten before read',
    description: 'An array or object element is assigned twice without being read in between.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unthrown-error',
    category: 'code',
    domain: 'bugs',
    name: 'Error created but not thrown',
    description: '`new Error(...)` is created but never thrown — the error is silently discarded.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/non-existent-operator',
    category: 'code',
    domain: 'bugs',
    name: 'Non-existent operator',
    description: 'Using `=+` or `=!` instead of `+=` or `!=` — likely a typo.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/in-operator-on-primitive',
    category: 'code',
    domain: 'bugs',
    name: 'in operator on primitive',
    description: '`"prop" in primitive` throws a TypeError at runtime — `in` only works on objects.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/useless-increment',
    category: 'code',
    domain: 'bugs',
    name: 'Useless increment',
    description: 'Increment/decrement result is not used — the operation has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/ignored-return-value',
    category: 'code',
    domain: 'bugs',
    name: 'Ignored return value',
    description: 'Return value of a pure method (map, filter, slice, etc.) is ignored — the original array is unchanged.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/collection-size-mischeck',
    category: 'code',
    domain: 'bugs',
    name: 'Collection size mischeck',
    description: 'Checking `collection.length === undefined` or `=== null` instead of `> 0` — length is always a number.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/arguments-order-mismatch',
    category: 'code',
    domain: 'bugs',
    name: 'Arguments in wrong order',
    description: 'Function arguments appear to be passed in the wrong order based on parameter names.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unexpected-multiline',
    category: 'code',
    domain: 'bugs',
    name: 'Unexpected multiline expression',
    description: 'A return statement is followed by a value on the next line — ASI will insert a semicolon, making the return value undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/empty-collection-access',
    category: 'code',
    domain: 'bugs',
    name: 'Empty collection access',
    description: 'Accessing an element of an empty array literal — always returns undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/void-return-value-used',
    category: 'code',
    domain: 'bugs',
    name: 'Void return value used',
    description: 'Using the return value of `console.log()`, `forEach()`, or another void-returning function.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/new-operator-misuse',
    category: 'code',
    domain: 'bugs',
    name: 'new with non-constructor',
    description: '`new` used with known non-constructor functions like `Symbol()` or `BigInt()`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/useless-backreference',
    category: 'code',
    domain: 'bugs',
    name: 'Useless regex backreference',
    description: 'Regex backreference (\\1, \\k<name>) that always matches empty string because the referenced group appears after or in an alternation branch not yet tried.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/dissimilar-type-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Dissimilar type comparison',
    description: 'Comparing a string literal to a numeric literal with strict equality — always false.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  // ---- New batch (25 rules) ------------------------------------------------
  {
    key: 'bugs/deterministic/index-of-positive-check',
    category: 'code',
    domain: 'bugs',
    name: 'indexOf compared to positive number',
    description: 'indexOf result compared to a positive number instead of -1 — only -1 means "not found".',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/array-delete',
    category: 'code',
    domain: 'bugs',
    name: 'delete on array element',
    description: 'Using the delete operator on an array element leaves a hole instead of removing the element.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/comma-in-switch-case',
    category: 'code',
    domain: 'bugs',
    name: 'Comma in switch case',
    description: 'Using a comma expression in a switch case instead of separate cases — only the last value is matched.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/literal-call',
    category: 'code',
    domain: 'bugs',
    name: 'Literal used as function',
    description: 'Calling a literal value (number, string, boolean) as a function — always throws a TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/prototype-builtins-call',
    category: 'code',
    domain: 'bugs',
    name: 'Prototype builtin called directly',
    description: 'Calling Object.prototype methods (e.g. hasOwnProperty) directly on objects — may throw if object has a custom property.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/stateful-regex',
    category: 'code',
    domain: 'bugs',
    name: 'Stateful regex (global flag)',
    description: 'Regex with global or sticky flag has stateful lastIndex — reuse without resetting causes unexpected results.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/incorrect-string-concat',
    category: 'code',
    domain: 'bugs',
    name: 'Incorrect string concatenation',
    description: 'Adding a string and number without explicit conversion can produce surprising results.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/misleading-array-reverse',
    category: 'code',
    domain: 'bugs',
    name: 'Misleading array mutation',
    description: 'reverse() and sort() mutate the original array in place — using them in a way that looks non-mutating is misleading.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/global-this-usage',
    category: 'code',
    domain: 'bugs',
    name: 'Global this usage',
    description: 'Using `this` at the module/global scope — value is undefined in strict mode or the global object otherwise.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/inconsistent-return',
    category: 'code',
    domain: 'bugs',
    name: 'Inconsistent return',
    description: 'Function sometimes returns a value and sometimes returns nothing — callers cannot rely on the return type.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  // Python-only rules
  {
    key: 'bugs/deterministic/assert-on-tuple',
    category: 'code',
    domain: 'bugs',
    name: 'Assert on non-empty tuple',
    description: '`assert (condition, message)` always passes because a non-empty tuple is truthy — use `assert condition, message` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fstring-missing-placeholders',
    category: 'code',
    domain: 'bugs',
    name: 'f-string without placeholders',
    description: 'f-string prefix with no `{...}` expressions — unnecessary `f` prefix or forgotten interpolation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/raise-not-implemented',
    category: 'code',
    domain: 'bugs',
    name: 'raise NotImplemented instead of NotImplementedError',
    description: '`raise NotImplemented` raises a TypeError — the correct exception is `NotImplementedError`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/is-literal-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Identity comparison with literal',
    description: 'Using `is` or `is not` with a string, int, or bytes literal — unreliable due to Python interning.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/none-comparison-with-equality',
    category: 'code',
    domain: 'bugs',
    name: 'None compared with ==',
    description: 'Using `== None` instead of `is None` — semantically different if `__eq__` is overridden.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/type-comparison-instead-of-isinstance',
    category: 'code',
    domain: 'bugs',
    name: 'Direct type comparison',
    description: 'Using `type(x) == Y` instead of `isinstance(x, Y)` — misses subclasses.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-set-value',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate set value',
    description: 'Set literal with duplicate values — duplicates are silently ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loop-variable-overrides-iterator',
    category: 'code',
    domain: 'bugs',
    name: 'Loop variable overrides iterator',
    description: 'Loop variable has the same name as the iterable — the iterator reference is overwritten inside the loop.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/raise-without-from-in-except',
    category: 'code',
    domain: 'bugs',
    name: 'Raise without from in except',
    description: 'Raising a new exception inside an except block without `from` loses the original traceback.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/init-return-value',
    category: 'code',
    domain: 'bugs',
    name: '__init__ returns a value',
    description: '`__init__` must not return a value — Python ignores it, so any return value is silently discarded.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/yield-in-init',
    category: 'code',
    domain: 'bugs',
    name: 'yield in __init__',
    description: 'Using `yield` in `__init__` makes it a generator — calling `MyClass()` returns a generator, not an instance.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-base-classes',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate base classes',
    description: 'Class inheriting from the same base class more than once — duplicate bases cause a TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/float-equality-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Float equality comparison',
    description: 'Comparing float values with `==` is unreliable due to floating point representation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/function-call-in-default-argument',
    category: 'code',
    domain: 'bugs',
    name: 'Function call in default argument',
    description: 'Function call (e.g. `datetime.now()`) used as a default argument — evaluated once at definition time, not per call.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/zip-without-strict',
    category: 'code',
    domain: 'bugs',
    name: 'zip() without strict',
    description: '`zip()` silently truncates to the shortest iterable — pass `strict=True` to detect length mismatches.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  // ---- New batch (25 rules) ------------------------------------------------
  {
    key: 'bugs/deterministic/raise-literal',
    category: 'code',
    domain: 'bugs',
    name: 'Raising a literal value',
    description: '`raise "error"` raises a TypeError in Python 3 — must raise an exception instance or class.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bad-open-mode',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid file open mode',
    description: '`open()` called with an invalid mode string — raises ValueError at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loop-at-most-one-iteration',
    category: 'code',
    domain: 'bugs',
    name: 'Loop with at most one iteration',
    description: 'Loop body always breaks, returns, or raises on the first iteration — the loop is redundant.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/break-continue-in-finally',
    category: 'code',
    domain: 'bugs',
    name: 'break/continue in finally block',
    description: 'break or continue inside a finally block silently discards any active exception.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/infinite-recursion',
    category: 'code',
    domain: 'bugs',
    name: 'Infinite recursion',
    description: 'Function calls itself unconditionally — will always cause a RecursionError.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-handler-exception',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate exception in handler',
    description: 'Same exception class listed more than once in an except clause — duplicates are unreachable.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-class-default',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable class variable default',
    description: 'Class variable with a mutable default (list, dict, set) is shared across all instances.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-dataclass-default',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable dataclass field default',
    description: 'Dataclass field with a mutable default value — shared across all instances. Use `field(default_factory=...)` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/await-outside-async',
    category: 'code',
    domain: 'bugs',
    name: 'await outside async function',
    description: 'Using `await` outside of an async function causes a SyntaxError.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/asyncio-dangling-task',
    category: 'code',
    domain: 'bugs',
    name: 'Asyncio dangling task',
    description: '`asyncio.create_task()` result is not saved — the task may be garbage-collected before it completes.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unexpected-special-method-signature',
    category: 'code',
    domain: 'bugs',
    name: 'Wrong special method signature',
    description: 'Dunder method defined with the wrong number of parameters — Python will silently use the wrong version.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-function-arguments',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate keyword argument',
    description: 'Function called with the same keyword argument more than once — raises TypeError at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/not-implemented-in-bool-context',
    category: 'code',
    domain: 'bugs',
    name: 'NotImplemented in boolean context',
    description: '`NotImplemented` is truthy — using it in a boolean context (if/assert) is always True.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/cancellation-exception-not-reraised',
    category: 'code',
    domain: 'bugs',
    name: 'Cancellation exception swallowed',
    description: 'Catching `CancelledError` without re-raising prevents task cancellation.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assert-raises-too-broad',
    category: 'code',
    domain: 'bugs',
    name: 'pytest.raises with broad exception',
    description: '`pytest.raises(Exception)` is too broad — use a more specific exception type.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/hashable-set-dict-member',
    category: 'code',
    domain: 'bugs',
    name: 'Unhashable type in set or dict key',
    description: 'Using a mutable literal (list) as a dict key or set member — raises TypeError at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/iter-not-returning-iterator',
    category: 'code',
    domain: 'bugs',
    name: '__iter__ not returning iterator',
    description: '`__iter__` method does not return `self` or a generator — the protocol is broken.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/modified-loop-iterator',
    category: 'code',
    domain: 'bugs',
    name: 'Modifying collection while iterating',
    description: 'Adding or removing elements from a set/dict/list while iterating over it causes a RuntimeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/misleading-character-class',
    category: 'code',
    domain: 'bugs',
    name: 'Misleading character class in regex',
    description: 'Regex character class containing a multi-codepoint character (emoji or combining sequence) — only matches one codepoint at a time.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/race-condition-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Race condition assignment',
    description: 'Variable assigned before an await and then reassigned after — the first assignment may be clobbered by a concurrent write.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/regex-group-reference-mismatch',
    category: 'code',
    domain: 'bugs',
    name: 'Regex group reference mismatch',
    description: 'Replacement string references a group number that does not exist in the regex — raises IndexError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/undefined-export',
    category: 'code',
    domain: 'bugs',
    name: 'Undefined name in __all__',
    description: 'Name listed in `__all__` is not defined in the module — raises AttributeError on import.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/string-format-mismatch',
    category: 'code',
    domain: 'bugs',
    name: 'String format argument count mismatch',
    description: '`%` format string has a different number of placeholders than arguments provided.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/property-without-return',
    category: 'code',
    domain: 'bugs',
    name: 'Property method without return',
    description: '`@property` getter that never returns a value — always returns None.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-import',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate import',
    description: 'The same module or name is imported more than once — the later import shadows the earlier one.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  // ---- New batch (25 rules) ------------------------------------------------
  {
    key: 'bugs/deterministic/constructor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Constructor with return value',
    description: 'Constructor returning a value replaces the constructed instance — use `this` properties instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/setter-return',
    category: 'code',
    domain: 'bugs',
    name: 'Setter with return value',
    description: 'Setters should not return a value — the return value is always ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/promise-executor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Promise executor return',
    description: 'Returning a value from a Promise executor is misleading — use resolve() to fulfill the promise.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/exception-not-from-base-exception',
    category: 'code',
    domain: 'bugs',
    name: 'Exception not from BaseException',
    description: 'Raised or caught value does not derive from BaseException — causes TypeError at runtime.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-special-method-return-type',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid special method return type',
    description: '__len__, __bool__, __str__, __hash__ etc. returning a literal of the wrong type.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/exception-group-misuse',
    category: 'code',
    domain: 'bugs',
    name: 'ExceptionGroup caught with except*',
    description: 'ExceptionGroup/BaseExceptionGroup should not be caught with `except*` — causes infinite recursion.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreliable-callable-check',
    category: 'code',
    domain: 'bugs',
    name: 'Unreliable callable check',
    description: 'Using `hasattr(x, "__call__")` instead of `callable(x)` — misses many edge cases.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/strip-with-multi-chars',
    category: 'code',
    domain: 'bugs',
    name: 'strip() with multi-character string',
    description: '`str.strip("abc")` strips individual characters, not the substring "abc" — common misunderstanding.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assert-false',
    category: 'code',
    domain: 'bugs',
    name: 'assert False instead of raise',
    description: '`assert False` is removed with `-O` flag — raise an exception instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/redundant-tuple-in-exception',
    category: 'code',
    domain: 'bugs',
    name: 'Redundant tuple in except handler',
    description: '`except (ValueError,):` with trailing comma creates an unnecessary tuple — remove the comma.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/except-with-empty-tuple',
    category: 'code',
    domain: 'bugs',
    name: 'Except with empty tuple',
    description: '`except ():` catches nothing — this handler is useless.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unintentional-type-annotation',
    category: 'code',
    domain: 'bugs',
    name: 'Unintentional type annotation',
    description: '`x: int` appearing as a standalone annotation when `x: int = value` was intended.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/re-sub-positional-args',
    category: 'code',
    domain: 'bugs',
    name: 're.sub positional arguments confusion',
    description: '`re.sub(pattern, repl, string, flags)` — `flags` is a keyword argument; passing it positionally sets `count` instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/static-key-dict-comprehension',
    category: 'code',
    domain: 'bugs',
    name: 'Static key in dict comprehension',
    description: 'Dict comprehension with a constant key overwrites the same key each iteration — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fstring-docstring',
    category: 'code',
    domain: 'bugs',
    name: 'f-string used as docstring',
    description: 'f-strings cannot be docstrings — `__doc__` will be `None`. Use a plain string literal.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/useless-contextlib-suppress',
    category: 'code',
    domain: 'bugs',
    name: 'Useless contextlib.suppress',
    description: '`contextlib.suppress()` with no exception types does nothing.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/star-arg-after-keyword',
    category: 'code',
    domain: 'bugs',
    name: 'Star-arg unpacking after keyword argument',
    description: '`*args` unpacking after keyword arguments can cause unexpected behavior.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/nan-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'NaN comparison with ==',
    description: 'Comparing against `float("nan")` with `==` is always False — use `math.isnan()` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assignment-to-os-environ',
    category: 'code',
    domain: 'bugs',
    name: 'Direct assignment to os.environ',
    description: 'Assigning to `os.environ` replaces the entire environment mapping — use `os.environ.update()` instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assert-on-string-literal',
    category: 'code',
    domain: 'bugs',
    name: 'Assert on string literal',
    description: '`assert "message"` is always True because the string is truthy — the assertion never fails.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/binary-op-exception',
    category: 'code',
    domain: 'bugs',
    name: 'Binary operation on exception in except clause',
    description: '`except ValueError or TypeError` — the `or` expression evaluates to one exception; use a tuple instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/super-without-brackets',
    category: 'code',
    domain: 'bugs',
    name: 'super without parentheses',
    description: '`super` without `()` references the built-in function rather than calling it — the proxy object is never created.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/yield-from-in-async',
    category: 'code',
    domain: 'bugs',
    name: 'yield from in async function',
    description: '`yield from` inside an async function is a SyntaxError — use `async for` instead.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-all-object',
    category: 'code',
    domain: 'bugs',
    name: 'Non-string in __all__',
    description: 'Non-string object in `__all__` causes a TypeError when importing with `*`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-fromkeys-value',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable value in dict.fromkeys',
    description: '`dict.fromkeys(keys, [])` — all keys share the same mutable list instance. Use a dict comprehension instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  // ---- New batch (25 rules) ------------------------------------------------
  {
    key: 'bugs/deterministic/except-non-exception-class',
    category: 'code',
    domain: 'bugs',
    name: 'Except with non-exception class',
    description: '`except` clause catching a non-exception class (e.g., `int`, `str`) — raises TypeError at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/reuse-groupby-generator',
    category: 'code',
    domain: 'bugs',
    name: 'Reuse of groupby generator',
    description: '`itertools.groupby` group iterator is consumed on the next iteration — reuse yields nothing.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-contextvar-default',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable ContextVar default',
    description: '`ContextVar` with a mutable default value — the default is shared across all async contexts.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/import-self',
    category: 'code',
    domain: 'bugs',
    name: 'Module imports itself',
    description: 'Module importing itself by name — causes import errors or infinite recursion.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-envvar-value',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid os.getenv argument type',
    description: '`os.getenv()` called with a non-string first argument — raises TypeError at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/singledispatch-method-mismatch',
    category: 'code',
    domain: 'bugs',
    name: 'singledispatch/singledispatchmethod mismatch',
    description: 'Using `@singledispatch` on an instance method or `@singledispatchmethod` on a plain function — wrong decorator.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bidirectional-unicode',
    category: 'code',
    domain: 'bugs',
    name: 'Bidirectional unicode control character',
    description: 'Source file contains bidirectional unicode control characters — can alter execution flow appearance.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/dict-iter-missing-items',
    category: 'code',
    domain: 'bugs',
    name: 'Dict iteration missing .items()',
    description: 'Iterating over a dict with tuple unpacking without `.items()` — only yields keys, not (key, value) pairs.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/nonlocal-and-global',
    category: 'code',
    domain: 'bugs',
    name: 'nonlocal and global for same variable',
    description: 'Variable declared as both `nonlocal` and `global` in the same scope — SyntaxError.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/comparison-to-none-constant',
    category: 'code',
    domain: 'bugs',
    name: 'Comparison to None is always constant',
    description: 'Comparing a freshly created object to `None` always produces the same result.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/new-object-identity-check',
    category: 'code',
    domain: 'bugs',
    name: 'Identity check on new object',
    description: 'Creating a new object only to check its identity with `is` — always evaluates to `False`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/property-without-return',
    category: 'code',
    domain: 'bugs',
    name: 'Property method without return',
    description: '`@property` getter that never returns a value — always returns `None` unexpectedly.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/instance-method-missing-self',
    category: 'code',
    domain: 'bugs',
    name: 'Instance method missing self parameter',
    description: 'Instance or class method defined with no positional parameters — raises TypeError when called.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/property-param-count-wrong',
    category: 'code',
    domain: 'bugs',
    name: 'Property method with wrong parameter count',
    description: 'Property getter/setter/deleter defined with an incorrect number of parameters.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/exit-re-raise-in-except',
    category: 'code',
    domain: 'bugs',
    name: '__exit__ should not re-raise exception',
    description: '`__exit__` re-raising the provided exception instead of returning `False` — wrong context manager protocol.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/parameter-initial-value-ignored',
    category: 'code',
    domain: 'bugs',
    name: 'Function parameter initial value ignored',
    description: 'Parameter is immediately reassigned at the start of the function — default value is never used.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/defaultdict-default-factory-kwarg',
    category: 'code',
    domain: 'bugs',
    name: 'defaultdict with default_factory as keyword argument',
    description: '`defaultdict(default_factory=list)` — the first positional arg is the factory; keyword is ignored.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assignment-in-assert',
    category: 'code',
    domain: 'bugs',
    name: 'Assignment expression in assert statement',
    description: 'Using `:=` (walrus operator) in an `assert` — asserts may be removed with `-O` flag, making the assignment disappear.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assert-with-print-message',
    category: 'code',
    domain: 'bugs',
    name: 'Assert with print() as message',
    description: '`assert condition, print("msg")` — `print()` executes regardless and returns `None` as the assert message.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/decimal-from-float',
    category: 'code',
    domain: 'bugs',
    name: 'Decimal constructed from float literal',
    description: '`Decimal(0.1)` creates an imprecise decimal — use `Decimal("0.1")` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-dict-key',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate dictionary key in comprehension',
    description: 'Dictionary comprehension with a key expression that produces duplicates — last value silently wins.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/redefined-while-unused',
    category: 'code',
    domain: 'bugs',
    name: 'Import redefined before use',
    description: 'An import is shadowed by another import before it is ever used.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bad-string-format-character',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid % format character',
    description: 'Invalid conversion character in a `%`-format string — raises `ValueError` at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/nonlocal-without-binding',
    category: 'code',
    domain: 'bugs',
    name: 'nonlocal without enclosing binding',
    description: '`nonlocal` declaration for a variable not defined in any enclosing scope — SyntaxError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/load-before-global-declaration',
    category: 'code',
    domain: 'bugs',
    name: 'Variable used before global declaration',
    description: 'A variable is used before its `global` declaration in the same scope.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  // ---- New batch: 25 JS/TS rules ------------------------------------------------
  {
    key: 'bugs/deterministic/empty-pattern',
    category: 'code',
    domain: 'bugs',
    name: 'Empty destructuring pattern',
    description: 'Destructuring pattern that binds nothing — `const {} = obj` has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-obj-calls',
    category: 'code',
    domain: 'bugs',
    name: 'Global object called as function',
    description: 'Calling `Math`, `JSON`, `Reflect`, or `Atomics` as functions — always throws TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/async-constructor',
    category: 'code',
    domain: 'bugs',
    name: 'Async constructor',
    description: 'Constructor using `async` keyword — constructors cannot be async; awaited operations inside cannot be awaited externally.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/global-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Global reassignment',
    description: 'Reassigning read-only global objects like `undefined`, `NaN`, `Infinity`, `Math`, `JSON`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/variable-redeclaration',
    category: 'code',
    domain: 'bugs',
    name: 'Variable redeclaration',
    description: 'Redeclaring the same variable with `var` in the same scope — the second declaration is silently ignored.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/restricted-name-shadowing',
    category: 'code',
    domain: 'bugs',
    name: 'Restricted name shadowing',
    description: 'Shadowing built-in names like `undefined`, `NaN`, `Infinity` as a variable or parameter.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/case-declaration-leak',
    category: 'code',
    domain: 'bugs',
    name: 'Case declaration leak',
    description: 'Lexical declarations (`let`, `const`, `class`) in case clauses without a block — leaks to the entire switch scope.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/delete-variable',
    category: 'code',
    domain: 'bugs',
    name: 'Delete variable',
    description: 'Using `delete` operator on a plain variable — has no effect in strict mode and is confusing.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/octal-literal',
    category: 'code',
    domain: 'bugs',
    name: 'Octal literal',
    description: 'Legacy octal literal syntax `0755` — use `0o755` instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/octal-escape',
    category: 'code',
    domain: 'bugs',
    name: 'Octal escape sequence',
    description: 'Deprecated octal escape sequences like `\\012` in strings — use `\\n` or `\\x0a` instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/nonstandard-decimal-escape',
    category: 'code',
    domain: 'bugs',
    name: 'Nonstandard decimal escape',
    description: 'Invalid `\\8` and `\\9` escape sequences in strings — not valid octal escapes.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/lost-error-context',
    category: 'code',
    domain: 'bugs',
    name: 'Lost error context',
    description: 'Reassigning or replacing the caught error variable in a catch block — loses original error info.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/missing-radix',
    category: 'code',
    domain: 'bugs',
    name: 'Missing radix argument',
    description: '`parseInt()` without a radix argument — strings starting with `0` may be parsed as octal in some environments.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/extra-arguments-ignored',
    category: 'code',
    domain: 'bugs',
    name: 'Extra arguments ignored',
    description: 'Function called with more arguments than its parameter list accepts — extras are silently ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/for-in-array',
    category: 'code',
    domain: 'bugs',
    name: 'for-in loop on array',
    description: 'Using `for...in` to iterate an array — it iterates over enumerable keys (strings), not values.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/only-throw-error',
    category: 'code',
    domain: 'bugs',
    name: 'Non-Error thrown',
    description: 'Throwing a non-Error value (string, number, plain object) loses the stack trace.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/reduce-missing-initial',
    category: 'code',
    domain: 'bugs',
    name: 'Array.reduce missing initial value',
    description: '`Array.reduce()` called without an initial value — throws TypeError on empty arrays.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/array-sort-without-compare',
    category: 'code',
    domain: 'bugs',
    name: 'Array sorted without comparator',
    description: '`Array.sort()` without a compare function sorts lexicographically, not numerically.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/contradictory-optional-chain',
    category: 'code',
    domain: 'bugs',
    name: 'Non-null assertion after optional chain',
    description: '`x?.y!` asserts non-null after optional chaining that may return undefined — contradictory.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-enum-value',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate enum value',
    description: 'Duplicate numeric values in enum members — the duplicate member is unreachable.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/confusing-non-null-assertion',
    category: 'code',
    domain: 'bugs',
    name: 'Confusing non-null assertion',
    description: '`x! == y` looks like `x !== y` but is actually a non-null assertion followed by `==`.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/null-comparison-without-type-check',
    category: 'code',
    domain: 'bugs',
    name: 'Null comparison without type check',
    description: '`== null` matches both `null` and `undefined` — use `=== null` for precise null check.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/extra-non-null-assertion',
    category: 'code',
    domain: 'bugs',
    name: 'Extra non-null assertion',
    description: 'Double `!!` non-null assertion is redundant — one `!` is sufficient.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/label-variable-collision',
    category: 'code',
    domain: 'bugs',
    name: 'Label variable collision',
    description: 'Label sharing a name with a variable in scope — confusing and error-prone.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unassigned-variable',
    category: 'code',
    domain: 'bugs',
    name: 'Unassigned variable',
    description: 'Variable declared but never assigned a value — always `undefined` when read.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
