import type { AnalysisRule } from '@truecourse/shared'

export const BUGS_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'bugs/deterministic/empty-catch',
    category: 'code',
    domain: 'bugs',
    name: 'Empty error handler',
    description: 'Empty catch/except blocks that swallow errors silently.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bare-except',
    category: 'code',
    domain: 'bugs',
    name: 'Bare except clause',
    description: 'Bare except catches all exceptions including KeyboardInterrupt and SystemExit.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-default-arg',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable default argument',
    description: 'Using mutable default arguments (list, dict, set) shares the object across calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Self comparison',
    description: 'Comparing a value to itself is always true or false — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Self assignment',
    description: 'Assigning a variable to itself has no effect and is likely a bug.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assignment-in-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Assignment in condition',
    description: 'Using assignment (=) instead of comparison (===) in a condition.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-case',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate case value',
    description: 'Switch statement with duplicate case values — only the first case will execute.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-keys',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate object keys',
    description: 'Object literal or dictionary with duplicate keys — later values silently overwrite earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-args',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate function arguments',
    description: 'Function with duplicate parameter names — later parameters shadow earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/all-branches-identical',
    category: 'code',
    domain: 'bugs',
    name: 'All branches identical',
    description: 'If/else where all branches have identical code — the condition has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/constant-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Constant condition',
    description: 'Condition that is always true or always false.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreachable-code',
    category: 'code',
    domain: 'bugs',
    name: 'Unreachable code',
    description: 'Code after return, throw, break, or continue that can never execute.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-self-compare',
    category: 'code',
    domain: 'bugs',
    name: 'NaN self-comparison',
    description: 'Using x !== x or NaN === NaN to check NaN — use Number.isNaN() instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-class-members',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate class members',
    description: 'Class with duplicate method or property names — the later declaration silently overwrites the earlier one.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-else-if',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate else-if condition',
    description: 'if/else if chain with duplicate conditions — the second branch is dead code.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-branches',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate branch body',
    description: 'if/else if with identical branch bodies — likely copy-paste error.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-typeof',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid typeof comparison',
    description: 'typeof compared to an invalid string like "strig" — likely a typo.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/use-isnan',
    category: 'code',
    domain: 'bugs',
    name: 'Direct NaN comparison',
    description: 'Comparing directly to NaN with === or == always yields false — use Number.isNaN() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/compare-neg-zero',
    category: 'code',
    domain: 'bugs',
    name: 'Comparison with -0',
    description: 'Comparing with -0 is unreliable — use Object.is(x, -0) instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loss-of-precision',
    category: 'code',
    domain: 'bugs',
    name: 'Loss of precision',
    description: 'Number literal that exceeds safe integer range and loses precision at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-negation',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe negation',
    description: '`!a instanceof B` negates `a` instead of the result — use `!(a instanceof B)` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-optional-chaining',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe optional chaining',
    description: 'Optional chaining in a context where short-circuiting to undefined causes a runtime error.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-finally',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe finally',
    description: 'return/throw in finally block silently discards try/catch result.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fallthrough-case',
    category: 'code',
    domain: 'bugs',
    name: 'Switch case fallthrough',
    description: 'Switch case without break/return that falls through to the next case.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/for-direction',
    category: 'code',
    domain: 'bugs',
    name: 'Wrong loop direction',
    description: 'Loop counter going in the wrong direction, causing an infinite loop or never executing.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-constructor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Constructor with return',
    description: 'Constructor returning a value replaces the constructed instance — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-setter-return',
    category: 'code',
    domain: 'bugs',
    name: 'Setter with return value',
    description: 'Setter method returning a value — the return value is always ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-promise-executor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Promise executor return',
    description: 'Returning a value from Promise executor — use resolve() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
