import type { AnalysisRule } from '@truecourse/shared'

export const BUGS_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'bugs/deterministic/empty-catch',
    category: 'code',
    domain: 'bugs',
    name: 'Empty error handler',
    description: 'Empty catch/except blocks that swallow errors silently.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/bare-except',
    category: 'code',
    domain: 'bugs',
    name: 'Bare except clause',
    description: 'Bare except catches all exceptions including KeyboardInterrupt and SystemExit.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/mutable-default-arg',
    category: 'code',
    domain: 'bugs',
    name: 'Mutable default argument',
    description: 'Using mutable default arguments (list, dict, set) shares the object across calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Self comparison',
    description: 'Comparing a value to itself is always true or false — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/self-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Self assignment',
    description: 'Assigning a variable to itself has no effect and is likely a bug.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/assignment-in-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Assignment in condition',
    description: 'Using assignment (=) instead of comparison (===) in a condition.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-case',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate case value',
    description: 'Switch statement with duplicate case values — only the first case will execute.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-keys',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate object keys',
    description: 'Object literal or dictionary with duplicate keys — later values silently overwrite earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-args',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate function arguments',
    description: 'Function with duplicate parameter names — later parameters shadow earlier ones.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/all-branches-identical',
    category: 'code',
    domain: 'bugs',
    name: 'All branches identical',
    description: 'If/else where all branches have identical code — the condition has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/constant-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Constant condition',
    description: 'Condition that is always true or always false.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreachable-code',
    category: 'code',
    domain: 'bugs',
    name: 'Unreachable code',
    description: 'Code after return, throw, break, or continue that can never execute.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-self-compare',
    category: 'code',
    domain: 'bugs',
    name: 'NaN self-comparison',
    description: 'Using x !== x or NaN === NaN to check NaN — use Number.isNaN() instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-class-members',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate class members',
    description: 'Class with duplicate method or property names — the later declaration silently overwrites the earlier one.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-else-if',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate else-if condition',
    description: 'if/else if chain with duplicate conditions — the second branch is dead code.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-branches',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate branch body',
    description: 'if/else if with identical branch bodies — likely copy-paste error.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-typeof',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid typeof comparison',
    description: 'typeof compared to an invalid string like "strig" — likely a typo.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/use-isnan',
    category: 'code',
    domain: 'bugs',
    name: 'Direct NaN comparison',
    description: 'Comparing directly to NaN with === or == always yields false — use Number.isNaN() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/compare-neg-zero',
    category: 'code',
    domain: 'bugs',
    name: 'Comparison with -0',
    description: 'Comparing with -0 is unreliable — use Object.is(x, -0) instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loss-of-precision',
    category: 'code',
    domain: 'bugs',
    name: 'Loss of precision',
    description: 'Number literal that exceeds safe integer range and loses precision at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-negation',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe negation',
    description: '`!a instanceof B` negates `a` instead of the result — use `!(a instanceof B)` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-optional-chaining',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe optional chaining',
    description: 'Optional chaining in a context where short-circuiting to undefined causes a runtime error.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unsafe-finally',
    category: 'code',
    domain: 'bugs',
    name: 'Unsafe finally',
    description: 'return/throw in finally block silently discards try/catch result.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fallthrough-case',
    category: 'code',
    domain: 'bugs',
    name: 'Switch case fallthrough',
    description: 'Switch case without break/return that falls through to the next case.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/for-direction',
    category: 'code',
    domain: 'bugs',
    name: 'Wrong loop direction',
    description: 'Loop counter going in the wrong direction, causing an infinite loop or never executing.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-constructor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Constructor with return',
    description: 'Constructor returning a value replaces the constructed instance — likely a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-setter-return',
    category: 'code',
    domain: 'bugs',
    name: 'Setter with return value',
    description: 'Setter method returning a value — the return value is always ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-promise-executor-return',
    category: 'code',
    domain: 'bugs',
    name: 'Promise executor return',
    description: 'Returning a value from Promise executor — use resolve() instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unreachable-loop',
    category: 'code',
    domain: 'bugs',
    name: 'Unreachable loop',
    description: 'Loop body always exits on the first iteration via return, break, or throw.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/constant-binary-expression',
    category: 'code',
    domain: 'bugs',
    name: 'Constant binary expression',
    description: 'Binary expression with literal operands that always produces the same result.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loop-counter-assignment',
    category: 'code',
    domain: 'bugs',
    name: 'Loop counter assignment',
    description: 'Assigning (not incrementing) the loop counter inside the loop body.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unmodified-loop-condition',
    category: 'code',
    domain: 'bugs',
    name: 'Unmodified loop condition',
    description: 'While loop condition variable is never modified inside the loop body.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/const-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Const reassignment',
    description: 'Reassigning a const variable causes a runtime TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/class-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Class reassignment',
    description: 'Reassigning a class declaration is almost always a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/function-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Function reassignment',
    description: 'Reassigning a function declaration is almost always a bug.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/import-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Import reassignment',
    description: 'Reassigning an import binding causes a TypeError in strict mode.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/getter-missing-return',
    category: 'code',
    domain: 'bugs',
    name: 'Getter missing return',
    description: 'Property getter without a return statement always returns undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/missing-super-call',
    category: 'code',
    domain: 'bugs',
    name: 'Missing super call',
    description: 'Constructor in derived class without super() call causes a ReferenceError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/this-before-super',
    category: 'code',
    domain: 'bugs',
    name: 'This before super',
    description: 'Using this before super() in derived constructor causes a ReferenceError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/async-promise-executor',
    category: 'code',
    domain: 'bugs',
    name: 'Async Promise executor',
    description: 'Async function as Promise executor — rejected promises from async errors are swallowed.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/empty-character-class',
    category: 'code',
    domain: 'bugs',
    name: 'Empty character class in regex',
    description: 'Regex with empty character class [] never matches anything.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/invalid-regexp',
    category: 'code',
    domain: 'bugs',
    name: 'Invalid regular expression',
    description: 'Regular expression with syntax errors that will throw at runtime.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/control-chars-in-regex',
    category: 'code',
    domain: 'bugs',
    name: 'Control characters in regex',
    description: 'Regex containing control characters (ASCII 0x01–0x1f) that are likely unintentional.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/sparse-array',
    category: 'code',
    domain: 'bugs',
    name: 'Sparse array',
    description: 'Array literal with empty slots like [1,,3] — likely a typo.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/prototype-pollution',
    category: 'code',
    domain: 'bugs',
    name: 'Prototype pollution',
    description: 'Dynamic property assignment obj[key] = value where key could be __proto__.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/void-zero-argument',
    category: 'code',
    domain: 'bugs',
    name: 'Unnecessary void expression',
    description: 'void 0 or void(0) used unnecessarily — use undefined directly instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/exception-reassignment',
    category: 'code',
    domain: 'bugs',
    name: 'Exception parameter reassignment',
    description: 'Reassigning the catch/except parameter loses the original error information.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/null-dereference',
    category: 'code',
    domain: 'bugs',
    name: 'Null dereference',
    description: 'Accessing a property on a value that could be null or undefined without a nullish check.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/symbol-description',
    category: 'code',
    domain: 'bugs',
    name: 'Symbol without description',
    description: 'Symbol() called without a description string — debugging is much harder without one.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/array-callback-return',
    category: 'code',
    domain: 'bugs',
    name: 'Array callback missing return',
    description: 'Callback passed to map/filter/reduce/find/findIndex/some/every/flatMap has no return statement.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/no-inner-declarations',
    category: 'code',
    domain: 'bugs',
    name: 'Function/var in block',
    description: 'Function declaration or var inside a block (if/else/while) — hoisting behaviour is confusing and varies by engine.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/template-curly-in-string',
    category: 'code',
    domain: 'bugs',
    name: 'Template expression in regular string',
    description: 'Regular string containing `${...}` — likely meant to be a template literal.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/await-in-loop',
    category: 'code',
    domain: 'bugs',
    name: 'Await inside loop',
    description: '`await` inside a loop body forces sequential execution — consider Promise.all() instead.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/element-overwrite',
    category: 'code',
    domain: 'bugs',
    name: 'Element overwritten before read',
    description: 'An array or object element is assigned twice without being read in between.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unthrown-error',
    category: 'code',
    domain: 'bugs',
    name: 'Error created but not thrown',
    description: '`new Error(...)` is created but never thrown — the error is silently discarded.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/non-existent-operator',
    category: 'code',
    domain: 'bugs',
    name: 'Non-existent operator',
    description: 'Using `=+` or `=!` instead of `+=` or `!=` — likely a typo.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/in-operator-on-primitive',
    category: 'code',
    domain: 'bugs',
    name: 'in operator on primitive',
    description: '`"prop" in primitive` throws a TypeError at runtime — `in` only works on objects.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/useless-increment',
    category: 'code',
    domain: 'bugs',
    name: 'Useless increment',
    description: 'Increment/decrement result is not used — the operation has no effect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/ignored-return-value',
    category: 'code',
    domain: 'bugs',
    name: 'Ignored return value',
    description: 'Return value of a pure method (map, filter, slice, etc.) is ignored — the original array is unchanged.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/collection-size-mischeck',
    category: 'code',
    domain: 'bugs',
    name: 'Collection size mischeck',
    description: 'Checking `collection.length === undefined` or `=== null` instead of `> 0` — length is always a number.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/arguments-order-mismatch',
    category: 'code',
    domain: 'bugs',
    name: 'Arguments in wrong order',
    description: 'Function arguments appear to be passed in the wrong order based on parameter names.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/unexpected-multiline',
    category: 'code',
    domain: 'bugs',
    name: 'Unexpected multiline expression',
    description: 'A return statement is followed by a value on the next line — ASI will insert a semicolon, making the return value undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/empty-collection-access',
    category: 'code',
    domain: 'bugs',
    name: 'Empty collection access',
    description: 'Accessing an element of an empty array literal — always returns undefined.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/void-return-value-used',
    category: 'code',
    domain: 'bugs',
    name: 'Void return value used',
    description: 'Using the return value of `console.log()`, `forEach()`, or another void-returning function.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/new-operator-misuse',
    category: 'code',
    domain: 'bugs',
    name: 'new with non-constructor',
    description: '`new` used with known non-constructor functions like `Symbol()` or `BigInt()`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/useless-backreference',
    category: 'code',
    domain: 'bugs',
    name: 'Useless regex backreference',
    description: 'Regex backreference (\\1, \\k<name>) that always matches empty string because the referenced group appears after or in an alternation branch not yet tried.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/dissimilar-type-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Dissimilar type comparison',
    description: 'Comparing a string literal to a numeric literal with strict equality — always false.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  // ---- New batch (25 rules) ------------------------------------------------
  {
    key: 'bugs/deterministic/index-of-positive-check',
    category: 'code',
    domain: 'bugs',
    name: 'indexOf compared to positive number',
    description: 'indexOf result compared to a positive number instead of -1 — only -1 means "not found".',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/array-delete',
    category: 'code',
    domain: 'bugs',
    name: 'delete on array element',
    description: 'Using the delete operator on an array element leaves a hole instead of removing the element.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/comma-in-switch-case',
    category: 'code',
    domain: 'bugs',
    name: 'Comma in switch case',
    description: 'Using a comma expression in a switch case instead of separate cases — only the last value is matched.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/literal-call',
    category: 'code',
    domain: 'bugs',
    name: 'Literal used as function',
    description: 'Calling a literal value (number, string, boolean) as a function — always throws a TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/prototype-builtins-call',
    category: 'code',
    domain: 'bugs',
    name: 'Prototype builtin called directly',
    description: 'Calling Object.prototype methods (e.g. hasOwnProperty) directly on objects — may throw if object has a custom property.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/stateful-regex',
    category: 'code',
    domain: 'bugs',
    name: 'Stateful regex (global flag)',
    description: 'Regex with global or sticky flag has stateful lastIndex — reuse without resetting causes unexpected results.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/incorrect-string-concat',
    category: 'code',
    domain: 'bugs',
    name: 'Incorrect string concatenation',
    description: 'Adding a string and number without explicit conversion can produce surprising results.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/misleading-array-reverse',
    category: 'code',
    domain: 'bugs',
    name: 'Misleading array mutation',
    description: 'reverse() and sort() mutate the original array in place — using them in a way that looks non-mutating is misleading.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/global-this-usage',
    category: 'code',
    domain: 'bugs',
    name: 'Global this usage',
    description: 'Using `this` at the module/global scope — value is undefined in strict mode or the global object otherwise.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/inconsistent-return',
    category: 'code',
    domain: 'bugs',
    name: 'Inconsistent return',
    description: 'Function sometimes returns a value and sometimes returns nothing — callers cannot rely on the return type.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  // Python-only rules
  {
    key: 'bugs/deterministic/assert-on-tuple',
    category: 'code',
    domain: 'bugs',
    name: 'Assert on non-empty tuple',
    description: '`assert (condition, message)` always passes because a non-empty tuple is truthy — use `assert condition, message` instead.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/fstring-missing-placeholders',
    category: 'code',
    domain: 'bugs',
    name: 'f-string without placeholders',
    description: 'f-string prefix with no `{...}` expressions — unnecessary `f` prefix or forgotten interpolation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/raise-not-implemented',
    category: 'code',
    domain: 'bugs',
    name: 'raise NotImplemented instead of NotImplementedError',
    description: '`raise NotImplemented` raises a TypeError — the correct exception is `NotImplementedError`.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/is-literal-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Identity comparison with literal',
    description: 'Using `is` or `is not` with a string, int, or bytes literal — unreliable due to Python interning.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/none-comparison-with-equality',
    category: 'code',
    domain: 'bugs',
    name: 'None compared with ==',
    description: 'Using `== None` instead of `is None` — semantically different if `__eq__` is overridden.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/type-comparison-instead-of-isinstance',
    category: 'code',
    domain: 'bugs',
    name: 'Direct type comparison',
    description: 'Using `type(x) == Y` instead of `isinstance(x, Y)` — misses subclasses.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-set-value',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate set value',
    description: 'Set literal with duplicate values — duplicates are silently ignored.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/loop-variable-overrides-iterator',
    category: 'code',
    domain: 'bugs',
    name: 'Loop variable overrides iterator',
    description: 'Loop variable has the same name as the iterable — the iterator reference is overwritten inside the loop.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/raise-without-from-in-except',
    category: 'code',
    domain: 'bugs',
    name: 'Raise without from in except',
    description: 'Raising a new exception inside an except block without `from` loses the original traceback.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/init-return-value',
    category: 'code',
    domain: 'bugs',
    name: '__init__ returns a value',
    description: '`__init__` must not return a value — Python ignores it, so any return value is silently discarded.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/yield-in-init',
    category: 'code',
    domain: 'bugs',
    name: 'yield in __init__',
    description: 'Using `yield` in `__init__` makes it a generator — calling `MyClass()` returns a generator, not an instance.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/duplicate-base-classes',
    category: 'code',
    domain: 'bugs',
    name: 'Duplicate base classes',
    description: 'Class inheriting from the same base class more than once — duplicate bases cause a TypeError.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/float-equality-comparison',
    category: 'code',
    domain: 'bugs',
    name: 'Float equality comparison',
    description: 'Comparing float values with `==` is unreliable due to floating point representation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/function-call-in-default-argument',
    category: 'code',
    domain: 'bugs',
    name: 'Function call in default argument',
    description: 'Function call (e.g. `datetime.now()`) used as a default argument — evaluated once at definition time, not per call.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'bugs/deterministic/zip-without-strict',
    category: 'code',
    domain: 'bugs',
    name: 'zip() without strict',
    description: '`zip()` silently truncates to the shortest iterable — pass `strict=True` to detect length mismatches.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
]
