import type { AnalysisRule } from '@truecourse/shared'

export const ARCHITECTURE_DETERMINISTIC_RULES: AnalysisRule[] = [
  // Service-level deterministic rules
  {
    key: 'architecture/deterministic/circular-service-dependency',
    category: 'service',
    domain: 'architecture',
    name: 'Circular service dependency',
    description: 'Two services depend on each other, creating a circular dependency.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/god-service',
    category: 'service',
    domain: 'architecture',
    name: 'God service',
    description: 'Service has too many files or spans too many layers, suggesting too many responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },

  // Module-level deterministic rules
  {
    key: 'architecture/deterministic/data-layer-depends-on-api',
    category: 'module',
    domain: 'architecture',
    name: 'Data layer depends on API layer',
    description: 'Data layer should not import from the API layer.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/external-layer-depends-on-api',
    category: 'module',
    domain: 'architecture',
    name: 'External layer depends on API layer',
    description: 'External integrations should not depend on the API layer directly.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/data-layer-depends-on-external',
    category: 'module',
    domain: 'architecture',
    name: 'Data layer depends on external layer',
    description: 'Data layer should not call external services.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/cross-service-internal-import',
    category: 'module',
    domain: 'architecture',
    name: 'Cross-service internal import',
    description: 'Module imports from another service\'s internal layer (data, service, external) instead of its API.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/circular-module-dependency',
    category: 'module',
    domain: 'architecture',
    name: 'Circular module dependency',
    description: 'Circular import chains between modules, including transitive cycles.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/god-module',
    category: 'module',
    domain: 'architecture',
    name: 'God module with too many methods',
    description: 'Class or module has too many methods (>15), suggesting too many responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/unused-export',
    category: 'module',
    domain: 'architecture',
    name: 'Unused export',
    description: 'Exported function or class not imported anywhere in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/dead-module',
    category: 'module',
    domain: 'architecture',
    name: 'Dead module',
    description: 'Module has no incoming or outgoing dependencies — likely unused.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/orphan-file',
    category: 'module',
    domain: 'architecture',
    name: 'Orphan file',
    description: 'Source file is never imported by any other file in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },

  // Method-level deterministic rules
  {
    key: 'architecture/deterministic/long-method',
    category: 'method',
    domain: 'architecture',
    name: 'Long method',
    description: 'Function has too many statements (>30), making it hard to understand.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/too-many-parameters',
    category: 'method',
    domain: 'architecture',
    name: 'Too many parameters',
    description: 'Function has 5 or more parameters, suggesting it needs refactoring.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/deeply-nested-logic',
    category: 'method',
    domain: 'architecture',
    name: 'Deeply nested logic',
    description: 'Function has excessive nesting depth (>4 levels), making it hard to follow.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/dead-method',
    category: 'method',
    domain: 'architecture',
    name: 'Dead method',
    description: 'Method has no incoming or outgoing calls — likely unused.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },

  // Code-level deterministic rules (AST visitors)
  {
    key: 'architecture/deterministic/duplicate-import',
    category: 'code',
    domain: 'architecture',
    name: 'Duplicate import',
    description: 'Same module imported multiple times in a file.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/implicit-dependency',
    category: 'code',
    domain: 'architecture',
    name: 'Implicit dependency',
    description: 'Module uses a dependency not declared in package.json.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/declarations-in-global-scope',
    category: 'code',
    domain: 'architecture',
    name: 'Global scope declaration',
    description: 'Mutable variable declared in global/module scope.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/unused-import',
    category: 'code',
    domain: 'architecture',
    name: 'Unused import',
    description: 'Import never referenced in the file.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/missing-input-validation',
    category: 'code',
    domain: 'architecture',
    name: 'Missing input validation',
    description: 'Route handler accesses request body without input validation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/missing-pagination-endpoint',
    category: 'code',
    domain: 'architecture',
    name: 'List endpoint without pagination',
    description: 'GET endpoint returns a list without pagination.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/missing-error-status-code',
    category: 'code',
    domain: 'architecture',
    name: 'Missing error status code',
    description: 'Catch block sends response without setting an error status code.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/route-without-auth-middleware',
    category: 'code',
    domain: 'architecture',
    name: 'Route without auth middleware',
    description: 'Route handler has no authentication middleware.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/missing-rate-limiting',
    category: 'code',
    domain: 'architecture',
    name: 'Missing rate limiting',
    description: 'API routes without rate limiting middleware.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/missing-request-body-size-limit',
    category: 'code',
    domain: 'architecture',
    name: 'No request body size limit',
    description: 'express.json()/bodyParser without a body size limit.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/raw-error-in-response',
    category: 'code',
    domain: 'architecture',
    name: 'Error details in API response',
    description: 'Error stack or message exposed in API response.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/type-assertion-overuse',
    category: 'code',
    domain: 'architecture',
    name: 'Type assertion to any',
    description: 'Heavy use of "as any" type assertions bypasses type safety.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'architecture/deterministic/barrel-file-re-export-all',
    category: 'code',
    domain: 'architecture',
    name: 'Barrel file with many re-exports',
    description: "index.ts with many 'export *' re-exports can slow down bundlers.",
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },

  // C# semantic rules (Roslyn host) — need the type/semantic model.
  {
    key: 'architecture/deterministic/deep-inheritance-chain',
    category: 'code',
    domain: 'architecture',
    name: 'Excessive inheritance depth',
    description:
      'A type sits many levels deep in its total inheritance chain (every ancestor up to System.Object), making the effective behavior hard to follow.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/deep-inheritance-tree',
    category: 'code',
    domain: 'architecture',
    name: 'Class inheritance tree is too deep',
    description:
      'A class derives through too many project-defined base classes (framework bases excluded), a maintainability and fragility signal.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/class-coupled-to-too-many',
    category: 'code',
    domain: 'architecture',
    name: 'Class is coupled to too many other classes',
    description:
      'A type references an excessive number of distinct other types, a high-efferent-coupling signal that makes it fragile and hard to maintain.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/excessive-class-coupling',
    category: 'code',
    domain: 'architecture',
    name: 'Excessive class coupling',
    description:
      'A single method references an unusually large number of distinct types, indicating high coupling and low cohesion in that member.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/namespace-folder-mismatch',
    category: 'code',
    domain: 'architecture',
    name: "Namespace does not match the file's folder path",
    description:
      "A type's namespace does not match its file's location under the project root, breaking the conventional namespace-to-directory mapping and making types hard to locate.",
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-workspace',
  },
  {
    key: 'architecture/deterministic/missing-public-argument-validation',
    category: 'code',
    domain: 'architecture',
    name: 'Missing null validation on public method argument',
    description:
      'A public method dereferences a reference-type parameter without a null guard, so callers get an opaque NullReferenceException instead of a clear ArgumentNullException.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/private-method-belongs-in-nested-class',
    category: 'code',
    domain: 'architecture',
    name: 'Private methods used only by a nested class should move into it',
    description:
      'A private method is called exclusively from one nested type and belongs there for cohesion.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'architecture/deterministic/prefer-uri-over-string',
    category: 'code',
    domain: 'architecture',
    name: 'System.Uri arguments should be used instead of strings',
    description:
      'A method accepts a URL as a string with no System.Uri overload, forcing ad-hoc parsing at every call site instead of a validated Uri contract.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
]
