import type { AnalysisRule } from '@truecourse/shared'

export const ARCHITECTURE_LLM_RULES: AnalysisRule[] = [
  {
    key: 'architecture/llm/tight-coupling',
    category: 'service',
    domain: 'architecture',
    name: 'Tightly coupled service pair',
    description: 'Identify pairs of services with unusually high cross-dependencies.',
    prompt:
      'Identify pairs of services with an unusually high number of dependencies between them. If two services have many import or HTTP dependencies in both directions, they may be too tightly coupled and could benefit from being merged or having a shared interface extracted. Consider the ratio of cross-service dependencies to total dependencies.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/missing-layers',
    category: 'service',
    domain: 'architecture',
    name: 'Service missing expected architectural layers',
    description: 'Check whether each service has the expected architectural layers for its type.',
    prompt:
      'Check whether each service has the expected architectural layers for its type. An API server should typically have an api layer and a service layer. A service with a data layer should usually have a service layer mediating access. Flag services that are missing layers that would be expected given their role and dependencies.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/circular-module-dependency',
    category: 'module',
    domain: 'architecture',
    name: 'Circular module dependency',
    description: 'Circular imports between modules within a service.',
    prompt:
      'Detect circular import chains between modules within the same service. A circular dependency exists when module A imports module B, and module B (directly or transitively) imports module A. Flag any cycles found and list the full dependency chain. Circular module dependencies make refactoring difficult and indicate unclear boundaries.',
    enabled: true,
    severity: 'high',
    type: 'llm',
  },
  {
    key: 'architecture/llm/deep-inheritance-chain',
    category: 'module',
    domain: 'architecture',
    name: 'Deep inheritance chain',
    description: 'Class extending 3+ levels deep.',
    prompt:
      'Identify classes with deep inheritance chains (3 or more levels of extends). Deep inheritance makes code fragile — changes in base classes ripple unpredictably. Flag the full chain and suggest composition over inheritance where appropriate.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/excessive-fan-out',
    category: 'module',
    domain: 'architecture',
    name: 'Excessive fan-out',
    description: 'Module importing too many other modules.',
    prompt:
      'Identify modules that import too many other modules (high fan-out). A module with many outgoing dependencies is tightly coupled to the rest of the codebase and hard to change in isolation. Flag modules importing from more than 8-10 other internal modules and suggest extracting responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/excessive-fan-in',
    category: 'module',
    domain: 'architecture',
    name: 'Excessive fan-in',
    description: 'Module imported by too many others.',
    prompt:
      'Identify modules imported by a disproportionately high number of other modules (high fan-in). These are bottleneck modules where any change has a large blast radius. Flag such modules and assess whether they should be split into smaller, more focused interfaces.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/mixed-abstraction-levels',
    category: 'module',
    domain: 'architecture',
    name: 'Mixed abstraction levels',
    description: 'Method mixing high-level orchestration with low-level details.',
    prompt:
      'Identify methods that mix different abstraction levels — e.g., a function that both orchestrates high-level workflow (calling other services, managing transactions) and performs low-level operations (string manipulation, raw SQL, bit operations). Each function should operate at a single level of abstraction. Flag methods where you see this mixing and suggest how to separate concerns.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/inconsistent-response-format',
    category: 'service',
    domain: 'architecture',
    name: 'Inconsistent API response format',
    description: 'Endpoints return data in different shapes (some wrapped, some not, different error formats).',
    prompt:
      'Find API endpoints that return data in inconsistent shapes. Look for: some endpoints wrapping responses in { data: ... } while others return raw objects, different error response formats across endpoints (some with { error: message } vs { errors: [...] }), and mixed conventions for pagination, status codes, or envelope structures. Flag specific endpoint pairs that are inconsistent.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/breaking-api-change',
    category: 'service',
    domain: 'architecture',
    name: 'Breaking API contract change',
    description: 'Endpoint removes or renames fields, changes types, or alters behavior without versioning.',
    prompt:
      'Identify API endpoints where fields have been removed, renamed, or had their types changed without a version bump. Look for commented-out response fields, TODO comments about deprecation, type changes on existing fields, and removed properties that clients may depend on. Breaking changes without versioning cause silent client failures.',
    enabled: true,
    severity: 'high',
    type: 'llm',
  },
  {
    key: 'architecture/llm/missing-api-versioning',
    category: 'service',
    domain: 'architecture',
    name: 'Missing API versioning',
    description: 'Public API without version prefix (/v1/) — no path for backward-compatible evolution.',
    prompt:
      'Check whether public API routes include a version prefix such as /v1/ or /api/v1/. APIs without versioning have no path for backward-compatible evolution — any breaking change forces all clients to update simultaneously. Flag route definitions that expose public endpoints without version prefixes.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/over-exposed-internal-model',
    category: 'service',
    domain: 'architecture',
    name: 'Internal data model exposed in API',
    description: 'Database schema or internal object structure leaked directly in API response — coupling clients to internals.',
    prompt:
      'Find API endpoints that return database models or internal objects directly without mapping to a DTO or response shape. Look for: route handlers that pass ORM entities straight to res.json(), responses containing internal fields like _id, __v, createdAt from the ORM, or database column names leaking through. Exposing internals couples API clients to the database schema.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/chatty-api',
    category: 'service',
    domain: 'architecture',
    name: 'Chatty API requiring many round trips',
    description: 'Client needs multiple sequential API calls to accomplish single logical operation — should be combined.',
    prompt:
      'Identify patterns where a client must make multiple sequential API calls to accomplish a single logical operation. Look for: frontend code making 3+ sequential fetch/axios calls, API endpoints that return IDs requiring follow-up calls to get details, and operations split across many small endpoints that could be a single batch endpoint. Chatty APIs increase latency and failure probability.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/wrong-http-method',
    category: 'service',
    domain: 'architecture',
    name: 'Incorrect HTTP method for operation',
    description: 'Using GET for mutations or POST for idempotent reads — violates REST semantics.',
    prompt:
      'Find routes where the HTTP method does not match the operation semantics. Look for: GET handlers that modify database state or create side effects, POST endpoints that only read data without creating resources, DELETE endpoints that return the deleted resource in full, and PUT used for partial updates where PATCH would be appropriate. Incorrect HTTP methods break caching, prefetching, and client expectations.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/missing-api-error-documentation',
    category: 'service',
    domain: 'architecture',
    name: 'Undocumented error responses',
    description: 'API endpoint can return error codes not documented or not typed — clients cannot handle them.',
    prompt:
      'Find API endpoints that can return error status codes or error shapes that are not documented in types, JSDoc, or OpenAPI specs. Look for: catch blocks that return ad-hoc error objects, multiple different error formats from the same endpoint, and error codes thrown deep in service layers that bubble up without being declared in the route handler types.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/feature-envy',
    category: 'module',
    domain: 'architecture',
    name: 'Feature envy',
    description: 'Method primarily uses data from another class/module — logic should move to where the data lives.',
    prompt:
      'Identify methods that primarily access data from another class or module rather than their own. Look for: functions that take an object parameter and access 3+ of its properties while using none of their own class state, methods that call multiple getters on a single external object to compute a result, and utility functions that clearly belong on the class they operate on. The logic should move to where the data lives.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/shotgun-surgery',
    category: 'module',
    domain: 'architecture',
    name: 'Shotgun surgery',
    description: 'Single logical change requires modifying many files across the codebase — poor encapsulation.',
    prompt:
      'Identify cases where a single logical change would require modifications across many files. Look for: the same constant or configuration value duplicated in multiple files, parallel class hierarchies that must be updated in lockstep, switch statements on the same type discriminator scattered across multiple files, and feature additions that require touching 5+ files. This indicates poor encapsulation.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/divergent-change',
    category: 'module',
    domain: 'architecture',
    name: 'Divergent change',
    description: 'Single file/class modified for many unrelated reasons — violates single responsibility.',
    prompt:
      'Identify files or classes that are modified for many unrelated reasons. Look for: large files with multiple unrelated groups of functions, classes with methods serving different stakeholders (e.g., user-facing + admin + reporting), files that appear in most pull requests regardless of the feature, and utility files that have grown to include unrelated functionality. These violate the single responsibility principle.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/inappropriate-intimacy',
    category: 'module',
    domain: 'architecture',
    name: 'Inappropriate intimacy between modules',
    description: 'Two modules accessing each other\'s internals instead of public interfaces — high coupling.',
    prompt:
      'Find modules that access each other\'s internal implementation details instead of using public interfaces. Look for: modules importing private/internal symbols (underscored names, non-exported helpers), directly accessing another module\'s internal data structures, reaching into nested properties of objects owned by another module, and bypassing a module\'s public API to call internal methods.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/middleman-class',
    category: 'module',
    domain: 'architecture',
    name: 'Middleman class',
    description: 'Class that only delegates to another class without adding value — unnecessary indirection.',
    prompt:
      'Find classes or modules whose methods primarily delegate to another single class without adding meaningful logic. Look for: classes where most methods are one-liners that call the same method on an injected dependency, wrapper classes that add no validation, transformation, or error handling, and service classes that merely proxy repository calls. These add indirection without value.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/god-function',
    category: 'module',
    domain: 'architecture',
    name: 'God function orchestrating everything',
    description: 'Single function handling validation, business logic, persistence, and notification — common in route handlers.',
    prompt:
      'Find functions that handle too many responsibilities in a single body. Look for route handlers or service methods that perform validation, business logic, database operations, and side effects (email, notifications, logging) all in one function. These god functions are hard to test, hard to reuse, and violate separation of concerns. Flag functions that span 3+ distinct responsibility areas.',
    enabled: true,
    severity: 'high',
    type: 'llm',
  },
  {
    key: 'architecture/llm/primitive-obsession',
    category: 'module',
    domain: 'architecture',
    name: 'Primitive obsession',
    description: 'Using primitive types (string, number) for domain concepts (email, money, userId) — no validation or behavior.',
    prompt:
      'Identify places where primitive types (string, number) are used for domain concepts that deserve their own type. Look for: email addresses, phone numbers, monetary amounts, URLs, or IDs passed around as plain strings/numbers without validation, functions accepting multiple string parameters that could be confused (userId, email, name all as string), and repeated inline validation of the same format.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/leaky-abstraction',
    category: 'module',
    domain: 'architecture',
    name: 'Leaky abstraction',
    description: 'Abstraction layer that exposes implementation details — callers depend on internal behavior.',
    prompt:
      'Find abstraction layers that leak implementation details to their callers. Look for: repository interfaces that expose ORM-specific query builders, service methods whose return types include database-specific fields, wrapper functions that require callers to understand the underlying library\'s error types, and abstractions where callers must catch implementation-specific exceptions.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/missing-abstraction',
    category: 'module',
    domain: 'architecture',
    name: 'Missing abstraction layer',
    description: 'Business logic directly calling infrastructure (DB, HTTP, file system) without service/repository layer.',
    prompt:
      'Find business logic that directly calls infrastructure without an abstraction layer. Look for: route handlers containing raw SQL queries or direct ORM calls, business logic functions that make HTTP requests to external services inline, components that directly read/write files, and controllers that instantiate database connections. These should go through a service or repository layer.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/temporal-coupling',
    category: 'module',
    domain: 'architecture',
    name: 'Temporal coupling',
    description: 'Functions that must be called in specific order without the code enforcing that order.',
    prompt:
      'Find functions or methods that must be called in a specific order but where the code does not enforce that order. Look for: init() methods that must be called before other methods work, setup/configure functions whose omission causes silent failures, classes where calling methods out of order produces wrong results without errors, and multi-step processes where skipping a step silently corrupts state.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/hardcoded-business-rule',
    category: 'module',
    domain: 'architecture',
    name: 'Hardcoded business rule',
    description: 'Business rule embedded in code instead of being configurable or data-driven.',
    prompt:
      'Find business rules hardcoded directly in application logic that should be configurable or data-driven. Look for: hardcoded price thresholds, rate limits, feature eligibility criteria, discount percentages, or role-based access rules embedded in if/switch statements. These rules change frequently and should be in configuration, database, or a rules engine rather than requiring code deployment to update.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/component-too-many-responsibilities',
    category: 'module',
    domain: 'architecture',
    name: 'Component with too many responsibilities',
    description: 'Single React component handling data fetching, business logic, and complex UI — should be split.',
    prompt:
      'Find React components that handle too many responsibilities. Look for: components that contain data fetching (useEffect + fetch), business logic (calculations, transformations, validation), and complex rendering all in one file. Components over 200 lines that mix these concerns should be split into a container component, custom hooks for data/logic, and presentational components for rendering.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/prop-drilling-deep',
    category: 'module',
    domain: 'architecture',
    name: 'Deep prop drilling',
    description: 'Prop passed through 3+ intermediate components that don\'t use it — use context or composition.',
    prompt:
      'Identify props being passed through 3 or more intermediate components that do not use the prop themselves. Look for: the same prop name appearing in multiple component interfaces in a parent-child chain, wrapper components that spread props without using them, and deeply nested component trees where leaf components need data from far-up ancestors. Suggest using React context, composition, or state management.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/business-logic-in-component',
    category: 'module',
    domain: 'architecture',
    name: 'Business logic in React component',
    description: 'Complex business rules in component instead of custom hook or service — not reusable or testable.',
    prompt:
      'Find React components containing complex business logic that should be extracted. Look for: multi-step calculations or data transformations inside component bodies, complex conditional logic for business rules (pricing, permissions, eligibility), and validation logic that is not in a custom hook or utility function. Business logic in components is hard to test independently and cannot be reused.',
    enabled: true,
    severity: 'medium',
    type: 'llm',
  },
  {
    key: 'architecture/llm/mixed-data-fetching-patterns',
    category: 'module',
    domain: 'architecture',
    name: 'Inconsistent data fetching patterns',
    description: 'Mix of useEffect+fetch, React Query, SWR, and direct axios in same app — should standardize.',
    prompt:
      'Check whether the application uses multiple different data fetching approaches. Look for: mixing useEffect+fetch with React Query or SWR, some components using axios while others use fetch, inconsistent error handling and loading state patterns across data fetching code, and custom hooks that reinvent caching already provided by installed libraries. The app should standardize on one approach.',
    enabled: true,
    severity: 'low',
    type: 'llm',
  },
  {
    key: 'architecture/llm/middleware-order-incorrect',
    category: 'module',
    domain: 'architecture',
    name: 'Incorrect Express middleware ordering',
    description: 'Auth middleware after route handlers, body parser after routes, or CORS after routes — middleware not applied.',
    prompt:
      'Check Express/Koa middleware ordering for correctness. Look for: authentication/authorization middleware registered after route handlers (routes bypass auth), body-parser or express.json() registered after routes that need parsed bodies, CORS middleware registered after routes, error-handling middleware not at the end of the chain, and rate limiting applied after the routes it should protect.',
    enabled: true,
    severity: 'high',
    type: 'llm',
  },
]
