/** Style-domain helpers for the C# visitors. */
import type { Node as SyntaxNode } from 'web-tree-sitter'
import { getCSharpAttributeNames } from '../../../_shared/csharp-helpers.js'

/**
 * Generated C# files (EF migration designers, gRPC stubs, WinForms designers,
 * T4 output) carry an `<auto-generated>` header per the .NET convention that
 * analyzers honor. Style findings there are noise — the file is rewritten by
 * a tool.
 */
export function isAutoGeneratedCSharpFile(sourceCode: string): boolean {
  return sourceCode.slice(0, 1024).includes('<auto-generated')
}

/** PascalCase per .NET conventions: uppercase start, no underscores. */
export function isPascalCase(name: string): boolean {
  return /^[A-Z]/.test(name) && !name.includes('_')
}

/**
 * Method-level attributes of the mainstream .NET test frameworks (xUnit,
 * NUnit, MSTest) and BenchmarkDotNet. Members carrying them follow framework
 * naming/documentation conventions, not API conventions.
 */
const TEST_METHOD_ATTRIBUTES = new Set([
  // xUnit
  'Fact', 'Theory',
  // NUnit
  'Test', 'TestCase', 'TestCaseSource', 'SetUp', 'TearDown', 'OneTimeSetUp', 'OneTimeTearDown',
  // MSTest
  'TestMethod', 'DataTestMethod', 'TestInitialize', 'TestCleanup', 'ClassInitialize', 'ClassCleanup',
  // BenchmarkDotNet
  'Benchmark', 'GlobalSetup', 'GlobalCleanup',
])

const TEST_CLASS_ATTRIBUTES = new Set(['TestClass', 'TestFixture'])

/** True when the method carries a test/benchmark framework attribute. */
export function isCSharpTestMethod(method: SyntaxNode): boolean {
  return getCSharpAttributeNames(method).some((name) => TEST_METHOD_ATTRIBUTES.has(name))
}

/**
 * True when the class is a test class: marked with a test-class attribute
 * (NUnit/MSTest) or containing test-attributed methods (xUnit test classes
 * carry no class-level attribute).
 */
export function isCSharpTestClass(classNode: SyntaxNode): boolean {
  if (getCSharpAttributeNames(classNode).some((name) => TEST_CLASS_ATTRIBUTES.has(name))) return true
  const body = classNode.childForFieldName('body') ?? classNode.namedChildren.find((c) => c?.type === 'declaration_list')
  if (!body) return false
  return body.namedChildren.some((member) => member?.type === 'method_declaration' && isCSharpTestMethod(member))
}

/** True when the node is, or is nested inside, a test class. */
export function isWithinCSharpTestClass(node: SyntaxNode): boolean {
  for (let current: SyntaxNode | null = node; current; current = current.parent) {
    if (current.type === 'class_declaration' && isCSharpTestClass(current)) return true
  }
  return false
}

/** True when an enum_declaration carries the `[Flags]` attribute. */
export function isFlagsEnum(enumNode: SyntaxNode): boolean {
  return getCSharpAttributeNames(enumNode).includes('Flags')
}

/** A type-member declaration (field/property/method/event/indexer). */
const MEMBER_DECLARATION_TYPES = new Set([
  'method_declaration',
  'property_declaration',
  'event_declaration',
  'event_field_declaration',
])

/**
 * True when `node` is the NAME being introduced by a type-member declaration:
 * a field/property/method/event of a type — the positions where a member named
 * `field` can shadow the C# 14 backing-field keyword inside a property
 * accessor. Locals and parameters are out of scope (lower risk, high FP rate).
 */
export function isCSharpMemberDeclarationName(node: SyntaxNode): boolean {
  const parent = node.parent
  if (!parent) return false
  // method/property/event expose the name in their `name` field.
  if (MEMBER_DECLARATION_TYPES.has(parent.type)) {
    return parent.childForFieldName('name')?.id === node.id
  }
  // A field: variable_declarator → variable_declaration → field_declaration.
  if (parent.type === 'variable_declarator' && parent.childForFieldName('name')?.id === node.id) {
    const declaration = parent.parent
    return declaration?.parent?.type === 'field_declaration'
  }
  return false
}
