import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile } from './_helpers.js'

/**
 * SA1121 — a basic .NET type referenced by its framework name (`Int32`,
 * `String`, …) in a type position instead of the idiomatic C# language alias
 * (`int`, `string`). The aliases and their framework types are exactly the
 * same type; the language guidance (and the default compiler/IDE convention)
 * is to use the keyword form.
 *
 * Only flags identifiers that are unambiguously in a TYPE position — the
 * `type`/`returns` slot of a declaration/cast/array/object-creation, or a
 * pure-type container (generic argument list, base list, tuple element). Value
 * references (`String.Empty`), `nameof(Int32)`, and `typeof(String)` are left
 * alone: those name the type deliberately and the keyword form reads worse or
 * is illegal there.
 *
 * `IntPtr`/`UIntPtr` are intentionally excluded — their `nint`/`nuint` aliases
 * are recent (C# 9) and the framework spelling is still idiomatic.
 */
const ALIAS_BY_FRAMEWORK: Record<string, string> = {
  Boolean: 'bool',
  Byte: 'byte',
  SByte: 'sbyte',
  Char: 'char',
  Decimal: 'decimal',
  Double: 'double',
  Single: 'float',
  Int16: 'short',
  UInt16: 'ushort',
  Int32: 'int',
  UInt32: 'uint',
  Int64: 'long',
  UInt64: 'ulong',
  Object: 'object',
  String: 'string',
}

/** Parents whose every identifier child is a type. */
const PURE_TYPE_CONTAINERS = new Set([
  'type_argument_list',
  'base_list',
  'tuple_element',
  'nullable_type',
  'pointer_type',
])

/**
 * `typeof(String)` / `sizeof(Int32)` name the type deliberately for
 * reflection; the framework spelling reads fine there and is left alone.
 */
const REFLECTION_TYPE_PARENTS = new Set(['typeof_expression', 'sizeof_expression', 'default_expression'])

/** True when `node` sits in a type position rather than a value position. */
function isInTypePosition(node: SyntaxNode): boolean {
  const parent = node.parent
  if (!parent) return false
  if (REFLECTION_TYPE_PARENTS.has(parent.type)) return false
  if (PURE_TYPE_CONTAINERS.has(parent.type)) return true
  // The `type`/`returns` slot of a declaration, cast, array, object creation.
  const typeChild = parent.childForFieldName('type')
  if (typeChild && typeChild.id === node.id) return true
  const returnsChild = parent.childForFieldName('returns')
  if (returnsChild && returnsChild.id === node.id) return true
  return false
}

export const csharpBuiltinTypeAliasVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/builtin-type-alias',
  languages: ['csharp'],
  nodeTypes: ['identifier'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null

    const alias = ALIAS_BY_FRAMEWORK[node.text]
    if (!alias) return null
    if (!isInTypePosition(node)) return null

    return makeViolation(
      this.ruleKey, node, filePath, 'low',
      'Use the built-in type alias',
      `Type '${node.text}' is the framework name for the C# alias '${alias}'. The language convention is to use the alias.`,
      sourceCode,
      `Replace '${node.text}' with '${alias}'.`,
    )
  },
}
