import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { hasCSharpModifier } from '../../../_shared/csharp-helpers.js'
import { isAutoGeneratedCSharpFile, isCSharpTestClass, isCSharpTestMethod, isWithinCSharpTestClass } from './_helpers.js'

/**
 * The C# docstring is the XML doc comment (`/// <summary>` — the construct
 * behind compiler warning CS1591 and StyleCop SA1600): public types and
 * methods without one are undocumented public API. Mirrors the Python
 * visitor's scope (public declarations only). Skips, to avoid flagging code
 * that follows other conventions: test classes/methods (framework naming is
 * the documentation), `override` methods (docs live on the base/`inheritdoc`),
 * EF Core migrations, `Main`, and `<auto-generated>` files.
 */
const KIND_BY_NODE_TYPE: Record<string, string> = {
  class_declaration: 'Class',
  interface_declaration: 'Interface',
  struct_declaration: 'Struct',
  record_declaration: 'Record',
  enum_declaration: 'Enum',
  method_declaration: 'Method',
}

/** True for `class X : Migration` — EF Core migrations are tool-managed. */
function extendsMigration(classNode: SyntaxNode): boolean {
  const bases = classNode.namedChildren.find((c) => c?.type === 'base_list')
  if (!bases) return false
  return bases.namedChildren.some((base) => {
    const text = base?.text ?? ''
    return text === 'Migration' || text.endsWith('.Migration')
  })
}

/** A doc/regular comment directly above the declaration documents it. */
function hasCommentAbove(node: SyntaxNode): boolean {
  const prev = node.previousNamedSibling
  return prev?.type === 'comment' && prev.endPosition.row >= node.startPosition.row - 1
}

export const csharpDocstringCompletenessVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/docstring-completeness',
  languages: ['csharp'],
  nodeTypes: Object.keys(KIND_BY_NODE_TYPE),
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (!hasCSharpModifier(node, 'public')) return null

    const name = node.childForFieldName('name')
    if (!name) return null

    if (node.type === 'method_declaration') {
      if (hasCSharpModifier(node, 'override')) return null
      if (node.namedChildren.some((c) => c?.type === 'explicit_interface_specifier')) return null
      if (name.text === 'Main' && hasCSharpModifier(node, 'static')) return null
      if (isCSharpTestMethod(node)) return null
    }
    if (node.type === 'class_declaration' && (isCSharpTestClass(node) || extendsMigration(node))) return null
    if (isWithinCSharpTestClass(node)) return null

    if (hasCommentAbove(node)) return null

    const kind = KIND_BY_NODE_TYPE[node.type]!
    return makeViolation(
      this.ruleKey, name, filePath, 'low',
      `${kind} missing doc comment`,
      `Public ${kind.toLowerCase()} '${name.text}' has no XML doc comment.`,
      sourceCode,
      `Add an XML doc comment above the declaration:\n/// <summary>What '${name.text}' does.</summary>`,
    )
  },
}
