import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile, isFlagsEnum } from './_helpers.js'

/**
 * A [Flags] enum whose type name ends in `Flags` or `Enum` restates
 * the kind in the name. `[Flags] enum ColorFlags` / `enum StatusEnum` read
 * redundantly at every use site (`ColorFlags.Red`); the suffix carries no
 * information the declaration doesn't already.
 */
export const csharpEnumNameRedundantSuffixVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/enum-name-redundant-suffix',
  languages: ['csharp'],
  nodeTypes: ['enum_declaration'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (!isFlagsEnum(node)) return null

    const name = node.childForFieldName('name')
    if (!name) return null

    const suffix = /Flags$/.test(name.text) ? 'Flags' : /Enum$/.test(name.text) ? 'Enum' : null
    if (!suffix) return null

    const trimmed = name.text.slice(0, -suffix.length)
    return makeViolation(
      this.ruleKey, name, filePath, 'low',
      `Enum name has redundant '${suffix}' suffix`,
      `Enum '${name.text}' ends with the redundant suffix '${suffix}'.`,
      sourceCode,
      `Rename to '${trimmed || name.text}' (drop the '${suffix}' suffix).`,
    )
  },
}
