import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile, isFlagsEnum, isPascalCase } from './_helpers.js'

/**
 * [Flags] enum MEMBERS must follow the .NET PascalCase naming
 * convention. The enum type name is covered by
 * style/deterministic/csharp-naming-convention; this visitor owns the member
 * names (which that rule does not check) so the two never overlap. Fires once
 * per enum on the first non-conforming member.
 */
function pascalize(name: string): string {
  return name
    .replace(/^_+/, '')
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

export const csharpEnumNamingConventionVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/enum-naming-convention',
  languages: ['csharp'],
  nodeTypes: ['enum_declaration'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (!isFlagsEnum(node)) return null

    const list = node.namedChildren.find((c) => c?.type === 'enum_member_declaration_list')
    if (!list) return null

    for (const member of list.namedChildren) {
      if (member?.type !== 'enum_member_declaration') continue
      const memberName: SyntaxNode | null = member.childForFieldName('name') ?? member.namedChildren[0] ?? null
      if (!memberName || memberName.type !== 'identifier') continue
      if (isPascalCase(memberName.text)) continue

      return makeViolation(
        this.ruleKey, memberName, filePath, 'low',
        'Enum member not in PascalCase',
        `Flags enum member '${memberName.text}' does not follow the .NET PascalCase naming convention.`,
        sourceCode,
        `Rename to PascalCase: ${pascalize(memberName.text)}.`,
      )
    }

    return null
  },
}
