import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile, isCSharpMemberDeclarationName } from './_helpers.js'

/**
 * `field` became a contextual keyword in C# 14 (the auto-property
 * backing field). Declaring a type MEMBER named `field` is a
 * forward-compatibility hazard: inside a property accessor the name now binds
 * to the backing field, so existing code can change meaning. Scoped to member
 * declarations (field/property/method/event) — locals and parameters are out
 * of scope to avoid false positives on incidental uses.
 */
export const csharpFieldKeywordConflictVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/field-keyword-conflict',
  languages: ['csharp'],
  nodeTypes: ['identifier'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (node.text !== 'field') return null
    if (!isCSharpMemberDeclarationName(node)) return null

    return makeViolation(
      this.ruleKey, node, filePath, 'low',
      "Identifier 'field' conflicts with a C# keyword",
      "'field' is a contextual keyword in C# 14 (the auto-property backing field); naming a member 'field' is a forward-compatibility hazard.",
      sourceCode,
      "Rename the identifier, or escape it as '@field' where it must keep this name.",
    )
  },
}
