import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile, isFlagsEnum } from './_helpers.js'

/**
 * In a [Flags] enum the zero value is the absence of all flags, so it
 * reads correctly in bitwise combinations only when named `None`
 * (`Permissions.None`, `flags & ~Permissions.Write`). A different name for the
 * `= 0` member (`Default`, `Unset`, …) is confusing.
 *
 * Only the explicit `= 0` member is checked. The implicit-zero first member is
 * left alone: without it the absence value is conventionally implied and
 * flagging it would be noisy.
 */
function memberValue(member: SyntaxNode): string | null {
  // enum_member_declaration: name [= value]; value is the second named child.
  for (let i = member.namedChildCount - 1; i >= 1; i--) {
    const child = member.namedChild(i)
    if (child) return child.text.trim()
  }
  return null
}

export const csharpFlagsEnumZeroNotNoneVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/flags-enum-zero-not-none',
  languages: ['csharp'],
  nodeTypes: ['enum_declaration'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (!isFlagsEnum(node)) return null

    const list = node.namedChildren.find((c) => c?.type === 'enum_member_declaration_list')
    if (!list) return null

    for (const member of list.namedChildren) {
      if (member?.type !== 'enum_member_declaration') continue
      const name = member.childForFieldName('name') ?? member.namedChildren[0]
      if (!name || name.type !== 'identifier') continue
      if (memberValue(member) !== '0') continue
      if (name.text === 'None') return null

      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        'Flags enum zero value not named None',
        `The 0 value of [Flags] enum member '${name.text}' should be named 'None' to read correctly in bitwise combinations.`,
        sourceCode,
        `Rename the 0-value member to 'None'.`,
      )
    }

    return null
  },
}
