import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile } from './_helpers.js'

/**
 * Logger *fields* should follow a consistent naming convention so loggers are
 * recognizable across a codebase. The accepted .NET form is camelCase with an
 * optional leading underscore (`logger`, `_logger`, `_log`). A logger field
 * named otherwise (`Logger`, `MyLog`, `LOG`) is flagged.
 *
 * Properties are intentionally NOT flagged: by .NET convention a property is
 * PascalCase regardless of accessibility, so the property-injection idiom
 * (`public ILogger<T> Logger { get; set; }` / `protected ILogger Logger => …`)
 * is correct — the camelCase/underscore convention is a field convention. This
 * matches the rule key (`logger-field-naming`) and removes a large class of
 * false positives on frameworks that use property injection.
 *
 * The logger type is matched syntactically by its simple name — the standard
 * `Microsoft.Extensions.Logging` / Serilog / NLog abstractions. A factory
 * (`ILoggerFactory`) is not a logger and is excluded.
 */
const LOGGER_TYPE_NAMES = new Set(['ILogger', 'Logger', 'ILog'])

/** camelCase, optionally `_`-prefixed: the accepted logger field form. */
const ACCEPTED = /^_?[a-z][a-zA-Z0-9]*$/

/** Simple type name from an identifier / generic_name / qualified_name node. */
function simpleTypeName(typeNode: SyntaxNode | null): string {
  if (!typeNode) return ''
  if (typeNode.type === 'identifier') return typeNode.text
  if (typeNode.type === 'generic_name') {
    return typeNode.namedChildren.find((c) => c?.type === 'identifier')?.text ?? ''
  }
  if (typeNode.type === 'qualified_name') {
    return typeNode.text.split('.').pop() ?? ''
  }
  return ''
}

function isLoggerType(typeNode: SyntaxNode | null): boolean {
  return LOGGER_TYPE_NAMES.has(simpleTypeName(typeNode))
}

export const csharpLoggerFieldNamingVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/logger-field-naming',
  languages: ['csharp'],
  nodeTypes: ['field_declaration'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null

    // field_declaration → variable_declaration(type, declarator…)
    const declaration = node.namedChildren.find((c) => c?.type === 'variable_declaration')
    if (!declaration) return null
    if (!isLoggerType(declaration.namedChild(0))) return null
    for (const declarator of declaration.namedChildren) {
      if (declarator?.type !== 'variable_declarator') continue
      const name = declarator.namedChild(0)
      if (!name || name.type !== 'identifier' || ACCEPTED.test(name.text)) continue
      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        'Logger does not follow the naming convention',
        `Logger field '${name.text}' does not follow the convention for logger members (camelCase, optionally _-prefixed).`,
        sourceCode,
        `Rename the logger to a camelCase name such as '_logger'.`,
      )
    }
    return null
  },
}
