import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { getCSharpAttributeNames, hasCSharpModifier } from '../../../_shared/csharp-helpers.js'
import { isAutoGeneratedCSharpFile, isCSharpTestMethod, isPascalCase } from './_helpers.js'

/**
 * .NET naming conventions, under the catalog's naming-convention rule key
 * (the catalog has only language-prefixed naming keys; this is the C#
 * counterpart of the JS visitor — "follow the language's naming
 * conventions"). Checks the parts every .NET style camp agrees on
 * (Framework Design Guidelines, IDE1006 defaults, StyleCop):
 *   - types PascalCase; interfaces additionally I-prefixed
 *   - methods and properties PascalCase
 *   - public fields and constants PascalCase
 *   - private fields not snake_case (`_camelCase`/`camelCase` both accepted —
 *     the underscore prefix is a style choice, snake_case segments are not)
 * Deliberately NOT flagged: test method names (Save_WhenMissing_Throws),
 * event-handler names (saveButton_Click), explicit interface
 * implementations, extern/P-Invoke methods (names must match the native
 * export), and PascalCase private fields (legitimately contested).
 */
const TYPE_NODE_TYPES = new Set([
  'class_declaration',
  'struct_declaration',
  'record_declaration',
  'enum_declaration',
])

const NATIVE_INTEROP_ATTRIBUTES = new Set(['DllImport', 'LibraryImport'])

function pascalize(name: string): string {
  return name
    .replace(/^_+/, '')
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function fieldDeclaratorNames(field: SyntaxNode): SyntaxNode[] {
  const declaration = field.namedChildren.find((c) => c?.type === 'variable_declaration')
  if (!declaration) return []
  const names: SyntaxNode[] = []
  for (const declarator of declaration.namedChildren) {
    if (declarator?.type !== 'variable_declarator') continue
    const id = declarator.namedChildren[0]
    if (id?.type === 'identifier') names.push(id)
  }
  return names
}

export const csharpNamingConventionVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/csharp-naming-convention',
  languages: ['csharp'],
  nodeTypes: [
    'class_declaration',
    'struct_declaration',
    'record_declaration',
    'enum_declaration',
    'interface_declaration',
    'method_declaration',
    'property_declaration',
    'field_declaration',
  ],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null

    if (TYPE_NODE_TYPES.has(node.type)) {
      const name = node.childForFieldName('name')
      if (!name || isPascalCase(name.text)) return null
      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        'Type not in PascalCase',
        `Type '${name.text}' does not follow the .NET convention of PascalCase type names.`,
        sourceCode,
        `Rename to PascalCase: ${pascalize(name.text)}.`,
      )
    }

    if (node.type === 'interface_declaration') {
      const name = node.childForFieldName('name')
      if (!name) return null
      if (/^I[A-Z]/.test(name.text) && !name.text.includes('_')) return null
      const missingPrefix = !/^I[A-Z]/.test(name.text)
      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        missingPrefix ? 'Interface missing I prefix' : 'Interface not in PascalCase',
        missingPrefix
          ? `Interface '${name.text}' does not follow the .NET convention of an 'I' prefix (e.g. I${pascalize(name.text)}).`
          : `Interface '${name.text}' does not follow the .NET convention of I-prefixed PascalCase names.`,
        sourceCode,
        `Rename to I${pascalize(name.text.replace(/^I(?=[A-Z])/, ''))}.`,
      )
    }

    if (node.type === 'method_declaration') {
      const name = node.childForFieldName('name')
      if (!name) return null
      // Name dictated by the interface, not a style choice
      if (node.namedChildren.some((c) => c?.type === 'explicit_interface_specifier')) return null
      // P/Invoke entry points must match the native export name
      if (hasCSharpModifier(node, 'extern')) return null
      if (getCSharpAttributeNames(node).some((a) => NATIVE_INTEROP_ATTRIBUTES.has(a))) return null
      // Test naming (Save_WhenIdMissing_Throws) is its own convention
      if (isCSharpTestMethod(node)) return null

      if (!/^[a-z_]/.test(name.text)) return null
      // saveButton_Click — the WinForms/WPF event-handler convention
      if (/_[A-Z]/.test(name.text)) return null
      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        'Method not in PascalCase',
        `Method '${name.text}' does not follow the .NET convention of PascalCase method names.`,
        sourceCode,
        `Rename to PascalCase: ${pascalize(name.text)}.`,
      )
    }

    if (node.type === 'property_declaration') {
      const name = node.childForFieldName('name')
      if (!name) return null
      if (node.namedChildren.some((c) => c?.type === 'explicit_interface_specifier')) return null
      if (!/^[a-z_]/.test(name.text)) return null
      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        'Property not in PascalCase',
        `Property '${name.text}' does not follow the .NET convention of PascalCase property names.`,
        sourceCode,
        `Rename to PascalCase: ${pascalize(name.text)}.`,
      )
    }

    if (node.type === 'field_declaration') {
      const isConst = hasCSharpModifier(node, 'const')
      const isPublic = hasCSharpModifier(node, 'public')
      for (const name of fieldDeclaratorNames(node)) {
        if (isConst) {
          if (!/^[a-z_]/.test(name.text)) continue
          return makeViolation(
            this.ruleKey, name, filePath, 'low',
            'Constant not in PascalCase',
            `Constant '${name.text}' does not follow the .NET convention of PascalCase constant names.`,
            sourceCode,
            `Rename to PascalCase: ${pascalize(name.text)}.`,
          )
        }
        if (isPublic) {
          if (!/^[a-z_]/.test(name.text)) continue
          return makeViolation(
            this.ruleKey, name, filePath, 'low',
            'Public field not in PascalCase',
            `Public field '${name.text}' does not follow the .NET convention of PascalCase public members.`,
            sourceCode,
            `Rename to PascalCase: ${pascalize(name.text)} (or expose it as a property).`,
          )
        }
        // Non-public fields: _camelCase and camelCase are both accepted;
        // snake_case segments are not .NET style in any camp.
        const core = name.text.replace(/^_+/, '')
        if (core.includes('_')) {
          return makeViolation(
            this.ruleKey, name, filePath, 'low',
            'Field uses snake_case',
            `Field '${name.text}' uses snake_case. The .NET convention for private fields is _camelCase.`,
            sourceCode,
            `Rename to _${core.split('_').filter(Boolean).map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('')}.`,
          )
        }
      }
      return null
    }

    return null
  },
}
