import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile } from './_helpers.js'

/**
 * `scoped` is a modifier in newer C# (ref-safety: `scoped ref`).
 * Using it as a bare (untyped) parameter name in a PARENTHESIZED lambda
 * parameter list — `(scoped, x) => …` — is ambiguous with the modifier and a
 * forward-compatibility hazard; it must be escaped as `@scoped`.
 *
 * Only the untyped lambda-parameter case is flagged. A typed parameter
 * (`(int scoped)`) or a method parameter is unambiguously a name and left
 * alone.
 */
export const csharpScopedIdentifierEscapeVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/scoped-identifier-escape',
  languages: ['csharp'],
  nodeTypes: ['identifier'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null
    if (node.text !== 'scoped') return null

    const param = node.parent
    if (param?.type !== 'parameter') return null
    // Untyped lambda parameter: the identifier is the parameter's only content.
    if (param.namedChildCount !== 1) return null
    const list = param.parent
    if (list?.type !== 'parameter_list') return null
    if (list.parent?.type !== 'lambda_expression') return null

    return makeViolation(
      this.ruleKey, node, filePath, 'low',
      "Lambda parameter 'scoped' should be escaped",
      "'scoped' is a C# modifier; using it as a lambda parameter name is ambiguous and a forward-compatibility hazard.",
      sourceCode,
      "Escape the parameter as '@scoped' (or rename it).",
    )
  },
}
