import type { Node as SyntaxNode } from 'web-tree-sitter'
import type { CodeRuleVisitor } from '../../../types.js'
import { makeViolation } from '../../../types.js'
import { isAutoGeneratedCSharpFile } from './_helpers.js'

/**
 * CA1710 / CA1711 — types deriving from the framework base types
 * `Exception`, `EventArgs`, and `Attribute` should carry the matching name
 * suffix, the .NET convention that lets call sites recognize the kind at a
 * glance (`catch (FooException)`, `OrderPlacedEventArgs`, `[Required]Attribute`).
 *
 * Matched on the DIRECT base type by its simple name — a sound subset of the
 * Roslyn rule: a class written `: Exception` unambiguously IS an exception, so
 * there is no false positive. Indirect derivation (via an intermediate base)
 * needs type information and is left to the compiler analyzers.
 */
const SUFFIX_BY_BASE: Record<string, string> = {
  Exception: 'Exception',
  EventArgs: 'EventArgs',
  Attribute: 'Attribute',
}

function directBaseSimpleNames(classNode: SyntaxNode): string[] {
  const bases = classNode.namedChildren.find((c) => c?.type === 'base_list')
  if (!bases) return []
  const names: string[] = []
  for (const base of bases.namedChildren) {
    if (!base) continue
    const text = base.text
    // Drop any generic argument list and namespace qualification.
    const simple = text.replace(/<.*$/, '').split('.').pop() ?? ''
    if (simple) names.push(simple)
  }
  return names
}

export const csharpTypeNameSuffixConventionVisitor: CodeRuleVisitor = {
  ruleKey: 'style/deterministic/type-name-suffix-convention',
  languages: ['csharp'],
  nodeTypes: ['class_declaration'],
  visit(node, filePath, sourceCode) {
    if (isAutoGeneratedCSharpFile(sourceCode)) return null

    const name = node.childForFieldName('name')
    if (!name) return null

    for (const baseName of directBaseSimpleNames(node)) {
      const suffix = SUFFIX_BY_BASE[baseName]
      if (!suffix) continue
      if (name.text.endsWith(suffix)) return null
      // Exception types named `*Error` are owned by the more specific
      // code-quality/deterministic/error-instead-of-exception rule.
      if (suffix === 'Exception' && name.text.endsWith('Error')) return null

      return makeViolation(
        this.ruleKey, name, filePath, 'low',
        `Type should end with '${suffix}'`,
        `Type '${name.text}' derives from ${baseName} but its name does not end with '${suffix}'.`,
        sourceCode,
        `Rename to '${name.text}${suffix}'.`,
      )
    }

    return null
  },
}
