import type { AnalysisRule } from '@truecourse/shared'

export const CODE_RULES: AnalysisRule[] = [
  {
    key: 'code/empty-catch',
    category: 'code',
    name: 'Empty catch block',
    description: 'Empty catch blocks that swallow errors silently.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code/console-log',
    category: 'code',
    name: 'Console log in production code',
    description: 'console.log / console.debug calls in production code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code/hardcoded-secret',
    category: 'code',
    name: 'Hardcoded secret',
    description: 'String literals matching API key, token, or password patterns.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'code/todo-fixme',
    category: 'code',
    name: 'TODO/FIXME comment',
    description: 'TODO, FIXME, or HACK comments left in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'code/no-explicit-any',
    category: 'code',
    name: 'Explicit any type',
    description: 'TypeScript `: any` type annotations bypass type safety.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'code/sql-injection',
    category: 'code',
    name: 'Potential SQL injection',
    description: 'String concatenation or template literals in query/execute calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
