import type { Tree } from 'web-tree-sitter'
import type { AnalysisRule, CodeViolation, SupportedLanguage } from '@truecourse/shared'
import { walkAstWithVisitors, type CodeRuleVisitor } from './types.js'
import type { TypeQueryService } from '../ts-compiler.js'
import type { SchemaIndex } from '../services/schema-index.js'

// Import all domain visitors
import { SECURITY_JS_VISITORS } from './security/visitors/javascript/index.js'
import { SECURITY_PYTHON_VISITORS } from './security/visitors/python/index.js'
import { SECURITY_UNIVERSAL_VISITORS } from './security/visitors/universal.js'
import { BUGS_JS_VISITORS } from './bugs/visitors/javascript/index.js'
import { BUGS_PYTHON_VISITORS } from './bugs/visitors/python/index.js'
import { CODE_QUALITY_JS_VISITORS } from './code-quality/visitors/javascript/index.js'
import { CODE_QUALITY_PYTHON_VISITORS } from './code-quality/visitors/python/index.js'
import { CODE_QUALITY_UNIVERSAL_VISITORS } from './code-quality/visitors/universal.js'
import { PERFORMANCE_JS_VISITORS } from './performance/visitors/javascript/index.js'
import { PERFORMANCE_PYTHON_VISITORS } from './performance/visitors/python/index.js'
import { RELIABILITY_JS_VISITORS } from './reliability/visitors/javascript/index.js'
import { RELIABILITY_PYTHON_VISITORS } from './reliability/visitors/python/index.js'
import { STYLE_JS_VISITORS } from './style/visitors/javascript/index.js'
import { STYLE_PYTHON_VISITORS } from './style/visitors/python/index.js'
import { ARCHITECTURE_JS_VISITORS } from './architecture/visitors/javascript/index.js'
import { ARCHITECTURE_PYTHON_VISITORS } from './architecture/visitors/python/index.js'
import { DATABASE_JS_VISITORS } from './database/visitors/javascript/index.js'
import { DATABASE_PYTHON_VISITORS } from './database/visitors/python/index.js'
import { SECURITY_CSHARP_VISITORS } from './security/visitors/csharp/index.js'
import { BUGS_CSHARP_VISITORS } from './bugs/visitors/csharp/index.js'
import { CODE_QUALITY_CSHARP_VISITORS } from './code-quality/visitors/csharp/index.js'
import { PERFORMANCE_CSHARP_VISITORS } from './performance/visitors/csharp/index.js'
import { RELIABILITY_CSHARP_VISITORS } from './reliability/visitors/csharp/index.js'
import { STYLE_CSHARP_VISITORS } from './style/visitors/csharp/index.js'
import { ARCHITECTURE_CSHARP_VISITORS } from './architecture/visitors/csharp/index.js'
import { DATABASE_CSHARP_VISITORS } from './database/visitors/csharp/index.js'

export const ALL_CODE_VISITORS: CodeRuleVisitor[] = [
  ...SECURITY_JS_VISITORS,
  ...SECURITY_PYTHON_VISITORS,
  ...SECURITY_UNIVERSAL_VISITORS,
  ...BUGS_JS_VISITORS,
  ...BUGS_PYTHON_VISITORS,
  ...CODE_QUALITY_JS_VISITORS,
  ...CODE_QUALITY_PYTHON_VISITORS,
  ...CODE_QUALITY_UNIVERSAL_VISITORS,
  ...PERFORMANCE_JS_VISITORS,
  ...PERFORMANCE_PYTHON_VISITORS,
  ...RELIABILITY_JS_VISITORS,
  ...RELIABILITY_PYTHON_VISITORS,
  ...STYLE_JS_VISITORS,
  ...STYLE_PYTHON_VISITORS,
  ...ARCHITECTURE_JS_VISITORS,
  ...ARCHITECTURE_PYTHON_VISITORS,
  ...DATABASE_JS_VISITORS,
  ...DATABASE_PYTHON_VISITORS,
  ...SECURITY_CSHARP_VISITORS,
  ...BUGS_CSHARP_VISITORS,
  ...CODE_QUALITY_CSHARP_VISITORS,
  ...PERFORMANCE_CSHARP_VISITORS,
  ...RELIABILITY_CSHARP_VISITORS,
  ...STYLE_CSHARP_VISITORS,
  ...ARCHITECTURE_CSHARP_VISITORS,
  ...DATABASE_CSHARP_VISITORS,
]

/**
 * Returns true if any registered code visitor requires a TypeQueryService.
 * Used by the pipeline to decide whether to create the TypeScript program.
 */
export function hasTypeAwareVisitors(enabledRuleKeys: Set<string>): boolean {
  return ALL_CODE_VISITORS.some(
    (v) => v.needsTypeQuery && enabledRuleKeys.has(v.ruleKey),
  )
}

/**
 * Returns true if any registered code visitor requires a SchemaIndex.
 * Used by the pipeline to decide whether to build the schema index.
 */
export function hasSchemaAwareVisitors(enabledRuleKeys: Set<string>): boolean {
  return ALL_CODE_VISITORS.some(
    (v) => v.needsSchemaIndex && enabledRuleKeys.has(v.ruleKey),
  )
}

/**
 * Check all code-level rules by walking the AST and firing matching visitors.
 * This is a combined checker that runs security, bugs, and code-quality domain
 * visitors in a single AST pass for efficiency.
 *
 * Drop-in replacement for the old checkCodeRules function.
 */
// Tool-generated source: scaffolds regenerate it, so findings aren't
// actionable — every mainstream analyzer skips these. Detected by the
// standard filename conventions and the <auto-generated> header (within the
// leading comment block, typically line 1-2).
const GENERATED_FILE_SUFFIXES = ['.Designer.cs', '.designer.cs', '.g.cs', '.generated.cs', '.g.i.cs']

function isGeneratedSource(filePath: string, sourceCode: string): boolean {
  if (GENERATED_FILE_SUFFIXES.some((suffix) => filePath.endsWith(suffix))) return true
  return sourceCode.slice(0, 400).includes('<auto-generated')
}

export function checkCodeRules(
  tree: Tree,
  filePath: string,
  sourceCode: string,
  enabledRules: AnalysisRule[],
  language?: SupportedLanguage,
  typeQuery?: TypeQueryService,
  schemaIndex?: SchemaIndex,
): CodeViolation[] {
  const enabledKeys = new Set(
    enabledRules
      .filter((r) => r.type === 'deterministic' && r.enabled)
      .map((r) => r.key),
  )

  if (enabledKeys.size === 0) return []

  if (isGeneratedSource(filePath, sourceCode)) return []

  return walkAstWithVisitors(tree, filePath, sourceCode, ALL_CODE_VISITORS, enabledKeys, language, typeQuery, schemaIndex)
}
