import type { AnalysisRule } from '@truecourse/shared'

export const DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'arch/layer-violation-data-api',
    category: 'architecture',
    name: 'Data layer depends on API layer',
    description: 'Data layer should not import from the API layer.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'arch/layer-violation-external-api',
    category: 'architecture',
    name: 'External layer depends on API layer',
    description: 'External integrations should not depend on the API layer directly.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'arch/layer-violation-data-external',
    category: 'architecture',
    name: 'Data layer depends on external layer',
    description: 'Data layer should not call external services.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },

  // Module-level deterministic rules
  {
    key: 'arch/god-module',
    category: 'module',
    name: 'God module with too many methods',
    description: 'Class or module has too many methods (>15), suggesting too many responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'arch/long-method',
    category: 'module',
    name: 'Long method',
    description: 'Function has too many statements (>30), making it hard to understand.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/too-many-parameters',
    category: 'module',
    name: 'Too many parameters',
    description: 'Function has 5 or more parameters, suggesting it needs refactoring.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/deeply-nested-logic',
    category: 'module',
    name: 'Deeply nested logic',
    description: 'Function has excessive nesting depth (>4 levels), making it hard to follow.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'arch/unused-export',
    category: 'module',
    name: 'Unused export',
    description: 'Exported function or class not imported anywhere in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/dead-module',
    category: 'module',
    name: 'Dead module',
    description: 'Module has no incoming or outgoing dependencies — likely unused.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
