import type { AnalysisRule } from '@truecourse/shared'

export const DETERMINISTIC_RULES: AnalysisRule[] = [
  // Service-level deterministic rules
  {
    key: 'arch/circular-service-dependency',
    category: 'service',
    name: 'Circular service dependency',
    description: 'Two services depend on each other, creating a circular dependency.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
    isDependencyViolation: true,
  },
  {
    key: 'arch/god-service',
    category: 'service',
    name: 'God service',
    description: 'Service has too many files or spans too many layers, suggesting too many responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },

  // Module-level deterministic rules
  {
    key: 'arch/module-layer-data-api',
    category: 'module',
    name: 'Data layer depends on API layer',
    description: 'Data layer should not import from the API layer.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
    isDependencyViolation: true,
  },
  {
    key: 'arch/module-layer-external-api',
    category: 'module',
    name: 'External layer depends on API layer',
    description: 'External integrations should not depend on the API layer directly.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    isDependencyViolation: true,
  },
  {
    key: 'arch/module-layer-data-external',
    category: 'module',
    name: 'Data layer depends on external layer',
    description: 'Data layer should not call external services.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    isDependencyViolation: true,
  },
  {
    key: 'arch/cross-service-internal-import',
    category: 'module',
    name: 'Cross-service internal import',
    description: 'Module imports from another service\'s internal layer (data, service, external) instead of its API.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
    isDependencyViolation: true,
  },
  {
    key: 'arch/god-module',
    category: 'module',
    name: 'God module with too many methods',
    description: 'Class or module has too many methods (>15), suggesting too many responsibilities.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'arch/unused-export',
    category: 'module',
    name: 'Unused export',
    description: 'Exported function or class not imported anywhere in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/dead-module',
    category: 'module',
    name: 'Dead module',
    description: 'Module has no incoming or outgoing dependencies — likely unused.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/orphan-file',
    category: 'module',
    name: 'Orphan file',
    description: 'Source file is never imported by any other file in the codebase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },

  // Method-level deterministic rules
  {
    key: 'arch/long-method',
    category: 'method',
    name: 'Long method',
    description: 'Function has too many statements (>30), making it hard to understand.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/too-many-parameters',
    category: 'method',
    name: 'Too many parameters',
    description: 'Function has 5 or more parameters, suggesting it needs refactoring.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'arch/deeply-nested-logic',
    category: 'method',
    name: 'Deeply nested logic',
    description: 'Function has excessive nesting depth (>4 levels), making it hard to follow.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'arch/dead-method',
    category: 'method',
    name: 'Dead method',
    description: 'Method has no incoming or outgoing calls — likely unused.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
