import type { AnalysisRule } from '@truecourse/shared'

export const STYLE_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'style/deterministic/import-formatting',
    category: 'code',
    domain: 'style',
    name: 'Import not at top of file',
    description: 'Import statement found after non-import code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/implicit-string-concatenation',
    category: 'code',
    domain: 'style',
    name: 'Implicit string concatenation',
    description: 'Adjacent string literals implicitly concatenated without an operator.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/unnecessary-parentheses-style',
    category: 'code',
    domain: 'style',
    name: 'Unnecessary parentheses',
    description: 'Extra parentheses around return value or simple expressions.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/comment-tag-formatting',
    category: 'code',
    domain: 'style',
    name: 'Malformed TODO/FIXME comment',
    description: 'TODO/FIXME comment without colon or description (e.g., "TODO fix this" instead of "TODO: fix this").',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/pytest-decorator-style',
    category: 'code',
    domain: 'style',
    name: 'Incorrect pytest decorator usage',
    description: 'pytest decorator used incorrectly (e.g., @pytest.fixture without parentheses when needed).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/js-style-preference',
    category: 'code',
    domain: 'style',
    name: 'JS style issue',
    description: 'JavaScript style inconsistency (e.g., var instead of const/let).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/ts-declaration-style',
    category: 'code',
    domain: 'style',
    name: 'TS declaration style',
    description: 'TypeScript declaration style issue (e.g., interface vs type alias for object shapes).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/sorting-style',
    category: 'code',
    domain: 'style',
    name: 'Unsorted imports',
    description: 'Import statements not sorted alphabetically.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/python-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'Python naming convention violation',
    description: 'Python function/variable not in snake_case or class not in PascalCase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/js-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'JS naming convention violation',
    description: 'JS/TS function not in camelCase or class not in PascalCase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/docstring-completeness',
    category: 'code',
    domain: 'style',
    name: 'Missing or incomplete docstring',
    description: 'Public function or class missing a docstring.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/python-minor-style-preference',
    category: 'code',
    domain: 'style',
    name: 'Python minor style issue',
    description: 'Python minor style preference (e.g., missing trailing comma in multi-line collections).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/whitespace-formatting',
    category: 'code',
    domain: 'style',
    name: 'Inconsistent whitespace',
    description: 'Mixed tabs and spaces or trailing whitespace detected.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
