import type { AnalysisRule } from '@truecourse/shared'

export const STYLE_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'style/deterministic/import-formatting',
    category: 'code',
    domain: 'style',
    name: 'Import not at top of file',
    description: 'Import statement found after non-import code.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/implicit-string-concatenation',
    category: 'code',
    domain: 'style',
    name: 'Implicit string concatenation',
    description: 'Adjacent string literals implicitly concatenated without an operator.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/unnecessary-parentheses-style',
    category: 'code',
    domain: 'style',
    name: 'Unnecessary parentheses',
    description: 'Extra parentheses around return value or simple expressions.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/comment-tag-formatting',
    category: 'code',
    domain: 'style',
    name: 'Malformed TODO/FIXME comment',
    description: 'TODO/FIXME comment without colon or description (e.g., "TODO fix this" instead of "TODO: fix this").',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/pytest-decorator-style',
    category: 'code',
    domain: 'style',
    name: 'Incorrect pytest decorator usage',
    description: 'pytest decorator used incorrectly (e.g., @pytest.fixture without parentheses when needed).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/js-style-preference',
    category: 'code',
    domain: 'style',
    name: 'JS style issue',
    description: 'JavaScript style inconsistency (e.g., var instead of const/let).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/ts-declaration-style',
    category: 'code',
    domain: 'style',
    name: 'TS declaration style',
    description: 'TypeScript declaration style issue (e.g., interface vs type alias for object shapes).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/sorting-style',
    category: 'code',
    domain: 'style',
    name: 'Unsorted imports',
    description: 'Import statements not sorted alphabetically.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/python-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'Python naming convention violation',
    description: 'Python function/variable not in snake_case or class not in PascalCase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/js-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'JS naming convention violation',
    description: 'JS/TS function not in camelCase or class not in PascalCase.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/csharp-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'C# naming convention violation',
    description: 'Type/method/property not in PascalCase, interface missing I prefix, or snake_case private field.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/docstring-completeness',
    category: 'code',
    domain: 'style',
    name: 'Missing or incomplete docstring',
    description: 'Public function or class missing a docstring.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/python-minor-style-preference',
    category: 'code',
    domain: 'style',
    name: 'Python minor style issue',
    description: 'Python minor style preference (e.g., missing trailing comma in multi-line collections).',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/whitespace-formatting',
    category: 'code',
    domain: 'style',
    name: 'Inconsistent whitespace',
    description: 'Mixed tabs and spaces or trailing whitespace detected.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/builtin-type-alias',
    category: 'code',
    domain: 'style',
    name: 'Use the built-in type alias',
    description:
      'A basic .NET type is referenced by its framework name (e.g. Int32, String) instead of the C# language alias (int, string); the alias is the idiomatic form.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/enum-name-redundant-suffix',
    category: 'code',
    domain: 'style',
    name: 'Enum names should not have Flags or Enum suffixes',
    description: 'Flags enum type names ending in "Flags" or "Enum", which restate the kind redundantly.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/enum-naming-convention',
    category: 'code',
    domain: 'style',
    name: 'Enumeration types should follow a naming convention',
    description: 'Flags enum members that do not follow the .NET PascalCase naming convention.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/field-keyword-conflict',
    category: 'code',
    domain: 'style',
    name: 'Identifiers should not conflict with the C# 14 field keyword',
    description: 'Flags identifiers named field that will collide with the new contextual keyword, a forward-compatibility hazard.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/flags-enum-zero-not-none',
    category: 'code',
    domain: 'style',
    name: 'Flags enum zero-value member should be named None',
    description: 'Flags a [Flags] enum whose 0 member is not named None, which reads poorly in bitwise combinations.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/logger-field-naming',
    category: 'code',
    domain: 'style',
    name: 'Logger fields should follow a naming convention',
    description: 'Flags logger fields/properties whose names do not follow the .NET logging naming convention.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/scoped-identifier-escape',
    category: 'code',
    domain: 'style',
    name: 'scoped should be escaped when used as an identifier in lambda parameters',
    description: 'Flags scoped used as an identifier in a parenthesized lambda parameter list, which newer C# treats as a modifier.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'style/deterministic/type-name-suffix-convention',
    category: 'code',
    domain: 'style',
    name: 'Attribute, EventArgs, and Exception types should end with the matching suffix',
    description: 'Flags types deriving from Attribute/EventArgs/Exception whose names do not end with the expected suffix.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
