import type { AnalysisRule } from '@truecourse/shared'

export const PERFORMANCE_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'performance/deterministic/inline-function-in-jsx-prop',
    category: 'code',
    domain: 'performance',
    name: 'Inline function in JSX prop',
    description: 'Arrow function or .bind() in JSX props causes new reference every render, defeating React.memo.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/inline-object-in-jsx-prop',
    category: 'code',
    domain: 'performance',
    name: 'Inline object in JSX prop',
    description: 'Object or array literal in JSX prop creates a new reference every render.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/regex-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'Regex created inside loop',
    description: 'Creating a RegExp inside a loop body recompiles the pattern on every iteration.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/spread-in-reduce',
    category: 'code',
    domain: 'performance',
    name: 'Spread operator in reduce callback',
    description: 'Using object/array spread in reduce creates O(n^2) copies.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/sync-fs-in-request-handler',
    category: 'code',
    domain: 'performance',
    name: 'Synchronous filesystem call in async context',
    description: 'Synchronous fs methods block the event loop in async functions or request handlers.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/missing-cleanup-useeffect',
    category: 'code',
    domain: 'performance',
    name: 'useEffect missing cleanup',
    description: 'useEffect with addEventListener/setInterval/setTimeout but no cleanup return causes memory leaks.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/event-listener-no-remove',
    category: 'code',
    domain: 'performance',
    name: 'addEventListener without removeEventListener',
    description: 'Adding an event listener without a corresponding removal can cause memory leaks.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/large-bundle-import',
    category: 'code',
    domain: 'performance',
    name: 'Large bundle import',
    description: 'Importing an entire large library when a subpath import would reduce bundle size.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/json-parse-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'JSON.parse/stringify in loop',
    description: 'JSON.parse() or JSON.stringify() inside a loop body is expensive per iteration.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/state-update-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'React state update in loop',
    description: 'Calling a React setState/useState setter inside a loop triggers multiple re-renders.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
]
