import type { AnalysisRule } from '@truecourse/shared'

export const PERFORMANCE_DETERMINISTIC_RULES: AnalysisRule[] = [
  // ---- C# semantic rules (Roslyn host) -------------------------------------
  {
    key: 'performance/deterministic/count-instead-of-any',
    category: 'code',
    domain: 'performance',
    name: 'Count used where Any suffices',
    description:
      'Count()/LongCount() is compared against zero where Any() short-circuits on the first element instead of enumerating the whole sequence.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/any-over-count-check',
    category: 'code',
    domain: 'performance',
    name: 'Any() used for emptiness check',
    description:
      'Any() builds an enumerator to test emptiness on a type with a cheap Count/Length/IsEmpty — use that property instead.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-array-find',
    category: 'code',
    domain: 'performance',
    name: 'Find should be used instead of FirstOrDefault on arrays',
    description:
      'FirstOrDefault(predicate) on an array/List allocates a LINQ enumerator where the type’s own Find avoids it.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-exists',
    category: 'code',
    domain: 'performance',
    name: 'Exists should be used instead of the Any extension',
    description:
      'The LINQ Any(predicate) extension on a List/array allocates an enumerator where the collection’s own Exists is cheaper.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-trueforall',
    category: 'code',
    domain: 'performance',
    name: 'TrueForAll should be used instead of the All extension',
    description:
      'The LINQ All extension on a List/array allocates an enumerator where the collection’s own TrueForAll avoids it.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-indexing-over-linq',
    category: 'code',
    domain: 'performance',
    name: 'Prefer indexing over Enumerable methods on IList',
    description:
      'First()/Last()/ElementAt on an indexable list enumerates from the start, where direct indexing avoids enumeration.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-linkedlist-first-last',
    category: 'code',
    domain: 'performance',
    name: 'First and Last properties of LinkedList should be preferred',
    description:
      'First()/Last() LINQ extensions on a LinkedList walk the list, where the O(1) First/Last properties exist.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-set-minmax-property',
    category: 'code',
    domain: 'performance',
    name: 'Min/Max properties of sorted sets should be used over the Enumerable extension',
    description:
      'Min()/Max() LINQ calls on a SortedSet scan the whole set, where the type’s O(1) Min/Max properties exist.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/multiple-orderby',
    category: 'code',
    domain: 'performance',
    name: 'Multiple OrderBy calls should not be chained',
    description: 'A second OrderBy discards the first ordering; ThenBy/ThenByDescending was intended.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/empty-string-compared-with-equals',
    category: 'code',
    domain: 'performance',
    name: 'Empty-string test via equality',
    description:
      'A string is tested for emptiness by comparing to "" where checking Length == 0 or string.IsNullOrEmpty is faster.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/startswith-over-indexof-zero',
    category: 'code',
    domain: 'performance',
    name: 'StartsWith over IndexOf==0',
    description: 'A prefix check written as IndexOf(prefix)==0 scans the whole string where StartsWith stops at the first mismatch.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/string-contains-char',
    category: 'code',
    domain: 'performance',
    name: 'String.Contains with single-char string',
    description: 'string.Contains is called with a one-character string literal where the char overload avoids substring searching.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/prefer-char-overload',
    category: 'code',
    domain: 'performance',
    name: 'Use char overload for single char',
    description: 'StartsWith/EndsWith is called with a single-character string literal where a char overload performs better.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/string-concat-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'Strings should not be concatenated with + in a loop',
    description: 'Repeated string += inside a loop allocates quadratically; use StringBuilder.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/use-span-string-concat',
    category: 'code',
    domain: 'performance',
    name: 'Use span-based string.Concat',
    description: 'A string is built by concatenating Substring results, where AsSpan with string.Concat avoids intermediate allocations.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/redundant-contains-before-set-op',
    category: 'code',
    domain: 'performance',
    name: 'Redundant Contains before Add/Remove',
    description:
      'A set Add or Remove is guarded by a Contains check, but both return a bool and perform the lookup themselves, making the guard a wasted lookup.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/value-type-without-iequatable',
    category: 'code',
    domain: 'performance',
    name: 'Value types should implement IEquatable<T>',
    description:
      'A struct overrides Equals but does not implement IEquatable<T>, so equality boxes and falls back to reflection-based ValueType.Equals.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/non-derived-private-class-not-sealed',
    category: 'code',
    domain: 'performance',
    name: 'Non-derived private classes should be sealed',
    description:
      'A private/file-scoped class that is never subclassed could be sealed for clarity and a small dispatch win.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/concurrentdictionary-captures-argument',
    category: 'code',
    domain: 'performance',
    name: 'The lambda parameter should be used instead of capturing in ConcurrentDictionary methods',
    description:
      'GetOrAdd/AddOrUpdate factory lambdas that capture an enclosing variable instead of using the provided state parameter allocate a closure per call.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/uncached-searchvalues',
    category: 'code',
    domain: 'performance',
    name: 'Uncached SearchValues',
    description: 'Values are passed directly to IndexOfAny/ContainsAny where a cached SearchValues instance is more efficient.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
    engine: 'roslyn-host',
  },
  {
    key: 'performance/deterministic/inline-function-in-jsx-prop',
    category: 'code',
    domain: 'performance',
    name: 'Inline function in JSX prop',
    description: 'Arrow function or .bind() in JSX props causes new reference every render, defeating React.memo.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/inline-object-in-jsx-prop',
    category: 'code',
    domain: 'performance',
    name: 'Inline object in JSX prop',
    description: 'Object or array literal in JSX prop creates a new reference every render.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/regex-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'Regex created inside loop',
    description: 'Creating a RegExp inside a loop body recompiles the pattern on every iteration.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/spread-in-reduce',
    category: 'code',
    domain: 'performance',
    name: 'Spread operator in reduce callback',
    description: 'Using object/array spread in reduce creates O(n^2) copies.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/sync-fs-in-request-handler',
    category: 'code',
    domain: 'performance',
    name: 'Synchronous filesystem call in async context',
    description: 'Synchronous fs methods block the event loop in async functions or request handlers.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/missing-cleanup-useeffect',
    category: 'code',
    domain: 'performance',
    name: 'useEffect missing cleanup',
    description: 'useEffect with addEventListener/setInterval/setTimeout but no cleanup return causes memory leaks.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/event-listener-no-remove',
    category: 'code',
    domain: 'performance',
    name: 'addEventListener without removeEventListener',
    description: 'Adding an event listener without a corresponding removal can cause memory leaks.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/large-bundle-import',
    category: 'code',
    domain: 'performance',
    name: 'Large bundle import',
    description: 'Importing an entire large library when a subpath import would reduce bundle size.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/json-parse-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'JSON.parse/stringify in loop',
    description: 'JSON.parse() or JSON.stringify() inside a loop body is expensive per iteration.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/state-update-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'React state update in loop',
    description: 'Calling a React setState/useState setter inside a loop triggers multiple re-renders.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },

  // --- JS/TS rules (new) ---
  {
    key: 'performance/deterministic/settimeout-setinterval-no-clear',
    category: 'code',
    domain: 'performance',
    name: 'setTimeout/setInterval without clear',
    description: 'setTimeout/setInterval called without storing the return value for later clearTimeout/clearInterval.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/unbounded-array-growth',
    category: 'code',
    domain: 'performance',
    name: 'Unbounded array growth',
    description: 'Array.push() in a loop or interval without bounds checking can cause memory issues.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/missing-usememo-expensive',
    category: 'code',
    domain: 'performance',
    name: 'Expensive computation without useMemo',
    description: 'Expensive computation (sort, filter, map, reduce) in render without useMemo causes recalculation every render.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/synchronous-crypto',
    category: 'code',
    domain: 'performance',
    name: 'Synchronous crypto operation in async context',
    description: 'crypto.pbkdf2Sync or crypto.scryptSync blocks the event loop in async contexts.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/missing-react-memo',
    category: 'code',
    domain: 'performance',
    name: 'Component without React.memo',
    description: 'Component receiving only primitive or stable props without React.memo may re-render unnecessarily.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/unnecessary-context-provider',
    category: 'code',
    domain: 'performance',
    name: 'Context provider wrapping single child',
    description: 'React Context provider wrapping only a single child component may be unnecessary.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/sync-require-in-handler',
    category: 'code',
    domain: 'performance',
    name: 'Synchronous require() in request handler',
    description: 'require() inside a request handler blocks the event loop on first call.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },

  // --- Python rules ---
  {
    key: 'performance/deterministic/quadratic-list-summation',
    category: 'code',
    domain: 'performance',
    name: 'String concatenation with += in loop',
    description: 'Building a string with += in a loop creates O(n^2) copies.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/str-replace-over-re-sub',
    category: 'code',
    domain: 'performance',
    name: 're.sub() for simple string replace',
    description: 're.sub() used with a plain string pattern that could use str.replace().',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/unnecessary-iterable-allocation',
    category: 'code',
    domain: 'performance',
    name: 'Unnecessary list() in for loop',
    description: 'list() wrapping a generator in a for loop creates an unnecessary intermediate list.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/sorted-for-min-max',
    category: 'code',
    domain: 'performance',
    name: 'sorted() for min/max',
    description: 'sorted(list)[0] or sorted(list)[-1] is O(n log n) when min()/max() is O(n).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/list-comprehension-in-any-all',
    category: 'code',
    domain: 'performance',
    name: 'List comprehension in any()/all()',
    description: 'List comprehension inside any()/all() prevents short-circuit evaluation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/unnecessary-list-cast',
    category: 'code',
    domain: 'performance',
    name: 'Unnecessary list() around list comprehension',
    description: 'list([...]) is redundant — list comprehension already returns a list.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/incorrect-dict-iterator',
    category: 'code',
    domain: 'performance',
    name: 'Incorrect dict iterator',
    description: 'Iterating .keys() but accessing values by key. Use .items() instead.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/try-except-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'try/except inside loop',
    description: 'try/except inside a tight loop adds overhead per iteration.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/manual-list-comprehension',
    category: 'code',
    domain: 'performance',
    name: 'Manual list building instead of comprehension',
    description: 'For loop with single .append() call can be replaced with a list comprehension.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/torch-dataloader-num-workers',
    category: 'code',
    domain: 'performance',
    name: 'DataLoader with num_workers=0',
    description: 'PyTorch DataLoader with num_workers=0 loads data in main process, bottlenecking training.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/missing-slots-in-subclass',
    category: 'code',
    domain: 'performance',
    name: 'Subclass missing __slots__',
    description: 'Subclass of a __slots__ class missing its own __slots__ negates memory savings.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/batch-writes-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'Database write inside loop',
    description: 'Individual database writes inside a loop instead of batch operations.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/set-mutations-in-loop',
    category: 'code',
    domain: 'performance',
    name: 'set.add() in loop',
    description: 'set.add() in a loop with single elements can be replaced with set.update() or comprehension.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/runtime-cast-overhead',
    category: 'code',
    domain: 'performance',
    name: 'Type casting in loop',
    description: 'Type casting function called inside a loop adds per-iteration overhead.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/explicit-gc-collect',
    category: 'code',
    domain: 'performance',
    name: 'GC.Collect should not be called',
    description: 'GC.Collect() forces a costly full collection that pre-empts the runtime’s adaptive schedule and usually hurts throughput.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/get-executing-assembly',
    category: 'code',
    domain: 'performance',
    name: 'Assembly.GetExecutingAssembly should not be called',
    description: 'Assembly.GetExecutingAssembly() walks the stack to find the calling assembly; typeof(T).Assembly is a direct metadata read.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/zero-length-array-allocation',
    category: 'code',
    domain: 'performance',
    name: 'Zero-length array allocation',
    description: 'new T[0] allocates a fresh empty array every time; Array.Empty<T>() returns a shared cached instance.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/multidimensional-array',
    category: 'code',
    domain: 'performance',
    name: 'Multidimensional array',
    description: 'A rectangular multidimensional array (T[,]) is bounds-checked per access and rarely intended; prefer a jagged array or collection.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/whenall-single-task',
    category: 'code',
    domain: 'performance',
    name: 'WhenAll with a single task',
    description: 'Task.WhenAll with one task allocates an array and a combined task to await a task that can be awaited directly.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/waitall-single-task',
    category: 'code',
    domain: 'performance',
    name: 'WaitAll with a single task',
    description: 'Task.WaitAll with one task routes a single wait through the array-based combinator, adding overhead.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/use-currentmanagedthreadid',
    category: 'code',
    domain: 'performance',
    name: 'Use Environment.CurrentManagedThreadId',
    description: 'Thread.CurrentThread.ManagedThreadId resolves the Thread object to read its id; Environment.CurrentManagedThreadId reads it directly.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/use-environment-processid',
    category: 'code',
    domain: 'performance',
    name: 'Use Environment.ProcessId',
    description: 'Process.GetCurrentProcess().Id creates a disposable Process object just to read the process id; Environment.ProcessId is direct.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/use-environment-processpath',
    category: 'code',
    domain: 'performance',
    name: 'Use Environment.ProcessPath',
    description: 'Process.GetCurrentProcess().MainModule.FileName creates a disposable Process object just to read the executable path; Environment.ProcessPath is direct.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/nested-path-combine',
    category: 'code',
    domain: 'performance',
    name: 'Nested Path.Combine/Join',
    description: 'Nested Path.Combine/Join calls can be collapsed into a single call for one allocation.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-regex-ismatch',
    category: 'code',
    domain: 'performance',
    name: 'Prefer Regex.IsMatch',
    description: 'Regex.Match(...).Success materializes a Match only to read a boolean; Regex.IsMatch returns it directly.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-regex-count',
    category: 'code',
    domain: 'performance',
    name: 'Prefer Regex.Count',
    description: 'Regex.Matches(...).Count materializes the whole MatchCollection only to count it; Regex.Count avoids the allocation.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/jsondocument-rootelement',
    category: 'code',
    domain: 'performance',
    name: 'JsonDocument.Parse().RootElement',
    description: 'JsonDocument.Parse(...).RootElement leaks the document’s pooled buffer; JsonElement.Parse reads the value without that lifetime.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/redundant-containskey-before-remove',
    category: 'code',
    domain: 'performance',
    name: 'Redundant ContainsKey before Remove',
    description: 'Dictionary.Remove already handles the missing-key case, so a guarding ContainsKey is a wasted second lookup.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-tryadd',
    category: 'code',
    domain: 'performance',
    name: 'Prefer TryAdd over ContainsKey + Add',
    description: 'Guarding Dictionary.Add with !ContainsKey does two lookups; TryAdd adds-if-absent in a single lookup.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/tolower-for-comparison',
    category: 'code',
    domain: 'performance',
    name: 'ToLower/ToUpper for case-insensitive compare',
    description: 'Lowercasing both operands to compare case-insensitively allocates throwaway strings; a StringComparison overload compares in place.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/use-tohexstring',
    category: 'code',
    domain: 'performance',
    name: 'Use Convert.ToHexString',
    description: 'Hex-encoding via BitConverter.ToString(...).Replace(...) allocates several intermediate strings; Convert.ToHexString is direct.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/local-jsonserializeroptions',
    category: 'code',
    domain: 'performance',
    name: 'Local JsonSerializerOptions instance',
    description: 'Constructing a new JsonSerializerOptions at each serialize/deserialize call defeats the metadata cache; reuse a single instance.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/filter-before-sort',
    category: 'code',
    domain: 'performance',
    name: 'Filter the collection before sorting',
    description: 'OrderBy followed by Where sorts elements that the filter then discards; applying Where first sorts a smaller sequence.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/countasync-instead-of-anyasync',
    category: 'code',
    domain: 'performance',
    name: 'CountAsync used where AnyAsync suffices',
    description: 'Comparing CountAsync() against zero counts every matching row to answer an existence question that AnyAsync() short-circuits.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-contains-over-any',
    category: 'code',
    domain: 'performance',
    name: 'Contains should be used instead of Any for equality checks',
    description: 'Any(x => x == value) allocates a delegate and runs a per-element predicate where Contains(value) is clearer and faster.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-char-startswith-endswith',
    category: 'code',
    domain: 'performance',
    name: 'Use the char overload of StartsWith / EndsWith',
    description: 'StartsWith/EndsWith with a one-character string uses the culture-aware string path; the char overload does an ordinal check.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/stringbuilder-append-single-char-string',
    category: 'code',
    domain: 'performance',
    name: 'StringBuilder.Append with a single-character string',
    description: 'Appending a one-character string goes through the string overload; the char overload avoids the string handling.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/stringbuilder-tostring-append',
    category: 'code',
    domain: 'performance',
    name: 'StringBuilder.Append(x.ToString())',
    description: 'Calling ToString() before Append allocates an intermediate string; Append has typed overloads that format straight into the buffer.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/redundant-stringbuilder-tostring',
    category: 'code',
    domain: 'performance',
    name: 'Optimize StringBuilder.Append call',
    description: 'Passing a concatenated string to Append builds the whole string on the heap first, defeating the StringBuilder.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/span-fill-default-over-clear',
    category: 'code',
    domain: 'performance',
    name: 'Span.Fill(default) over Clear',
    description: 'Fill(default) writes the default value into every element; Clear() zeroes the whole span in one operation.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/prefer-trygetvalue',
    category: 'code',
    domain: 'performance',
    name: 'Prefer TryGetValue over ContainsKey + indexer',
    description: 'Guarding an indexer read with ContainsKey looks the key up twice; TryGetValue does it in a single lookup.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/stringbuilder-pinvoke-parameter',
    category: 'code',
    domain: 'performance',
    name: 'StringBuilder parameter on a P/Invoke',
    description: 'A StringBuilder parameter on a P/Invoke always marshals through a copied native buffer; a char span/buffer avoids the copy.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/property-returns-collection-copy',
    category: 'code',
    domain: 'performance',
    name: 'Property returns a collection copy',
    description: 'A property getter returning ToArray()/ToList() allocates a fresh copy on every access — a hidden O(n) cost callers do not expect.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'performance/deterministic/constant-array-argument',
    category: 'code',
    domain: 'performance',
    name: 'Constant array passed as argument',
    description: 'A constant array literal passed as an argument is re-allocated on every call; a static readonly field allocates it once.',
    enabled: true,
    severity: 'low',
    type: 'deterministic',
  },
]
