import type { AnalysisRule } from '@truecourse/shared'

export const DATABASE_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'database/deterministic/missing-transaction',
    category: 'code',
    domain: 'database',
    name: 'Multiple writes without transaction',
    description: 'Multiple related INSERT/UPDATE/DELETE calls that should be atomic but are not wrapped in a transaction.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/unvalidated-external-data',
    category: 'code',
    domain: 'database',
    name: 'Unvalidated external data used in query',
    description: 'Data from API response, file, or message queue used directly in a database query without schema validation.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/missing-unique-constraint',
    category: 'code',
    domain: 'database',
    name: 'Duplicate prevention via application code only',
    description: 'Uniqueness enforced in application code but not in database schema — race conditions can create duplicates.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/unsafe-delete-without-where',
    category: 'code',
    domain: 'database',
    name: 'DELETE/UPDATE without WHERE clause',
    description: 'SQL DELETE or UPDATE statement without WHERE condition — affects all rows in table.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/select-star',
    category: 'code',
    domain: 'database',
    name: 'SELECT * in production code',
    description: 'Fetching all columns when only a subset is needed — wastes bandwidth and prevents index-only scans.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/missing-migration',
    category: 'code',
    domain: 'database',
    name: 'Schema change without migration file',
    description: 'Direct ALTER TABLE or schema modification not captured in a migration system.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/connection-not-released',
    category: 'code',
    domain: 'database',
    name: 'Database connection not released',
    description: 'Connection acquired from pool but not released in a finally/using block — can exhaust connection pool.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'database/deterministic/orm-lazy-load-in-loop',
    category: 'code',
    domain: 'database',
    name: 'ORM lazy loading in loop',
    description: 'Accessing ORM relationship inside a loop triggers one query per iteration — N+1 pattern.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
