import type { AnalysisRule } from '@truecourse/shared'

export const SECURITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'security/deterministic/sql-injection',
    category: 'code',
    domain: 'security',
    name: 'Potential SQL injection',
    description: 'String interpolation or concatenation in database query calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-secret',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded secret',
    description: 'String literals matching API key, token, or password patterns.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/eval-usage',
    category: 'code',
    domain: 'security',
    name: 'Dynamic code evaluation',
    description: 'Use of eval(), exec(), or equivalent dynamic code execution.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/os-command-injection',
    category: 'code',
    domain: 'security',
    name: 'OS command injection',
    description: 'Shell command execution with potentially dynamic input.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-hashing',
    category: 'code',
    domain: 'security',
    name: 'Weak hashing algorithm',
    description: 'Use of MD5 or SHA1 which are cryptographically weak.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-ip',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded IP address',
    description: 'Hardcoded IPv4 addresses in string literals.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/clear-text-protocol',
    category: 'code',
    domain: 'security',
    name: 'Clear-text protocol',
    description: 'Use of unencrypted protocols (http://, ftp://, telnet://).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-certificate',
    category: 'code',
    domain: 'security',
    name: 'Unverified TLS certificate',
    description: 'Disabled TLS certificate verification.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/permissive-cors',
    category: 'code',
    domain: 'security',
    name: 'Permissive CORS configuration',
    description: 'Wildcard CORS origin allowing any domain.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-cookie',
    category: 'code',
    domain: 'security',
    name: 'Insecure cookie',
    description: 'Cookie set without the secure flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/cookie-without-httponly',
    category: 'code',
    domain: 'security',
    name: 'Cookie without httpOnly',
    description: 'Cookie set without the httpOnly flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/disabled-auto-escaping',
    category: 'code',
    domain: 'security',
    name: 'Disabled auto-escaping',
    description: 'Template engine with auto-escaping disabled, risking XSS.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/csrf-disabled',
    category: 'code',
    domain: 'security',
    name: 'CSRF protection disabled',
    description: 'Disabling CSRF protection in framework configuration.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-cipher',
    category: 'code',
    domain: 'security',
    name: 'Weak cipher algorithm',
    description: 'Use of weak ciphers such as DES, RC4, or Blowfish.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-crypto-key',
    category: 'code',
    domain: 'security',
    name: 'Weak cryptographic key size',
    description: 'RSA key smaller than 2048 bits or EC key smaller than 256 bits.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-ssl',
    category: 'code',
    domain: 'security',
    name: 'Weak SSL/TLS protocol',
    description: 'Use of deprecated SSL/TLS protocols (SSLv2, SSLv3, TLS 1.0).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-jwt',
    category: 'code',
    domain: 'security',
    name: 'Insecure JWT configuration',
    description: 'JWT signed with none algorithm or other weak algorithm.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/encryption-insecure-mode',
    category: 'code',
    domain: 'security',
    name: 'Insecure encryption mode',
    description: 'Use of ECB mode which does not provide semantic security.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-content-security-policy',
    category: 'code',
    domain: 'security',
    name: 'Missing Content Security Policy',
    description: 'Helmet or Express configured without Content Security Policy.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-frame-ancestors',
    category: 'code',
    domain: 'security',
    name: 'Missing frame ancestors protection',
    description: 'Missing X-Frame-Options or frame-ancestors CSP directive.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-strict-transport',
    category: 'code',
    domain: 'security',
    name: 'Missing HSTS',
    description: 'Helmet configured with HSTS disabled.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-referrer-policy',
    category: 'code',
    domain: 'security',
    name: 'Missing referrer policy',
    description: 'Helmet configured with referrer policy disabled.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-mime-sniff-protection',
    category: 'code',
    domain: 'security',
    name: 'Missing MIME sniff protection',
    description: 'Helmet configured with X-Content-Type-Options (noSniff) disabled.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/server-fingerprinting',
    category: 'code',
    domain: 'security',
    name: 'Server fingerprinting',
    description: 'X-Powered-By header not disabled, leaking server technology.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-hostname',
    category: 'code',
    domain: 'security',
    name: 'Unverified hostname',
    description: 'Disabled hostname verification in TLS connections.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/xml-xxe',
    category: 'code',
    domain: 'security',
    name: 'XML external entity injection',
    description: 'XML parsing without disabling external entities.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unsafe-unzip',
    category: 'code',
    domain: 'security',
    name: 'Unsafe archive extraction',
    description: 'Extracting archives without controlling resource consumption (zip bomb risk).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
