import type { AnalysisRule } from '@truecourse/shared'

export const SECURITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'security/deterministic/sql-injection',
    category: 'code',
    domain: 'security',
    name: 'Potential SQL injection',
    description: 'String interpolation or concatenation in database query calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-secret',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded secret',
    description: 'String literals matching API key, token, or password patterns.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/eval-usage',
    category: 'code',
    domain: 'security',
    name: 'Dynamic code evaluation',
    description: 'Use of eval(), exec(), or equivalent dynamic code execution.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/os-command-injection',
    category: 'code',
    domain: 'security',
    name: 'OS command injection',
    description: 'Shell command execution with potentially dynamic input.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-hashing',
    category: 'code',
    domain: 'security',
    name: 'Weak hashing algorithm',
    description: 'Use of MD5 or SHA1 which are cryptographically weak.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-ip',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded IP address',
    description: 'Hardcoded IPv4 addresses in string literals.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/clear-text-protocol',
    category: 'code',
    domain: 'security',
    name: 'Clear-text protocol',
    description: 'Use of unencrypted protocols (http://, ftp://, telnet://).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-certificate',
    category: 'code',
    domain: 'security',
    name: 'Unverified TLS certificate',
    description: 'Disabled TLS certificate verification.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/permissive-cors',
    category: 'code',
    domain: 'security',
    name: 'Permissive CORS configuration',
    description: 'Wildcard CORS origin allowing any domain.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-cookie',
    category: 'code',
    domain: 'security',
    name: 'Insecure cookie',
    description: 'Cookie set without the secure flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/cookie-without-httponly',
    category: 'code',
    domain: 'security',
    name: 'Cookie without httpOnly',
    description: 'Cookie set without the httpOnly flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/disabled-auto-escaping',
    category: 'code',
    domain: 'security',
    name: 'Disabled auto-escaping',
    description: 'Template engine with auto-escaping disabled, risking XSS.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
