import type { AnalysisRule } from '@truecourse/shared'

export const SECURITY_DETERMINISTIC_RULES: AnalysisRule[] = [
  {
    key: 'security/deterministic/sql-injection',
    category: 'code',
    domain: 'security',
    name: 'Potential SQL injection',
    description: 'String interpolation or concatenation in database query calls.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-secret',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded secret',
    description: 'String literals matching API key, token, or password patterns.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/eval-usage',
    category: 'code',
    domain: 'security',
    name: 'Dynamic code evaluation',
    description: 'Use of eval(), exec(), or equivalent dynamic code execution.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/os-command-injection',
    category: 'code',
    domain: 'security',
    name: 'OS command injection',
    description: 'Shell command execution with potentially dynamic input.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-hashing',
    category: 'code',
    domain: 'security',
    name: 'Weak hashing algorithm',
    description: 'Use of MD5 or SHA1 which are cryptographically weak.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-ip',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded IP address',
    description: 'Hardcoded IPv4 addresses in string literals.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/clear-text-protocol',
    category: 'code',
    domain: 'security',
    name: 'Clear-text protocol',
    description: 'Use of unencrypted protocols (http://, ftp://, telnet://).',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-certificate',
    category: 'code',
    domain: 'security',
    name: 'Unverified TLS certificate',
    description: 'Disabled TLS certificate verification.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/permissive-cors',
    category: 'code',
    domain: 'security',
    name: 'Permissive CORS configuration',
    description: 'Wildcard CORS origin allowing any domain.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-cookie',
    category: 'code',
    domain: 'security',
    name: 'Insecure cookie',
    description: 'Cookie set without the secure flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/cookie-without-httponly',
    category: 'code',
    domain: 'security',
    name: 'Cookie without httpOnly',
    description: 'Cookie set without the httpOnly flag.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/disabled-auto-escaping',
    category: 'code',
    domain: 'security',
    name: 'Disabled auto-escaping',
    description: 'Template engine with auto-escaping disabled, risking XSS.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/csrf-disabled',
    category: 'code',
    domain: 'security',
    name: 'CSRF protection disabled',
    description: 'Disabling CSRF protection in framework configuration.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-cipher',
    category: 'code',
    domain: 'security',
    name: 'Weak cipher algorithm',
    description: 'Use of weak ciphers such as DES, RC4, or Blowfish.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-crypto-key',
    category: 'code',
    domain: 'security',
    name: 'Weak cryptographic key size',
    description: 'RSA key smaller than 2048 bits or EC key smaller than 256 bits.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/weak-ssl',
    category: 'code',
    domain: 'security',
    name: 'Weak SSL/TLS protocol',
    description: 'Use of deprecated SSL/TLS protocols (SSLv2, SSLv3, TLS 1.0).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-jwt',
    category: 'code',
    domain: 'security',
    name: 'Insecure JWT configuration',
    description: 'JWT signed with none algorithm or other weak algorithm.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/encryption-insecure-mode',
    category: 'code',
    domain: 'security',
    name: 'Insecure encryption mode',
    description: 'Use of ECB mode which does not provide semantic security.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-content-security-policy',
    category: 'code',
    domain: 'security',
    name: 'Missing Content Security Policy',
    description: 'Helmet or Express configured without Content Security Policy.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-frame-ancestors',
    category: 'code',
    domain: 'security',
    name: 'Missing frame ancestors protection',
    description: 'Missing X-Frame-Options or frame-ancestors CSP directive.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-strict-transport',
    category: 'code',
    domain: 'security',
    name: 'Missing HSTS',
    description: 'Helmet configured with HSTS disabled.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-referrer-policy',
    category: 'code',
    domain: 'security',
    name: 'Missing referrer policy',
    description: 'Helmet configured with referrer policy disabled.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/missing-mime-sniff-protection',
    category: 'code',
    domain: 'security',
    name: 'Missing MIME sniff protection',
    description: 'Helmet configured with X-Content-Type-Options (noSniff) disabled.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/server-fingerprinting',
    category: 'code',
    domain: 'security',
    name: 'Server fingerprinting',
    description: 'X-Powered-By header not disabled, leaking server technology.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-hostname',
    category: 'code',
    domain: 'security',
    name: 'Unverified hostname',
    description: 'Disabled hostname verification in TLS connections.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/xml-xxe',
    category: 'code',
    domain: 'security',
    name: 'XML external entity injection',
    description: 'XML parsing without disabling external entities.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unsafe-unzip',
    category: 'code',
    domain: 'security',
    name: 'Unsafe archive extraction',
    description: 'Extracting archives without controlling resource consumption (zip bomb risk).',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/file-permissions-world-accessible',
    category: 'code',
    domain: 'security',
    name: 'World-accessible file permissions',
    description: 'Setting file permissions to 0o777 or similar overly permissive modes.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unrestricted-file-upload',
    category: 'code',
    domain: 'security',
    name: 'Unrestricted file upload',
    description: 'File upload without type or size validation.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hidden-file-exposure',
    category: 'code',
    domain: 'security',
    name: 'Hidden file exposure',
    description: 'Serving dotfiles via express.static without denying access.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/link-target-blank',
    category: 'code',
    domain: 'security',
    name: 'Unsafe target="_blank" link',
    description: 'Link with target="_blank" without rel="noopener" allowing reverse tabnabbing.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/confidential-info-logging',
    category: 'code',
    domain: 'security',
    name: 'Confidential info logging',
    description: 'Logging password, token, or secret variables.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/production-debug-enabled',
    category: 'code',
    domain: 'security',
    name: 'Production debug enabled',
    description: 'Debug mode enabled in configuration, risking information leakage.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/insecure-random',
    category: 'code',
    domain: 'security',
    name: 'Insecure random number generator',
    description: 'Using Math.random() or random.random() for security-sensitive operations.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/ip-forwarding',
    category: 'code',
    domain: 'security',
    name: 'Untrusted IP forwarding header',
    description: 'Trusting X-Forwarded-For header without validation.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/hardcoded-blockchain-mnemonic',
    category: 'code',
    domain: 'security',
    name: 'Hardcoded blockchain mnemonic',
    description: 'BIP39 mnemonic seed phrase hardcoded in source code.',
    enabled: true,
    severity: 'critical',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/dompurify-unsafe-config',
    category: 'code',
    domain: 'security',
    name: 'DOMPurify unsafe configuration',
    description: 'DOMPurify configured with ALLOW_UNKNOWN_PROTOCOLS or ADD_TAGS weakening sanitization.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/disabled-resource-integrity',
    category: 'code',
    domain: 'security',
    name: 'Missing subresource integrity',
    description: 'External script or link tag without integrity attribute.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/path-command-injection',
    category: 'code',
    domain: 'security',
    name: 'Path-based command injection',
    description: 'User input in path.join() passed to fs or exec functions.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/mixed-content',
    category: 'code',
    domain: 'security',
    name: 'Mixed content',
    description: 'Loading HTTP resources from an HTTPS page in JSX src/href attributes.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/subprocess-security',
    category: 'code',
    domain: 'security',
    name: 'Subprocess without full path',
    description: 'subprocess.Popen called without a full path to the executable.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/partial-path-execution',
    category: 'code',
    domain: 'security',
    name: 'Partial path execution',
    description: 'os.exec* called without a full path to the executable.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/ssl-version-unsafe',
    category: 'code',
    domain: 'security',
    name: 'Unsafe SSL/TLS minimum version',
    description: 'Setting minimum SSL/TLS version too low.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/vulnerable-library-import',
    category: 'code',
    domain: 'security',
    name: 'Vulnerable library import',
    description: 'Importing a known vulnerable Python module.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/process-start-no-shell',
    category: 'code',
    domain: 'security',
    name: 'Subprocess with string command',
    description: 'subprocess.Popen with string argument instead of list, risking shell injection.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/non-octal-file-permissions',
    category: 'code',
    domain: 'security',
    name: 'Non-octal file permissions',
    description: 'File permissions passed as decimal instead of octal literal.',
    enabled: true,
    severity: 'medium',
    type: 'deterministic',
  },
  {
    key: 'security/deterministic/unverified-cross-origin-message',
    category: 'code',
    domain: 'security',
    name: 'Unverified cross-origin message',
    description: 'Listening for window messages without checking the origin.',
    enabled: true,
    severity: 'high',
    type: 'deterministic',
  },
]
